ariakit/ariakit

- docs/components/Contents.js
- docs/components/Editor.js
- docs/components/StyleGuideRenderer.js
- src/components/Perpendicular/Perpendicular.md
> Improve mobile experience for docs website

- rollup.config.js
Sorry, I've missed it during the former PR. Was fixing it when you have merged it in 😅
> Fixed using lodash-es in cjs target

- src/components/Step/Step.js
- src/components/Step/__tests__/withStep-test.js
- src/components/Step/withStepState.js
> Add order prop to Step component

- src/enhancers/__tests__/__snapshots__/as-test.js.snap
- src/enhancers/as.js
> Refactor on as enhancer

- docs/components/Banner.js
- docs/components/Brackets.js
- docs/components/Contents.js
- docs/components/GitHubButton.js
- docs/components/Intro.js
- docs/components/IntroPanel.js
- docs/components/IntroTabs.js
- docs/components/Link.js
- docs/components/Menu.js
- docs/components/StyleGuideRenderer.js
- docs/contents/intro.md
- docs/contents/styling.md
- src/enhancers/__tests__/__snapshots__/as-test.js.snap
- src/enhancers/__tests__/as-test.js
- src/enhancers/as.js
Encourage usage of `styled()` instead.
> Remove extend

- docs/as.md
- docs/behaviors.md
- docs/create-react-app.md
- docs/install.md
- docs/intro.md
- docs/state-containers.md
- docs/styling.md
- styleguide.config.js
changed the glob on sg config to *.js because it works the same and it's simpler.
> added content from old site, update sg config, changed some words

- .travis.yml
- package.json
- rollup.config.js
- src/components/Hidden/HiddenHide.js
- src/components/Hidden/HiddenShow.js
- src/components/Hidden/HiddenToggle.js
- src/components/Step/Step.js
- src/components/Step/StepHide.js
- src/components/Step/StepNext.js
- src/components/Step/StepPrevious.js
- src/components/Step/StepShow.js
- src/components/Step/StepToggle.js
- src/components/Tabs/TabsPanel.js
- src/components/Tabs/TabsTab.js
- src/enhancers/as.js
- src/utils/callAll.js
- src/utils/pickHTMLProps.js
- src/utils/pickSVGProps.js
- yarn.lock
Using https://github.com/diegohaz/singel to check if Reas components conform to the Singel pattern.
> Test components with Singel

- src/components/Blockquote/Blockquote.js
- src/components/Blockquote/Blockquote.md
- src/components/Blockquote/index.js
- src/components/index.js
> BlockQuote Component

- styleguide.config.js
- website/src/pages/Section.js
> Add github src links for all component sections

- website/src/pages/Section.js
- website/src/utils/findNonEmptySiblingSection.js
> Added previous section and next section links

- website/src/components/ScrollToTop.js
- website/src/index.js
> Scroll to top when switching between pages

- src/components/Step/StepContainer.js
- src/components/Table/Table.js
- website/src/components/ContainerAPITable.js
- website/src/components/PropTypesTable.js
- website/src/components/SectionGitHubButtons.js
- website/src/components/SectionUses.js
- website/src/elements/SectionContentWrapper.js
- website/src/elements/TableWrapper.js
- website/src/pages/Section.js
- website/src/theme.js
- yarn.lock
And some refactors (basically abstracting Section.js)
Fix #114
> Add Container API Table

- styleguide.config.js
- website/src/template.js
> Add Google Tag Manager for Analytics

- src/components/Tabs/TabsPanel.js
Testing:
1. Go to https://deploy-preview-144--reakit.netlify.com/components/tabs
2. Add a `visible` prop to the second `Tabs.Panel`
Try to do the same thing on https://reakit.io/components/tabs
> Make it possible to pass visible to TabsPanel

- src/components/Hidden/Hidden.js
- src/components/Hidden/__tests__/Hidden-test.js
- src/components/Step/Step.js
- src/components/Tabs/TabsPanel.js
Will work on the other changes in a separate PR.
Fix #98 
Preview: https://deploy-preview-145--reakit.netlify.com/
> Replace destroy prop by unmount on Hidden

- src/components/Table/Table.md
- src/components/Table/TableCell.js
- website/src/components/ContainerAPITable.js
- website/src/components/PropTypesTable.js
> Replace header prop by as='th' on TableCell

- CHANGELOG.md
- README.md
- docs/accessibility.md
- docs/as.md
- docs/composability.md
- package.json
- src/components/Link/Link.md
- src/components/Navigation/Navigation.md
- website/src/components/Footer.js
- website/src/components/Header.js
- website/src/components/HeroGitHubButton.js
- website/src/containers/GitHubStarsContainer.js
- website/src/utils/getSectionGitHubUrl.js
> Move to reakit org

- website/src/components/Header.js
- website/src/components/MobileSidebar.js
- website/src/utils/getRelease.js
Ref #113 
| Desktop  |
|:-:|
| ![screen shot 2018-07-27 at 15 32 11](https://user-images.githubusercontent.com/10820159/43340679-7c090460-91b3-11e8-92e6-9c9bd4151c39.png)  | 
| Mobile  |
|:-:|
| ![screen shot 2018-07-27 at 20 07 11](https://user-images.githubusercontent.com/10820159/43350107-f6fff7ba-91da-11e8-8c54-2830d2d162c6.png) |
> Add version on Header

- src/components/Avatar/Avatar.js
- src/components/Avatar/Avatar.md
- src/components/Avatar/index.js
- src/components/Toolbar/Toolbar.md
- src/components/index.js
Preview: https://deploy-preview-175--reakit.netlify.com/components/avatar
Updated toolbar example: https://deploy-preview-175--reakit.netlify.com/components/toolbar
> Add Avatar component

- packages/website/src/components/Markdown.js
- packages/website/src/components/Menu.js
- packages/website/src/components/MobileSidebar.js
- packages/website/src/components/SectionHeader.js
- packages/website/src/pages/Section.js
- packages/website/src/pages/Sections.js
- packages/website/src/theme.js
Before:
After:
[full preview](https://deploy-preview-197--reakit.netlify.com/)
> style(website): Spacing and font size adjustments

- package.json
- packages/reakit/.npmignore
- packages/reakit/package.json
- yarn.lock
> Small things

- packages/reakit/src/Popover/Popover.md
> Attempts to clarify popover example #1

- package.json
- yarn.lock
Pre-commit hook for prettier, closes https://github.com/reakit/reakit/issues/179
> chore: pre-commit hook for prettier

- CONTRIBUTING.md
> Update Contribution guides with TS

- README.md
- packages/reakit/README.md
> Update readme.md with browserStack logo

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Add templates for pull requests and for issues
> Pull request and issue templates

- packages/reakit/src/Code/Code.tsx
- packages/reakit/src/Code/index.ts
- packages/reakit/src/Flex/Flex.ts
- packages/reakit/src/Flex/index.ts
- packages/reakit/src/_utils/types.ts
- packages/reakit/src/as.tsx
- packages/reakit/src/index.ts
- packages/reakit/test.tsx
Part of #219
Adds types to Code, Flex
**Did you add tests for your changes?**
No
No
> Typing Code, Flex components

- packages/reakit/src/Hidden/Hidden.tsx
https://twitter.com/sebmarkbage/status/1041989537575124992
> feat: Add `hidden` attribute to `Hidden`

- packages/website/src/components/Filter.js
- packages/website/src/components/Menu.js
Adds Filter to website. Filter has keydown handlers to focus self on "/".
**Did you add tests for your changes?**
No need imo.
No, it's website.
> add Filter component with keydown "/" focus

- .github/PULL_REQUEST_TEMPLATE.md
Flexibilizes the template text. Not all PR's need tests. Adds conditions that if a PR
- is big or important
- decreases coverage
Then it requires tests.
**Did you add tests for your changes?**
Nope.
No :)
> Change template to be more flexible

- packages/reakit/src/Card/index.ts
- packages/reakit/src/Grid/index.ts
- packages/reakit/src/Group/index.ts
- packages/reakit/src/Hidden/index.ts
- packages/reakit/src/Overlay/index.ts
- packages/reakit/src/Sidebar/index.ts
- packages/reakit/src/Table/index.ts
As I said here https://github.com/reakit/reakit/pull/251, I think this approach is more **ts-friendly** and more **readable** and elegant.
This PR is just a proposal, feel free to discuss here if you want to.
*Note: I did not touch the components Step, Popover, Tabs, Toolbar, Tooltip because they are not in TS yet*
> [Proposal] Refactor component's index to export using Object.assign

- packages/website/src/components/Filter.js
> fix: website keypress focus when user is on a textarea or input

- CONTRIBUTING.md
- TYPING_GUIDELINES.md
Create typing guidelines and reference it on contribution guide.
No
> Add typing guidelines

- packages/reakit/src/Provider/Provider.md
Duplicate `container` declaration causes an error in the preview for Provider. Just removed the duplicate declaration.
> Remove duplicate container declaration

- packages/reakit/src/Popover/Popover.tsx
> fix: blur on popover

- packages/reakit/src/Overlay/__tests__/Overlay-test.tsx
- packages/reakit/src/Overlay/__tests__/OverlayContainer-test.ts
- packages/reakit/src/Overlay/__tests__/OverlayHide-test.tsx
- packages/reakit/src/Overlay/__tests__/OverlayShow-test.tsx
- packages/reakit/src/Overlay/__tests__/OverlayToggle-test.tsx
> test: Overlay

- packages/reakit/src/Toolbar/__tests__/Toolbar-test.tsx
- packages/reakit/src/Toolbar/__tests__/ToolbarContent-test.tsx
- packages/reakit/src/Toolbar/__tests__/ToolbarFocusable-test.tsx
Tests for Toolbar and sub-components.
No
#271
> Tests: Toolbar

- packages/reakit/src/Tabs/TabsTab.tsx
- packages/reakit/src/Tabs/__tests__/Tabs-test.tsx
- packages/reakit/src/Tabs/__tests__/TabsNext-test.tsx
- packages/reakit/src/Tabs/__tests__/TabsPanel-test.tsx
- packages/reakit/src/Tabs/__tests__/TabsPrevious-test.tsx
- packages/reakit/src/Tabs/__tests__/TabsTab-test.tsx
Added tests for Tabs component and sub-components.
No.
> Tests: Tabs

- packages/reakit/src/Table/__tests__/Table-test.tsx
- packages/reakit/src/Table/__tests__/TableWrapper-test.tsx
Added tests for Table and TableWrapper.
No
#271
> Tests: Table

- CONTRIBUTING.md
Fixes "How to start contributing" doc broken anchor
No
> Fix how to start contributing anchor

- packages/reakit/src/Label/__tests__/Label-test.tsx
Adds tests for Label component
No
> Tests: Label

- packages/reakit/src/Flex/__tests__/Flex-test.tsx
- packages/reakit/src/Grid/__tests__/Grid-test.tsx
- packages/reakit/src/Grid/__tests__/GridItem-test.tsx
- packages/reakit/src/Group/__tests__/Group-test.tsx
- packages/reakit/src/Group/__tests__/GroupItem-test.tsx
- packages/reakit/src/Heading/__tests__/Heading-test.tsx
Unit tests (mostly _snapshot testing_) for:
- [`<Heading />`](https://reakit.io/components/heading)
- [`<Group />`](https://reakit.io/components/group)
- [`<Flex />`](https://reakit.io/components/flex)
- [`<Grid />`](https://reakit.io/components/grid)
I'm getting two _small_ and probably related type errors:
`<Flex />` props `wrap` 🤷🏻‍♂️ ( [type declaration](https://github.com/reakit/reakit/blob/master/packages/reakit/src/Flex/Flex.ts#L14) )
```bash
Type 'true' is not assignable to type 'undefined'.
219   const { container } = render(<Flex wrap />);
^^^^
```
`<Grid />` prop `row` 🤷🏻‍♂️ ( [type declaration](https://github.com/reakit/reakit/blob/master/packages/reakit/src/Grid/Grid.ts#L16) )
```bash
Type 'string' is not assignable to type 'number | undefined'.
219   const { container } = …
```
> Testing more components ✅

- packages/reakit/src/Image/__tests__/Image-test.tsx
- packages/reakit/src/Inline/__tests__/Inline-test.tsx
- packages/reakit/src/InlineBlock/__tests__/InlineBlock-test.tsx
- packages/reakit/src/InlineFlex/__tests__/InlineFlex-test.tsx
Unit tests (mostly _snapshot testing_) for:
- [`<Image />`](https://reakit.io/components/image)
- [`<Inline />`](https://reakit.io/components/inline)
- [`<InlineBlock />`](https://reakit.io/components/inlineblock)
- [`<InlineFlex />`](https://reakit.io/components/inlineflex)
Just a _patch_ bump I believe. See #271.
> Getting there ✅

- packages/reakit/src/Card/__tests__/Card-test.tsx
- packages/reakit/src/Card/__tests__/CardFit-test.tsx
- packages/reakit/src/Paragraph/__tests__/Paragraph-test.tsx
Unit tests (mostly _snapshot testing_) for:
- [`<Card />`](https://reakit.io/components/card)
- [`<CardFit />`](https://reakit.io/components/cardfit)
- [`<Paragraph />`](https://reakit.io/components/paragraph)
Just a _patch_ bump I believe. See #271.
> More tests ✅

- packages/reakit/src/Link/__tests__/Link-test.tsx
- packages/reakit/src/List/__tests__/List-test.tsx
- packages/reakit/src/Navigation/__tests__/Navigation-test.tsx
This PR contains the changes from @rafael-vitor in #308 #309 #310 but _cherry-picked_ so the git history stays clean.
Just a _patch_ bump I believe. See #271.
> Test <Nagivation /> <List /> <Link />

- packages/reakit/src/Box/__test__/Box-test.tsx
- packages/reakit/src/Box/__test__/__snapshots__/Box-test.tsx.snap
this PR contains testing for the box component 
link of the issue https://github.com/reakit/reakit/issues/271
> test<box> add test to box components #271

- packages/reakit/src/Input/Input.md
Fixing an uncomplete merge in docs
> Uncomplete merge fix

- packages/reakit/src/Portal/Portal.md
> fixing typo

- README.md
The link for composable page was broken (404)
**motivation**
Keep the link live so other users can access it
docs (README.md)
No
> Fix composable link

- packages/reakit/src/Checkbox/Checkbox.ts
- packages/reakit/src/Dialog/Dialog.tsx
- packages/reakit/src/Dialog/README.md
- packages/reakit/src/Dialog/__utils/useEventListenerOutside.ts
- packages/reakit/src/Dialog/__utils/useFocusOnHide.ts
- packages/reakit/src/Dialog/__utils/useFocusOnShow.ts
- packages/reakit/src/Dialog/__utils/useFocusTrap.ts
- packages/reakit/src/Hidden/Hidden.ts
- packages/reakit/src/Hidden/HiddenState.ts
- packages/reakit/src/Hidden/README.md
- packages/reakit/src/Menu/Menu.tsx
- packages/reakit/src/Menu/MenuDisclosure.ts
- packages/reakit/src/Menu/MenuItem.tsx
- packages/reakit/src/Menu/StaticMenu.tsx
- packages/reakit/src/Popover/Popover.ts
- packages/reakit/src/Popover/PopoverState.ts
- packages/reakit/src/Radio/RadioGroup.tsx
- packages/reakit/src/Rover/Rover.ts
- packages/reakit/src/Rover/RoverState.ts
- packages/reakit/src/Tab/TabList.tsx
- packages/reakit/src/Toolbar/Toolbar.tsx
- packages/reakit/src/__utils/warning.ts
This PR enables conditional renders on the `Hidden` component (and its derivative) by using render props.
It also warns against conditionally render the `Hidden` components themselves as this makes some Reakit features not work.
> feat: Enable conditional render on `Hidden` components with render props

- packages/reakit/src/VisuallyHidden/README.md
Small typo fix to VisuallyHidden docs.
> Fixed typo in VisuallyHidden docs

- packages/reakit/src/Form/README.md
> Include section on textareas in `Form` docs

- packages/reakit/src/Popover/PopoverState.ts
- packages/reakit/src/Popover/__tests__/index-test.tsx
- packages/reakit/src/Tooltip/__tests__/index-test.tsx
- stories/index.stories.tsx
> fix: Fix `Tooltip` error when `visible` is initially set to `true`

- packages/reakit/src/Hidden/Hidden.ts
- packages/reakit/src/Hidden/HiddenState.ts
- packages/reakit/src/Hidden/__tests__/HiddenState-test.ts
> fix: Fix `Hidden` not setting `unstable_animating` to `false` while visible

- packages/reakit/src/Checkbox/Checkbox.ts
- packages/reakit/src/Checkbox/__tests__/index-test.tsx
- packages/reakit/src/Checkbox/__utils/useDelayedEvent.ts
- packages/reakit/src/Checkbox/__utils/useIndeterminateState.ts
> fix: Fix `Checkbox` `event.target.checked` value inside `onChange` event

- packages/reakit/src/Tabbable/Tabbable.ts
> fix: Fix `FormInput` as `textarea` caret position when focusing

- packages/reakit/src/Portal/Portal.tsx
Export `PortalContext` as described in reakit/reakit#428
Nope
> fix: Export `PortalContext`

- packages/reakit/src/Form/FormSubmitButton.ts
- packages/reakit/src/Form/__tests__/FormSubmitButton-test.tsx
> fix: Fix `FormSubmitButton` ignoring `disabled` prop

- packages/reakit/src/Popover/PopoverArrow.tsx
> fix: Fix `PopoverArrow` ignoring `size` prop

- packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts
> fix: Fix `Dialog` closing when clicking inside it and dragging outside

- packages/reakit-system-palette/jest.config.js
- packages/reakit/jest.config.js
- packages/reakit/src/Dialog/__utils/usePreventBodyScroll.ts
Reverting #508 because of https://github.com/reakit/reakit/pull/508#issuecomment-566091262
> Revert "importing directly body-scroll-lock from es modules to fix rollup build"

- packages/reakit/src/Radio/README.md
Added Radio example with default value
> docs: add default value example to Radio docs

- packages/reakit/src/Dialog/__utils/useFocusTrap.ts
> fix: check for classList existence before use

- packages/reakit/src/Portal/Portal.tsx
> fix: Fix portaled components without dimensions in the first render

- packages/reakit/src/Disclosure/DisclosureContent.ts
> fix: Fix `transitionEnd` capturing children transitions

- packages/reakit/src/Disclosure/README.md
Fixes a typo noted while reading docs
> Fix typo in Disclosure readme

- packages/reakit/src/Dialog/__examples__/DialogWithForm/__tests__/index-test.tsx
- packages/reakit/src/Dialog/__examples__/DialogWithForm/index.tsx
Add an example using a form in a modal.
It will increase the list of examples related to #626
> examples: modal with form

- packages/reakit/src/Tab/__examples__/TabWithModal/__test__/index-test.tsx
- packages/reakit/src/Tab/__examples__/TabWithModal/index.tsx
Add an example using a tab in a modal.
> chore: Add example Tab with Modal

- packages/reakit/src/Dialog/README.md
- packages/reakit/src/Menu/README.md
- packages/reakit/src/Popover/README.md
- packages/reakit/src/Tooltip/README.md
This PR improves the abstracting examples, adding ref as you taught me in this [question](https://spectrum.chat/reakit/general/get-tooltipreference-ref-using-tooltip-abstracting-example~2aa76287-fb6c-446a-9f81-4b5521160b48) 
No
> Add ref to abstracting examples

- packages/reakit/src/Composite/CompositeItem.ts
- packages/reakit/src/Composite/CompositeState.ts
- packages/reakit/src/Composite/__examples__/NestedCompositeItems/__tests__/index-test.tsx
- packages/reakit/src/Composite/__examples__/NestedCompositeItems/index.tsx
- packages/reakit/src/Composite/__examples__/VirtualNestedCompositeItems/__tests__/index-test.tsx
- packages/reakit/src/Composite/__examples__/VirtualNestedCompositeItems/index.tsx
- packages/reakit/src/Tabbable/__utils/useFocusOnMouseDown.ts
> feat: Support nested `CompositeItem`s

- packages/reakit/src/Disclosure/DisclosureContent.ts
> fix: Fix enter animation on `DisclosureContent` and derivative components

- CONTRIBUTING.md
Add info about branches to contribution guidelines
> chore: Add branches information to CONTRIBUTING.md

- packages/reakit/src/Menu/README.md
Updating documentation for updated component.
> Update Menu documentation

- packages/reakit/src/Composite/Composite.ts
- packages/reakit/src/Composite/README.md
- packages/reakit/src/Composite/__keys.ts
- packages/reakit/src/Composite/__tests__/index-test.tsx
- packages/reakit/src/Grid/README.md
- packages/reakit/src/Menu/README.md
- packages/reakit/src/Radio/README.md
- packages/reakit/src/Tab/README.md
- packages/reakit/src/Toolbar/README.md
> feat: Improve types for composite roles

- packages/reakit/src/Composite/__utils/sortBasedOnDOMPosition.ts
> Handle sort inconsistencies in sortBasedOnDOMPosition

- packages/reakit-playground/package.json
- packages/reakit-system-bootstrap/package.json
- packages/reakit-system-palette/package.json
- packages/reakit-system/package.json
- packages/reakit-test-utils/package.json
- packages/reakit-utils/package.json
- packages/reakit-warning/package.json
- packages/reakit/package.json
> fix: Add React 17 to peer dependencies

- packages/reakit/src/Composite/__utils/useSortBasedOnDOMPosition.ts
Closes #827
Check generated CodeSandbox: https://codesandbox.io/s/red-moon-4b6yg
No
> fix: Fix automatic sort of `Composite` items in fixed containers

- packages/website/src/components/CoreLayout.tsx
- packages/website/src/components/Header.tsx
It's being a lot of months since we [added the **Black Lives Matter** banner](#663) to Reakit's documentation.
Hopefully, it helped awareness about the issue and donations for the movement. I personally think it's ok to remove it now?
Run this branch and the website locally.
Affects only the website, not the main `reakit` package.
> Remove BLM banner 🪴

- packages/reakit/src/Radio/__examples__/RadioWithRadioGroup/__tests__/index-test.tsx
- packages/reakit/src/Radio/__examples__/RadioWithRadioGroup/index.tsx
- packages/reakit/src/Radio/__examples__/index.story.ts
Add example on storybook for `<Radio  />`
Related to #626 discussion.
> Examples: Radio

- packages/reakit/src/Button/__examples__/ButtonWithTooltip/__tests__/index-test.tsx
- packages/reakit/src/Popover/PopoverState.ts
Closes #852
Open the CodeSandbox created for this PR and follow the instructions on #852
No.
> fix: Fix Popover initial position

- packages/reakit/src/Tabbable/Tabbable.ts
Refactored multiple || statements with array.includes.
For new features in the main package, use `next` branch as target. For other kinds of PRs, like bugfixes and chores, you can target `master` directly. [Learn more](https://github.com/reakit/reakit/blob/master/CONTRIBUTING.md#branches).
**Does this PR introduce breaking changes?** No.
> refactor: refactored tabbable utilities

- packages/reakit/src/Group/README.md
I noticed the documentation was missing this information!
> doc: update Group "Composition" section

- contributing.md
- scripts/pages/dependency-loader.js
- scripts/pages/pages-webpack-plugin.js
- scripts/pages/utils.js
> fix: Fix dev workflow on Windows

- packages/ariakit/src/checkbox/__examples__/checkbox/index.tsx
- packages/ariakit/src/checkbox/__examples__/checkbox/style.css
- packages/ariakit/src/checkbox/__examples__/checkbox/test.tsx
- packages/ariakit/src/checkbox/readme.md
> chore: Add `checkbox` example

- packages/ariakit/src/tooltip/__examples__/tooltip/index.tsx
- packages/ariakit/src/tooltip/__examples__/tooltip/style.css
- packages/ariakit/src/tooltip/__examples__/tooltip/test.tsx
- packages/ariakit/src/tooltip/readme.md
basic tooltip example for #939
> chore: Add `tooltip` example

- packages/ariakit/src/group/__examples__/group/index.tsx
- packages/ariakit/src/group/__examples__/group/style.css
- packages/ariakit/src/group/__examples__/group/test.tsx
#939 Added Default Group example + test 
http://localhost:3000/examples/group
First github pull to an non-owned project ever. So I hope everything is fine :-)
> chore: Add `group` example

- packages/ariakit/src/command/__examples__/command-space-disabled/index.tsx
- packages/ariakit/src/command/__examples__/command-space-disabled/style.css
- packages/ariakit/src/command/__examples__/command-space-disabled/test.tsx
- packages/website/pages/index.tsx
> chore: Add Command clickOnSpace false Example

- packages/ariakit/src/popover/popover-state.ts
> fix: Fix Popover warning when placement is auto base

- jest.config.js
- packages/ariakit-utils/src/__tests__/events-test.ts
Follow on to #1120 for events.
> chore: Add test coverage to events utils

- packages/ariakit/src/collection/collection-state.ts
- packages/ariakit/src/combobox/combobox.ts
- packages/ariakit/src/select/__examples__/select-combobox/test.tsx
> fix: Fix `Select` + `Combobox` not getting correct value

- packages/ariakit/src/composite/composite-item.tsx
- packages/ariakit/src/menu/__examples__/menu-combobox/test.tsx
- packages/ariakit/src/menu/menu.ts
> fix: Fix conflict on `Menu` and `Combobox` that auto selects item on backspace

- packages/ariakit/src/toolbar/__examples__/toolbar/index.tsx
- packages/ariakit/src/toolbar/__examples__/toolbar/style.css
- packages/ariakit/src/toolbar/__examples__/toolbar/test.tsx
- packages/website/pages/index.tsx
> chore: Add `toolbar` example

- packages/ariakit-utils/src/__tests__/misc-test.ts
> chore: Add tests for ariakit utils/misc

- packages/website/next.config.js
> Fix critical dependency warning

- .changeset/select-focus-visible-flash.md
- packages/ariakit/src/focusable/focusable.ts
> Fix Select focus-visible flash

- .changeset/select-label-as-div.md
- packages/ariakit/src/select/select-label.ts
> Fix SelectLabelProps type to default to div instead of label

- .changeset/portal-suspense.md
- packages/ariakit/src/portal/__examples__/portal-lazy/index.tsx
- packages/ariakit/src/portal/__examples__/portal-lazy/style.css
- packages/ariakit/src/portal/__examples__/portal-lazy/test.tsx
- packages/ariakit/src/portal/portal.tsx
- scripts/pages/utils.js
> Fix Portal with parent Suspense

- packages/ariakit-utils/src/__tests__/hooks-test.tsx
Added some tests for the hooks utils. A few of the hooks I struggled with how to test completely but overall this feels like a good step forward. The hook I struggled most with thinking through how to test was `useControlledState` so feel free to throw out any suggestions around that test.
> Chore: Adds tests for hooks utils

- packages/ariakit-utils/src/__tests__/system-test.tsx
Tests to cover the system utils
> Adds tests for system utils

- .changeset/add-global-event-listener-frames-undefined.md
- packages/ariakit-utils/src/__tests__/events-test.ts
- packages/ariakit-utils/src/events.ts
> Fix addGlobalEventListener when window.frames is undefined

- .changeset/test-is-browser-error.md
- packages/ariakit-test/src/__utils.ts
- packages/ariakit-test/src/act.ts
> [ariakit-test] Stop accessing isBrowser before initialization

- packages/ariakit/src/portal/__examples__/portal/index.tsx
- packages/ariakit/src/portal/__examples__/portal/style.css
- packages/ariakit/src/portal/__examples__/portal/test.tsx
- packages/website/pages/index.tsx
Adds the `portal` example for https://github.com/ariakit/ariakit/issues/939
> chore: Add portal example

- packages/ariakit/src/combobox/__examples__/combobox-disclosure/index.tsx
- packages/ariakit/src/combobox/__examples__/combobox-disclosure/style.css
- packages/ariakit/src/combobox/__examples__/combobox-disclosure/test.tsx
- packages/website/pages/index.tsx
Add `combobox-disclosure` example for #939
> chore: Add `combobox-disclosure` example

- .changeset/hovercard-strict-mode.md
- .changeset/menu-bar-strict-mode.md
- .changeset/test-strict-mode.md
- .changeset/utils-boolean-or-callback-generics.md
- .changeset/utils-update-effect-strict-mode.md
- packages/ariakit-test/src/render.ts
- packages/ariakit-utils/src/__tests__/hooks-test.tsx
- packages/ariakit-utils/src/__tests__/system-test.tsx
- packages/ariakit-utils/src/hooks.ts
- packages/ariakit-utils/src/types.ts
- packages/ariakit/src/hovercard/hovercard.tsx
- packages/ariakit/src/menu/menu.ts
Also running tests on strict mode so we can catch future bugs.
> Fix MenuBar initial focus on strict mode

- .changeset/select-initial-focus.md
- packages/ariakit/src/select/select-popover.ts
- packages/website/next.config.js
> Fix Select initial focus on strict mode

- .changeset/focus-trap-region.md
- packages/ariakit/src/dialog/dialog.tsx
- packages/ariakit/src/focus-trap/__examples__/focus-trap-region/index.tsx
- packages/ariakit/src/focus-trap/__examples__/focus-trap-region/style.css
- packages/ariakit/src/focus-trap/__examples__/focus-trap-region/test.tsx
- packages/ariakit/src/focus-trap/focus-trap-region.tsx
- packages/ariakit/src/focus-trap/index.ts
- packages/website/pages/index.tsx
- Added <FocusTrapRegion \/> component
Example: 
```tsx
<FocusTrapRegion enabled={true | false}>
<Button>click me</Button>
<Button>trap focus</Button>
<Button disabled>disabled Button</Button>
</FocusTrapRegion>
```
Let me know if any other API or feature changes needed. 
Closes #1462
> Add FocusTrapRegion component

- packages/ariakit/src/menu/__examples__/menu-item-radio/index.tsx
- packages/ariakit/src/menu/__examples__/menu-item-radio/style.css
- packages/ariakit/src/menu/__examples__/menu-item-radio/test.tsx
- packages/website/pages/index.tsx
Add `menu-item-radio` example for #939
> Add menu-item-radio example

- .changeset/select-animated-initial-focus.md
- packages/ariakit/src/disclosure/disclosure-content.ts
- packages/ariakit/src/portal/portal.tsx
- packages/ariakit/src/select/__examples__/select-animated/index.tsx
- packages/ariakit/src/select/__examples__/select-animated/style.css
- packages/ariakit/src/select/__examples__/select-animated/test-chrome.ts
- packages/ariakit/src/select/select-popover.ts
> Fix initial focus on animated Select

- .changeset/select-scroll-on-space.md
- packages/ariakit/src/select/select.tsx
> Prevent page from scrolling when pressing Space on Select

- .changeset/select-popover-composite-attributes.md
- packages/ariakit/src/select/select-list.ts
> Fix SelectPopover props with composite set to false

- .changeset/combobox-popover-modal.md
- packages/ariakit/src/combobox/combobox-popover.ts
> Remove modal prop from ComboboxPopover

- .changeset/popover-disclosure-arrow-placement.md
- packages/ariakit/src/popover/popover-disclosure-arrow.tsx
Usage:
```jsx
<PopoverDisclosureArrow placement="right" />
```
> Add placement prop to PopoverDisclosureArrow

- .changeset/floating-ui.md
- package-lock.json
- packages/ariakit/package.json
> Update dependency @floating-ui/dom to v1

- .changeset/combobox-cancel-hide-popover.md
- packages/ariakit/src/combobox/__examples__/combobox-cancel/test.tsx
- packages/ariakit/src/combobox/combobox.ts
Related to https://github.com/ariakit/ariakit/issues/1652#issuecomment-1191996014
> Fix ComboboxCancel closing ComboboxPopover when focused

- .changeset/popover-tooltip-relative-placement.md
- packages/ariakit/src/menu/__examples__/menu-slide/menu.tsx
- packages/ariakit/src/popover/popover.tsx
- packages/ariakit/src/tooltip/tooltip.tsx
> Fix Popover/Tooltip position within relative container

- .changeset/combobox-cancel-auto-select.md
- packages/ariakit/src/combobox/__examples__/combobox-cancel/index.tsx
- packages/ariakit/src/combobox/__examples__/combobox-cancel/test.tsx
- packages/ariakit/src/combobox/combobox.ts
> Fix autoSelect behavior when blurring Combobox

- .changeset/hovercard-hide-after-scroll.md
- .changeset/utils-use-is-mouse-moving.md
- packages/ariakit-utils/src/hooks.ts
- packages/ariakit/src/composite/composite-hover.ts
- packages/ariakit/src/hovercard/__examples__/hovercard/test-browser.ts
- packages/ariakit/src/hovercard/hovercard-anchor.ts
- packages/ariakit/src/hovercard/hovercard.tsx
> Fix Hovercard not hiding after scroll

- .changeset/portal-blur-event-order.md
- packages/ariakit/src/popover/__examples__/popover-focus-within/index.tsx
- packages/ariakit/src/popover/__examples__/popover-focus-within/popover.tsx
- packages/ariakit/src/popover/__examples__/popover-focus-within/style.css
- packages/ariakit/src/popover/__examples__/popover-focus-within/test.tsx
- packages/ariakit/src/portal/portal.tsx
> Fix blur event order on Portal with preserveTabOrder set to true

- .changeset/collection-items-order.md
- packages/ariakit/src/collection/collection-state.ts
Fixes https://github.com/ariakit/ariakit/issues/1747
> fix: Collection Items are not correctly ordered when adding items from start

- package-lock.json
- packages/ariakit-react-utils/.gitignore
- packages/ariakit-react-utils/package.json
- packages/ariakit-utils/.gitignore
These changes were missing from #1819.
> Fix missing dependency and .gitignores

- .changeset/checkbox-value-attribute.md
- packages/ariakit/src/checkbox/__examples__/checkbox-state-with-value/index.tsx
- packages/ariakit/src/checkbox/__examples__/checkbox-state-with-value/readme.md
- packages/ariakit/src/checkbox/__examples__/checkbox-state-with-value/style.css
- packages/ariakit/src/checkbox/__examples__/checkbox-state-with-value/test.tsx
- packages/ariakit/src/checkbox/checkbox.tsx
Closes #2223 
Had to create this PR to add changesets (the other PR doesn't allow edits from maintainers).
> Fix checkbox state with value attribute

- guide/400-component-stores.md
- package-lock.json
- package.json
- website/app/(main)/[category]/[page]/page.tsx
- website/build-pages/config.js
- website/components/code-block.tsx
- website/utils/rehype-code-meta.ts
> Add component stores guide to the docs

- .changeset/lemon-experts-cheat.md
- packages/ariakit-react-core/src/menu/menu-item-checkbox.ts
- packages/ariakit-react-core/src/menu/menu-item-radio.tsx
- packages/ariakit-react-core/src/menu/menu-item.ts
> Fix error messages on Menu components

- .changeset/plenty-pianos-bake.md
- examples/form-callback-queue/index.tsx
- examples/form-callback-queue/style.css
- examples/form-callback-queue/test.ts
- examples/form/style.css
- packages/ariakit-core/src/collection/collection-store.ts
- packages/ariakit-core/src/form/form-store.ts
- packages/ariakit-react-core/src/form/form-field.ts
- packages/ariakit-react-core/src/form/form-store.ts
- packages/ariakit-react-core/src/utils/store.tsx
Closes #2282
The changes on this PR are based on https://github.com/ariakit/ariakit/issues/2282#issuecomment-1522537348
> Make sure Form callbacks run in a consistent order

- package-lock.json
- package.json
> Revert "Update dependency marked to v5"

- .changeset/bright-doors-buy.md
- scripts/build/utils.js
Closes #2400 
Closes #2483
Related to #2487
> Add types field to proxy package.json files

- .changeset/combobox-auto-select-scroll.md
- packages/ariakit-react-core/src/combobox/combobox.ts
Closes #2398
CodeSandbox using Tanstack Virtual: https://codesandbox.io/s/ariakit-select-combobox-with-react-virtual-2kg8mm
> Fix Combobox autoSelect with virualized items

- package-lock.json
- package.json
> Revert "Update dependency next to v13.4.9"

- .changeset/store-controlled-flush-sync.md
- examples/combobox-group/test-browser.ts
- packages/ariakit-react-core/src/combobox/combobox.ts
- packages/ariakit-react-core/src/utils/store.tsx
> Flush updates synchronously on controlled component stores

- .changeset/dialog-nested-parent-backdrop.md
- examples/dialog-nested-multiple/index.tsx
- examples/dialog-nested-multiple/style.css
- examples/dialog-nested-multiple/test-browser.ts
- packages/ariakit-react-core/src/dialog/utils/mark-tree-outside.ts
- packages/ariakit-react-core/src/dialog/utils/walk-tree-outside.ts
> Fix nested dialog with custom parent backdrop

- .changeset/menu-tooltip-1.md
- .changeset/menu-tooltip-2.md
- .changeset/menu-tooltip-3.md
- .github/workflows/main.yml
- examples/menu-tooltip-multiple/index.tsx
- examples/menu-tooltip-multiple/menu.tsx
- examples/menu-tooltip-multiple/style.css
- examples/menu-tooltip-multiple/test.ts
- examples/menu-tooltip-multiple/tooltip.tsx
- examples/tooltip/test.ts
- packages/ariakit-react-core/src/dialog/dialog.tsx
- packages/ariakit-react-core/src/dialog/utils/use-hide-on-interact-outside.ts
- packages/ariakit-react-core/src/tooltip/tooltip-anchor.ts
- packages/ariakit-react-core/src/utils/store.tsx
This PR adds internal examples and tests for `Menu` and `Tooltip` and fixes some related issues. More details on the changeset files.
> Fix Menu with Tooltip issues

- .changeset/collection-controlled.md
- examples/collection-controlled/index.tsx
- examples/collection-controlled/style.css
- examples/collection-controlled/test.ts
- examples/combobox-min-length/test.ts
- packages/ariakit-react-core/src/collection/collection-item.ts
- packages/ariakit-react-core/src/combobox/combobox.ts
- packages/ariakit-react-core/src/utils/store.tsx
> Fix controlled collection

- packages/ariakit-core/src/collection/collection-store.ts
- packages/ariakit-core/src/combobox/combobox-store.ts
- packages/ariakit-core/src/composite/composite-store.ts
- packages/ariakit-core/src/disclosure/disclosure-store.ts
- packages/ariakit-core/src/menu/menu-store.ts
- packages/ariakit-core/src/select/select-store.ts
- packages/ariakit-core/src/tab/tab-store.ts
- packages/ariakit-core/src/utils/store.ts
- packages/ariakit-react-core/src/composite/composite-overflow-disclosure.ts
- packages/ariakit-react-core/src/dialog/utils/use-nested-dialogs.tsx
- packages/ariakit-react-core/src/hovercard/hovercard-disclosure.tsx
- packages/ariakit-react-core/src/hovercard/hovercard.tsx
- packages/ariakit-react-core/src/menu/menu-button.tsx
- packages/ariakit-react-core/src/tooltip/tooltip-anchor.ts
- packages/ariakit-react-core/src/utils/store.tsx
- website/components/header-menu.tsx
> Pass deps before callback on store props

- .changeset/2797-dialog-auto-focus-on-hide.md
- examples/select-menu-default-open-click/index.tsx
- examples/select-menu-default-open-click/style.css
- examples/select-menu-default-open-click/test.ts
- packages/ariakit-react-core/src/dialog/dialog.tsx
- packages/ariakit-react-core/src/utils/store.tsx
> Fix regression on Dialog "focus on hide" timing

- .changeset/2820-dialog-disclosure-aria-haspopup.md
- packages/ariakit-react-core/src/dialog/dialog-disclosure.ts
> Add missing `aria-haspopup` attribute to `DialogDisclosure`

- package-lock.json
- package.json
> Revert "Update dependency next to v13.5.1"

- .changeset/2869-fuzzy-seals-happen.md
- packages/ariakit-react-core/src/utils/store.tsx
Fixes https://github.com/ariakit/ariakit/issues/2868
> Fix safeFlushSync uncaught error

- package-lock.json
- package.json
> Revert "Update dependency next to v13.5.4"

- .changeset/2949-fuzzy-books-reflect.md
- examples/select-form/index.tsx
- examples/select-form/style.css
- examples/select-form/test.ts
- packages/ariakit-react-core/src/select/select.tsx
Fixes #1989
Fixes #2491
Fixes #2661
> Ensure Select has selected option when rendering the native select

- .changeset/3088-fix-selection-range.md
- examples/combobox-input-email/index.tsx
- examples/combobox-input-email/style.css
- examples/combobox-input-email/test.ts
- packages/ariakit-core/src/utils/dom.ts
- packages/ariakit-react-core/src/combobox/combobox.ts
fix #3086
Details here: https://github.com/ariakit/ariakit/issues/3086#issuecomment-1824887516
> Fix error when execute setSelectionRange on unsupported input types

- examples/collection-no-register-item/index.tsx
- examples/collection-no-register-item/style.css
- examples/collection-no-register-item/test.ts
Part of #939
-  Collection with `shouldRegisterItem` set to `false`
> Add `collection-no-register-item` example

- examples/composite/index.tsx
- examples/composite/style.css
- examples/composite/test.ts
Part of #939 
-  Default Composite example
---
Please tell me if I should cover more behaviors on tests.
> Add `composite` example

- examples/collection-get-item/index.tsx
- examples/collection-get-item/style.css
- examples/collection-get-item/test.ts
Part of #939
- Collection with `getItem`
> Add `collection-get-item` example

- .changeset/3241-collection-store-sort.md
- packages/ariakit-core/src/collection/collection-store.ts
> Try to sort CollectionItem elements less often

- packages/ariakit-react-core/src/disclosure/disclosure-store.ts
> Update useDisclosureStore example

- .changeset/3256-combobox-auto-select-focus.md
- examples/combobox-auto-select-focus/index.tsx
- examples/combobox-auto-select-focus/style.css
- examples/combobox-auto-select-focus/test.ts
- packages/ariakit-react-core/src/composite/composite.tsx
As for the comment below, after testing the examples related to the use of `Composite`, everything appears to be functioning as intended. Please let me know if there's something I'm missing.
https://github.com/ariakit/ariakit/blob/e783dc9166b2a6b68a49051a1db6536b76a18585/packages/ariakit-react-core/src/composite/composite.tsx#L186-L189
Closes #3203
> Fix Combobox calling onFocus on every key pressed

- .changeset/3258-hovercard-shadow-dom.md
- examples/hovercard-shadow-dom/index.tsx
- examples/hovercard-shadow-dom/test-browser.ts
- package-lock.json
- package.json
- packages/ariakit-react-core/src/hovercard/hovercard.tsx
> Fix Hovercard when using shadow DOM

- .changeset/3295-collection-perf.md
- examples/dialog-framer-motion/test.ts
- examples/menu-framer-motion/test.ts
- examples/tooltip-framer-motion/test.ts
- packages/ariakit-core/src/collection/collection-store.ts
- packages/ariakit-react-core/src/select/select.tsx
- vitest.config.ts
> Improve collection performance with multiple items

- .changeset/3332-focusable-focus-onmouseup.md
- examples/dialog-menu/test-mobile.ts
- examples/tooltip-label/test-mobile.ts
- packages/ariakit-react-core/src/focusable/focusable.ts
> Revert change in focus behavior on Safari

- .changeset/3506-portal-extra-span.md
- examples/disclosure-animated/test-chrome-firefox.ts
- examples/menu/test.ts
- examples/tab-panel-animated/test-chrome-firefox.ts
- packages/ariakit-react-core/src/portal/portal.tsx
- website/components/header-ariakit-plus.tsx
> Stop rendering an extra span when not using portal

- .changeset/3560-tab-nested-1.md
- .changeset/3560-tab-nested-2.md
- examples/tab-nested/index.tsx
- examples/tab-nested/style.css
- examples/tab-nested/test.ts
- packages/ariakit-core/src/tab/tab-store.ts
- packages/ariakit-react-core/src/tab/tab-store.ts
- packages/ariakit-react-core/src/tab/tab.tsx
> Fix nested tabs

- .changeset/3591-combobox-auto-focus-on-hide-1.md
- .changeset/3591-combobox-auto-focus-on-hide-2.md
- examples/combobox/test-mobile.ts
- packages/ariakit-core/src/combobox/combobox-store.ts
- packages/ariakit-react-core/src/combobox/combobox-popover.tsx
- packages/ariakit-react-core/src/dialog/dialog.tsx
> Fix autoFocusOnHide behavior on Combobox

- .changeset/3595-combobox-show-min-length.md
- packages/ariakit-react-core/package.json
- packages/ariakit-react-core/src/combobox/combobox.tsx
> Add `showMinLength` prop to `Combobox`

- .changeset/3599-composite-item-input.md
- packages/ariakit-react-core/src/composite/composite-input.ts
- packages/ariakit-react-core/src/composite/composite-item.tsx
- packages/ariakit-react-core/src/toolbar/toolbar-input.ts
> Add support for CompositeItem as textbox

- .changeset/4140-cjs-build-use-client.md
- scripts/build/build.js
> Fix CJS build on Next.js

- .changeset/4148-dialog-viewport-height.md
- examples/dialog-combobox-command-menu/style.css
- examples/dialog/style.css
- guide/200-styling/readme.md
- packages/ariakit-react-core/src/dialog/dialog.tsx
> Add `--dialog-viewport-height` CSS variable

- .changeset/4182-composite-focus-shift.md
- examples/composite-focus-shift/index.tsx
- examples/composite-focus-shift/test.ts
- packages/ariakit-core/src/composite/composite-store.ts
> Fix `focusShift` option on composite stores

- .changeset/4184-radio-unnecessary-on-change.md
- examples/radio-alert-on-change/index.tsx
- examples/radio-alert-on-change/test-browser.ts
- packages/ariakit-react-core/src/radio/radio.tsx
> Fix `Radio` calling `onChange` when the value is the same

- .changeset/4185-disclosure-content-animating.md
- examples/disclosure-content-animating/index.tsx
- examples/disclosure-content-animating/style.css
- examples/disclosure-content-animating/test.ts
- packages/ariakit-react-core/src/disclosure/disclosure-content.tsx
- vitest.config.ts
> Fix `animating` state on `DisclosureContent` enter animations

- .changeset/4244-items-rendered-items-leftover.md
- packages/ariakit-react-core/src/composite/composite.tsx
> Fix composite items → renderedItems leftover

- .changeset/4251-mighty-ads-flow.md
- examples/menu-nested/test-chrome.ts
- packages/ariakit-core/src/utils/events.ts
> Fix two submenus open at the same time

- .changeset/4252-form-store-typescript.md
- packages/ariakit-core/src/form/form-store.ts
> Fix type conflict on form store

- package-lock.json
- package.json
- packages/ariakit-solid-core/package.json
- packages/ariakit-solid-playground/.gitignore
- packages/ariakit-solid-playground/README.md
- packages/ariakit-solid-playground/index.html
- packages/ariakit-solid-playground/package.json
- packages/ariakit-solid-playground/src/App.css
- packages/ariakit-solid-playground/src/App.tsx
- packages/ariakit-solid-playground/src/index.tsx
- packages/ariakit-solid-playground/vite.config.ts
Parent: #4378
A playground to test stuff for now. Also:
- Sync exports in Ariakit Solid core.
- FIx lint-staged stylelint command argument issue.
> [Solid] Add playground

- packages/ariakit-solid-core/contributing.md
Parent: #4378
- Added initial contributing guide
> [Solid] Contributing guide

- packages/ariakit-solid-core/contributing.md
Parent: #4378
- Added ToC
- Added basic tutorial
- Added port principles
- Updated ref section (null now permitted)
- General cleanup
- Misc. fixes and improvements
> [Solid] Contributing docs improvements

- package-lock.json
- packages/ariakit-solid-core/package.json
- packages/ariakit-solid-core/src/as/as.tsx
- packages/ariakit-solid-core/src/focus-trap/focus-trap-region.tsx
- packages/ariakit-solid-core/src/focus-trap/focus-trap.tsx
- packages/ariakit-solid-core/src/group/group-label-context.tsx
- packages/ariakit-solid-core/src/group/group-label.tsx
- packages/ariakit-solid-core/src/group/group.tsx
- packages/ariakit-solid-core/src/heading/heading-level.tsx
- packages/ariakit-solid-core/src/heading/heading.tsx
- packages/ariakit-solid-core/src/separator/separator.tsx
- packages/ariakit-solid-core/src/utils/__tests__/props-test.tsx
- packages/ariakit-solid-core/src/utils/misc.ts
- packages/ariakit-solid-core/src/utils/props.ts
- packages/ariakit-solid-core/src/utils/system.tsx
- packages/ariakit-solid-core/src/visually-hidden/visually-hidden.tsx
- vitest.config.ts
> [Solid] Props utilities

- packages/ariakit-solid-core/src/heading/heading-level.tsx
- packages/ariakit-solid-core/src/utils/__props.ts
- packages/ariakit-solid-core/src/utils/__tests__/props-test.solid.tsx
> [Solid] Fix max call stack size error caused by props system

- examples/command-enter-disabled/index.solid.tsx
- examples/command-space-disabled/index.solid.tsx
- examples/command/index.solid.tsx
- packages/ariakit-solid-core/package.json
- packages/ariakit-solid-core/src/command/command.tsx
- packages/ariakit-solid-core/src/focusable/focusable.tsx
- packages/ariakit-solid-core/src/utils/__port.ts
- packages/ariakit-solid-core/src/utils/__props.ts
- packages/ariakit-solid/package.json
- packages/ariakit-solid/src/command.ts
- packages/ariakit-solid/src/index.ts
Parent: #4378
Command has been implemented, plus a few minor tweaks here and there.
> [Solid - Command] Initial implementation

- examples/button-as-div/index.solid.tsx
- examples/button-as-link/index.solid.tsx
- examples/button/index.solid.tsx
- examples/group/index.solid.tsx
- examples/role-unit/test.ts
- packages/ariakit-solid-core/package.json
- packages/ariakit-solid-core/src/button/button.tsx
- packages/ariakit-solid-core/src/command/command.tsx
- packages/ariakit-solid-core/src/focusable/focusable.tsx
- packages/ariakit-solid/package.json
- packages/ariakit-solid/src/button.ts
- packages/ariakit-solid/src/index.ts
Parent: #4378
Implemented along with examples/tests, including some unblocked by this.
> [Solid - Button] Initial implementation

- packages/ariakit-core/readme.md
- packages/ariakit-react-core/readme.md
- packages/ariakit-react/readme.md
- packages/ariakit-solid-core/readme.md
- packages/ariakit-solid/readme.md
- packages/ariakit-test/readme.md
I also changed the links from the sad, pathetic husk of what used to be called "twitter" to The Good Place (bsky). Happy to revert if you prefer!
> Add myself (Dani) to core team <3

- contributing.md
- examples/combobox-links/index.react.tsx
- examples/dialog-menu/index.react.tsx
- examples/hovercard-disclosure/index.react.tsx
- examples/hovercard-disclosure/test.ts
- examples/hovercard-shadow-dom/index.react.tsx
- examples/hovercard-shadow-dom/test-browser.ts
- examples/hovercard/index.react.tsx
- examples/hovercard/test-chrome-firefox.ts
- examples/hovercard/test.ts
- packages/ariakit-react/readme.md
- packages/ariakit-solid/readme.md
- website/components/footer.tsx
> Add Discord links and replace Twitter stuff with Bluesky

- .changeset/4537-core-form-valid.md
- examples/form-valid/index.react.tsx
- examples/form-valid/style.css
- examples/form-valid/test.ts
- packages/ariakit-core/src/form/form-store.ts
> Fix valid state on Form

- .github/workflows/app.yml
- .github/workflows/commit-or-pr/action.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/ignore-stale-commits.yml
- .github/workflows/main.yml
- .github/workflows/og-images.yml
- .github/workflows/plus.yml
- .github/workflows/pr.yml
- .github/workflows/react-next.yml
- .github/workflows/release.yml
- .github/workflows/screenshots.yml
This pull request introduces several improvements and security enhancements to the GitHub Actions workflows. The main changes focus on tightening permissions, improving credential handling, standardizing concurrency groups, and making environment variable usage more robust. These updates help ensure workflows are more secure, maintainable, and reliable.
**Security & Permissions**
* Added explicit `permissions: contents: read` to most workflows (`main.yml`, `app.yml`, `plus.yml`, `pr.yml`, `react-next.yml`) and `contents: write` to release jobs, ensuring least privilege for workflow runs. [[1]](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R8-R10) [[2]](diffhunk://#diff-d119feda77103cd5ff3e0dc8d14de750a9de942a0eb277e9b967fd6c33f9b402R8-R10) …
> Fix workflows
