.babelrc
package.json
rollup.config.js
src/utils/isSVGElement.js
yarn.lock

Before PR:
> Destination: dist/cjs/reas.js
> Bundle size: 180.92 KB, Gzipped size: 40.12 KB
After PR:
> Destination: dist/cjs/reas.js
> Bundle size: 64.93 KB, Gzipped size: 14.2 KB
That's 65% reduction 😉 Ofc those lodash deps will have to be bundled too, but at least they should deduplicate between packages, which is not possible if you bundle them into your source code.

Do not bundle cherry-picked lodash functions for cjs & es targets

---

rollup.config.js

This shouldn't affect you, but it's always better to be future-proof.

Fixed external regexp issue for empty external arrays

---

src/components/Hidden/__tests__/withHidden-test.js
src/components/Hidden/withHiddenState.js
src/components/Popover/__tests__/withPopover-test.js
src/components/Step/__tests__/withStep-test.js
src/components/Step/withStepState.js
src/components/Tabs/__tests__/withTabs-test.js

Instead of using `withState` and `withHandlers` from `recompose`, we are now using `withStateHandlers` so we can have updated state and props.
Even though I can't reproduce on tests some issues I encountered by using it on a real world app, I think it will be enough to solve those problems.
Reference: https://github.com/acdlite/recompose/issues/610

Refactor on state enhancers

---

src/components/Perpendicular/Perpendicular.js
src/components/Popover/PopoverArrow.js
src/components/Tooltip/TooltipArrow.js
website/src/components/PropTypesTable.js
website/src/utils/findSectionPropTypes.js

Fix #109
I also changed `findSectionPropTypes` to display `defaultValues` from the parent component to the base component (e.g. https://deploy-preview-149--reakit.netlify.com/components/arrow shows `angle=0`, while https://deploy-preview-149--reakit.netlify.com/components/popover/popoverarrow shows `angle=180`)

Use angle instead of reverse prop on Perpendicular

---

website/src/images/404.svg
website/src/pages/NotFound.js
website/src/pages/Sections.js

Ref #137 
It adds a 404 page to website if not match any section:
Notes:
1. I added `404.svg` to a new folder called `images` because I did not know where to put it :sweat_smile: 
2. Feel free to change `404.svg`, I'm not a designer, but I tried to give my best.
3. I did not put any text or call to action, if you think it's cool to have, suggest here.

Add 404 page to website

---

src/components/Overlay/Overlay.js
src/components/Overlay/Overlay.md
src/components/Portal/Portal.js
src/components/Portal/Portal.md
src/components/Portal/index.js
src/components/Sidebar/Sidebar.md
src/components/index.js

This PR introduces a `Portal` component (abstracted from `Overlay`) so it will be easier to create other components with this feature.
It also makes it possible to use `Overlay` and `Sidebar` without being portals (actually, they won't be portals by default), so we can use them within another wrappers.
* `Overlay` and `Sidebar` no longer use React portals by default. Now it should be combined with `Portal` component in order to achieve the same behavior.
Before:
```jsx
<Overlay />
<Sidebar />
```
After:
```jsx
<Overlay as={Portal} />
<Sidebar as={Portal} />
```

Portal component

---

src/components/Overlay/Overlay.js

Not checking if the `wrapper` state for the `Overlay` component is mounted before removing it when it unmounts causes in some edge cases this warning:
`TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
`
It's weird but seems like React call `componentWillUnMount` even when the component didn't have the chance to be mounted.

Fix dom warning when wrapper for Overlay component haven't mounted yet

---

packages/reakit/src/Popover/Popover.js
packages/website/src/components/HeroGitHubButton.js

Added props to enable/disable the shift and flip modifiers of popper.js.

feat: Add `shift` and `flip` props to `Popover`

---

packages/reakit/src/__tests__/__snapshots__/as-test.js.snap
packages/reakit/src/as.tsx

Closes #208
This PR not only removes duplicated styles, but also decreases the number of components generated by not creating another wrapper around the enhanced component.
The whole problem was that `Styled(Base.as(div))` was injecting duplicated (and unnecessary) class names into the enhanced component:
cc @lomocc

fix: Dedupe classNames with identical styles

---

packages/reakit/src/_utils/getComponentName.ts
packages/reakit/src/_utils/types.ts

Closes #245
It was breaking some components. Since those properties weren't picked by `pickCSSProps` they wouldn't be rendered anyway.

fix(typescript): Stop using csstype for CSS properties

---

packages/reakit/src/Card/Card.ts
packages/reakit/src/Group/Group.js
packages/reakit/src/Popover/Popover.js
packages/reakit/src/Toolbar/ToolbarFocusable.js
packages/reakit/src/_utils/__tests__/getSelector-test.ts
packages/reakit/src/_utils/getSelector.ts
packages/reakit/test.tsx

TypeScript wasn't recognizing this prop because of the `// @ts-ignore` on component selector:
```jsx
<Card gutter={8} />
```

fix(typescript): Use `getSelector` when interpolating styled components

---

.travis.yml
packages/reakit/src/Hidden/HiddenContainer.tsx
packages/reakit/src/Hidden/__tests__/HiddenContainer-test.ts
packages/reakit/src/Step/StepContainer.tsx
packages/reakit/src/Step/__tests__/StepContainer-test.tsx

Instead of exporting them separately as `hiddenContainerState`, `hiddenContainerActions` etc., they will be attached to `HiddenContainer`:
```jsx
import { Hidden } from "reakit";
const { show } = Hidde.Container.actions;
```
Besides fixing a bug on the final bundle (for some reason, `rollup`'s `experimentalCodeSplitting` isn't working properly with the current master's approach), it makes the exports more concise.

feat: Attach `initialState`, `selectors` and `actions` to containers

---

packages/reakit/src/Flex/Flex.ts

Reported by @jpdesigndev on https://github.com/reakit/reakit/issues/229#issuecomment-427239512
It turns out that `wrap` is an actual HTML prop. We can't have conflicting props like this, so I'm removing it (which is a breaking change, so I'm targeting `next` branch).
The css prop should be used instead:
```jsx
<Flex flexWrap="wrap" />
```

fix: Remove buggy `flexWrap` props on `Flex` component

---

packages/reakit/src/Box/Box.tsx

This fixes a bug where refs weren't being applied to `Box` that had its `use` prop set to a component.
More specifically, this was the issue I personally was having:
```jsx
<Button use={Overlay.Hide} elementRef={this.initialFocusRef}>Close</Button>
```
It seemed that the ref wasn't being properly attached in this case, however, if I removed the `use` prop altogether, it worked.

Fixed refs for Box

---

packages/reakit/src/Popover/Popover.tsx

fix: Do not compute Popover's style when its parent has `display="none"`

---

packages/reakit/scripts/makeProxies.js

This fixes the issue where the "types" key in proxy packages were pointing to @diegohaz local machine. See #316.
I'm not too sure if we need to reference the `src/` folder though? Hence why I got rid of `getTSPath`... Just exposing the module's respective `ts/` folder should be enough? Let me know if I'm wrong. :)

Fix "types" key for proxy packages

---

README.md
docs/get-started.md
packages/reakit/README.md

As mentioned in #338, installing `@types/styled-components` is required to prevent TypeScript compile errors in certain scenarios.
Adds instruction to install `@types/styled-components` for TypeScript projects.
No

Add instructions for TypeScript

---

packages/reakit-system-palette/src/__tests__/index-test.tsx
packages/reakit-system-palette/src/palette.ts
packages/website/src/components/Provider.tsx

As pointed on #354 when you run a contrast ratio test it with `#007BFF` on primary color it gets a ratio below 4.5.
I just changed the primary dark color to `#006DFF` which gets a contrast ratio of 4.53. =D
I tried another values, but i think that changing the color values to more distinct values can cause some trouble on projects that are already using the default colors.
Closes #354

Changing Pallet primary dark from #005AFF to #006DFF due to constrat

---

packages/reakit-playground/src/PlaygroundPreview.tsx

The components were only unmounted when the `useEffect` was rerun or threw an error.
This meant that unmount would not trigger when the hook itself was destroyed.
This ensures that the component is always unmounted when the effect is updated, by unmounting in the cleanup function.
See: https://github.com/reakit/reakit/issues/351#issuecomment-492960923

[playground] Unmount React components correctly

---

packages/reakit/src/Tabbable/Tabbable.ts

fix: Fix `Checkbox` toggling twice on space bar key on Firefox

---

packages/reakit/src/Dialog/README.md
packages/reakit/src/Hidden/Hidden.ts
packages/reakit/src/Hidden/HiddenState.ts
packages/reakit/src/Hidden/README.md
packages/reakit/src/Hidden/__tests__/HiddenState-test.ts
packages/reakit/src/Menu/README.md
packages/reakit/src/Popover/README.md
packages/reakit/src/Tab/README.md
packages/reakit/src/Tooltip/README.md
packages/website/package.json
packages/website/src/components/Header.tsx
packages/website/src/templates/Docs.tsx
yarn.lock

This PR adds an `unstable_animated` option to `useHiddenState` and its derivatives. The goal is to support animations via CSS transitions and `react-spring`.
```jsx
import { useHiddenState, Hidden } from "reakit";
import styled from "styled-components";
const AnimatedHidden = styled(Hidden)`
opacity: 1;
transition: opacity 1500ms;
&.hidden {
opacity: 0;
}
`;
function App() {
const hidden = useHiddenState({ unstable_animated: true }); 
return <Hidden {...hidden} />;
}
```
- `unstable_animated` should be passed to `useHiddenState` instead of `Hidden`.
**Before:**
```jsx
const hidden = useHiddenState();
<Hidden {...hidden} unstable_animated />
```
**After:**
```jsx
const hidden = useHiddenState({ unstable_animated: true });
<Hidden {...hidden} />
```

feat: Add `unstable_animated` option to `useHiddenState` and its derivatives

---

packages/reakit-system-bootstrap/src/Dialog.ts
packages/reakit-system-bootstrap/src/Tooltip.ts
packages/reakit/src/Dialog/Dialog.tsx
packages/reakit/src/Dialog/DialogBackdrop.ts
packages/reakit/src/Dialog/__tests__/Dialog-test.tsx
packages/reakit/src/Dialog/__tests__/DialogBackdrop-test.tsx
packages/reakit/src/Menu/__tests__/Menu-test.tsx
packages/reakit/src/Popover/__tests__/Popover-test.tsx
packages/reakit/src/Popover/__tests__/PopoverBackdrop-test.tsx
packages/reakit/src/Tooltip/Tooltip.tsx
packages/reakit/src/Tooltip/__tests__/Tooltip-test.tsx

Closes #366
- Removed extra styles from `Dialog` and `DialogBackdrop` and all their derivative components. Also removed default `z-index` from `Tooltip`. These styles have been moved to the `reakit-system-bootstrap` package. If you're not using this system package, you should apply the styles manually.
**Before:**
```jsx
<DialogBackdrop />
<Dialog />
<Popover />
<Menu />
<Tooltip />
```
**After:**
```jsx
<DialogBackdrop
style={{
position: "fixed",
top: 0,
right: 0,
bottom: 0,
left: 0,
zIndex: 998
}}
/>
<Dialog style={{ zIndex: 999 }} />
<Popover style={{ zIndex: 999 }} />
<Menu style={{ zIndex: 999 }} />
<Tooltip style={{ zIndex: 999 }} />
```

feat: Remove z-index and extra styles from `Dialog` and `DialogBackdrop`

---

packages/website/gatsby-node.js
packages/website/src/components/DocsBackNext.tsx
packages/website/src/templates/Docs.tsx
packages/website/src/utils/getAdjacentPaths.ts

Explain the motivation for making this change and try to link to an open issue for more information.
Tackles in `Previous/next links on documentation for better navigation` in #351
No
- Added `nextPagePath` & `prevPagePath` to the context of each page in  `gatsby-node.js`
- Added a helper function `getAdjacentPaths.ts` in an attempt to keep `gatsby-node.js` a little tidier  
- Added a component for the links `DocsBackNext.tsx` & used it in `Docs.tsx`

Add previous/next links on documentation for better navigation

---

packages/reakit/src/Menu/README.md
packages/reakit/src/Radio/README.md
packages/reakit/src/Radio/__tests__/RadioState-test.ts
packages/reakit/src/Rover/README.md
packages/reakit/src/Rover/Rover.ts
packages/reakit/src/Rover/RoverState.ts
packages/reakit/src/Rover/__tests__/RoverState-test.ts
packages/reakit/src/Rover/__tests__/index-test.tsx
packages/reakit/src/Tab/README.md
packages/reakit/src/Tab/__tests__/TabState-test.ts
packages/reakit/src/Toolbar/README.md
packages/reakit/src/Toolbar/__tests__/ToolbarState-test.ts

Behavior before this change:
- Call `rover.first()` (focuses the first `Rover`)
- Move focus elsewhere
- Call `rover.first()` again (focus isn't returned to `Rover`)
This happens because `Rover` is only focused when there's a change on the current selec
ted rover (that is, a change on `rover.currentId`). Since it keeps being the `currentId` when we move focus elsewhere, it doesn't receive focus back when we try to re-select it.
This may be considered a bug as the behavior of `rover.first()` and other move methods
will be inconsistent.
With this change, the behavior is corrected:
- Call `rover.first()` (focuses the first `Rover`)
- Move focus elsewhere
- Call `rover.first()` (focuses the first `Rover`)
To do so, we simply increment a `unstable_moves` state and check if `Rover` is focused …

fix: Always focus `Rover` when calling `rover.{move|first|last}()`

---

packages/reakit/src/Checkbox/README.md
packages/reakit/src/Dialog/README.md
packages/reakit/src/Form/README.md
packages/reakit/src/Hidden/README.md
packages/reakit/src/Menu/README.md
packages/reakit/src/Popover/README.md
packages/reakit/src/Radio/README.md
packages/reakit/src/Rover/README.md
packages/reakit/src/Separator/README.md
packages/reakit/src/Tab/README.md
packages/reakit/src/Toolbar/README.md
packages/reakit/src/Tooltip/README.md
packages/website/src/components/List.ts
packages/website/src/components/Summary.tsx
packages/website/src/templates/Docs.tsx
scripts/build/utils.js

This puts props returned by state hooks (e.g. `useDialogState`) into hidden sections in the documentation. The goal is to improve the readability of the props documentation by hiding props that will usually be spread directly from the state hook to the component.

feat(website): Hide state hook props from docs

---

packages/reakit-utils/src/hasFocusWithin.ts
packages/reakit-utils/src/index.ts
packages/reakit/src/Menu/Menu.tsx
packages/reakit/src/Menu/__utils/useShortcuts.ts
packages/reakit/src/Rover/Rover.ts
packages/reakit/src/Rover/__tests__/index-test.tsx
packages/reakit/src/Tabbable/Tabbable.ts
packages/reakit/src/Tabbable/__tests__/Tabbable-test.tsx

This PR updates `Tabbable` and `Rover` components to support nested interactive components.
It also fixes some issues around Portals bubbling events to `Tabbable` and `Rover` (reference: https://github.com/facebook/react/issues/11387#issuecomment-524113945)
Look at tests for usage examples.
Closes #376

feat: Support nested `Tabbable` and `Rover` components

---

packages/reakit-playground/src/__deps/reakit.ts
packages/reakit/src/Form/README.md
packages/reakit/src/Menu/MenuArrow.ts
packages/reakit/src/Menu/README.md
packages/reakit/src/Menu/__tests__/MenuArrow-test.tsx
packages/reakit/src/Menu/index.ts
scripts/build/utils.js

Usage:
```jsx
import {
useMenuState,
Menu,
MenuArrow,
MenuItem,
MenuDisclosure,
MenuSeparator
} from "reakit/Menu";
function Example() {
const menu = useMenuState({ unstable_gutter: 14 });
return (
<>
<MenuDisclosure {...menu}>Preferences</MenuDisclosure>
<Menu {...menu} aria-label="Preferences">
<MenuArrow {...menu} />
<MenuItem {...menu}>Settings</MenuItem>
<MenuItem {...menu} disabled>
Extensions
</MenuItem>
<MenuSeparator {...menu} />
<MenuItem {...menu}>Keyboard shortcuts</MenuItem>
</Menu>
</>
);
}
```

feat: Add new `MenuArrow` component

---

packages/reakit/src/Hidden/Hidden.ts
packages/reakit/src/Hidden/HiddenDisclosure.ts
packages/reakit/src/Hidden/HiddenState.ts
packages/reakit/src/Hidden/README.md
packages/reakit/src/Hidden/__tests__/HiddenDisclosure-test.tsx
packages/reakit/src/Hidden/__tests__/index-test.tsx
packages/reakit/src/Hidden/__utils/useSetIsMounted.ts
packages/reakit/src/Hidden/__utils/useWarningIfMultiple.ts

Each `Hidden` component should have its own `useHiddenState`. This is also true for derivative modules like [Dialog](https://reakit.io/docs/dialog/), [Popover](https://reakit.io/docs/popover/), [Menu](https://reakit.io/docs/menu/), [Tooltip](https://reakit.io/docs/tooltip/) etc.
If you want to have only one `HiddenDisclosure` element controling multiple `Hidden` components, you can use [render props](https://reakit.io/docs/composition/#render-props) to apply the same state to different `HiddenDisclosure`s that will result in a single element.
```jsx
import { useHiddenState, Hidden, HiddenDisclosure } from "reakit/Hidden";
function Example() {
const hidden1 = useHiddenState();
const hidden2 = useHiddenState();
return (
<>
<HiddenDisclosure {...hidden1}>
{props => (
<HiddenDisclosure …
```

feat: Add support for `HiddenDisclosure` to control multiple `Hidden` components

---

packages/reakit-utils/src/tabbable.ts
packages/reakit/src/Dialog/__tests__/index-test.tsx

If `tabIndex={0}` is passed to the `Dialog` component, it should be included in the tab stops.
Before this change, it would be ignored if the dialog had focusable children already.

fix: Fix `Dialog` with `tabIndex={0}` not being included in the tab order

---

.eslintrc.js
packages/reakit-utils/src/tabbable.ts
packages/reakit/src/Dialog/__tests__/index-test.tsx
packages/reakit/src/Dialog/__utils/useDisableHoverOutside.ts
packages/reakit/src/Dialog/__utils/useFocusOnHide.ts
packages/reakit/src/Dialog/__utils/useFocusOnShow.ts

This is a fix for a very weird behavior when in certain environments, initial focus isn't set in the Dialog when it opens. I couldn't reproduce it o tests unfortunately, but enforcing focus with `requestAnimationFrame` does work.
I've also made it support manual initial focus using `React.useEffect` and `autoFocus` prop (when the dialog contents are mounted/unmounted from the DOM). See tests for more details.
No.

fix: Fix `Dialog` initial focus

---

packages/reakit/src/Popover/PopoverState.ts
packages/reakit/src/Popover/__tests__/Popover-test.tsx
packages/reakit/src/Tooltip/README.md
packages/reakit/src/Tooltip/Tooltip.tsx
packages/reakit/src/Tooltip/__tests__/Tooltip-test.tsx

This PR adds an `unstable_portal` prop to `Tooltip` so we have the option to render tooltips without `Portal`. A use case was raised by @lxcid on [Spectrum](https://spectrum.chat/reakit/general/i-was-wondering-if-can-hide-portal-of-tooltip-when-conditionally-rendered~4e05ffe1-93e8-4c72-8c85-eccb1c3f2ff1).
No

feat: Add experimental `unstable_portal` prop to `Tooltip`

---

packages/reakit/src/Menu/MenuState.ts
packages/reakit/src/Menu/README.md
packages/reakit/src/Popover/PopoverState.ts
packages/reakit/src/Popover/README.md
packages/reakit/src/Tooltip/README.md

It removes the `unstable_` prefix from the `gutter` option on `usePopoverState` and its derivatives (`useTooltipState`, `useMenuState`).
No! But it removes the `unstable_gutter` option.

feat: Add `gutter` option to `usePopoverState`

---

packages/reakit-playground/src/__deps/reakit-utils.ts
packages/reakit-utils/.gitignore
packages/reakit-utils/src/closest.ts
packages/reakit-utils/src/index.ts
packages/reakit/src/Dialog/__utils/useFocusTrap.ts
packages/reakit/src/Dialog/__utils/usePortalRef.ts
packages/reakit/src/Menu/__utils/useShortcuts.ts
packages/website/package.json

Closes #360
This PR replaces `Element.prototype.closest` and `Element.prototype.remove` by their [ponyfilled](https://github.com/sindresorhus/ponyfill) versions. These methods aren't automatically polyfilled by Babel on apps. So, with this, Reakit should work with IE11 by simply using Babel (production build).
No

fix: Replace IE11 incompatible DOM features

---

packages/reakit-system/src/createHook.ts

First off, thanks for this awesome project. Reading through the codebase has been a delight so far. This PR is something small I picked up while reading through the code.
The PR aims to improve performance by decreasing the space complexity (memory usage) of the `createHook` method. Instead of creating a new array for each iteration of the `reduce` method, it simply pushes to the new accumulator array. This is a *minor* improvement, but seeing that almost all components are using this method, it could have a negative performance impact on a large number of components and `composedHooks`.
There are no breaking changes for this change and all test are still passing locally.

perf: improve space complexity for `createHook` method

---

packages/reakit/src/Dialog/Dialog.tsx
packages/reakit/src/Dialog/__tests__/Dialog-test.tsx
packages/reakit/src/Dialog/__utils/useEventListenerOutside.ts
packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts
packages/reakit/src/Dialog/__utils/usePortal.tsx
packages/reakit/src/Menu/__tests__/Menu-test.tsx
packages/reakit/src/Popover/__tests__/Popover-test.tsx
packages/reakit/src/Portal/Portal.tsx
packages/reakit/src/Portal/README.md

VoiceOver requires nested modals to be children of their parent modals. In our current implementation, they're siblings. This PR changes this so nested dialogs will be appended as children to the parent dialog instead of the portal.

fix: Fix nested `Dialog`s not working with VoiceOver

---

docs/ACCESSIBILITY.md

No breaking changes. Small grammar fix for accessibility docs.

docs: grammar fix for accessibility docs

---

packages/reakit-playground/src/__deps/reakit-utils.ts
packages/reakit-utils/.gitignore
packages/reakit-utils/src/useIsomorphicEffect.ts
packages/reakit/src/Dialog/__utils/useDisclosuresRef.ts
packages/reakit/src/Hidden/HiddenState.ts
packages/reakit/src/Popover/PopoverState.ts
packages/website/src/hooks/useScrolled.ts
packages/website/src/hooks/useViewportWidthGreaterThan.ts

As mentioned in #438 the currently using Reakit triggers a lot of React warning messages when used with server side rendering. Using `useEffect` when window is undefined resolves this behaviour.
Fixes #438

Add a `useIsomorphicEffect` hook to allow proper SSR rendering

---

packages/reakit/src/Popover/PopoverState.ts

As discussed in #462 only exposes the `unsafe_update()` method in this version.
By the way, in the current project I'm working on I've wrapped the Popover state to automatically update whenever the content of the popover change. This might also be a good solution? I'm not really sure what the whole philosophy of reakit is, if this should be included or if this is something that should be left up to the user.
```ts
useIsomorphicEffect(() => {
const observer = new ResizeObserver(() => {
if (popperRef.current) popperRef.current.update();
});
observer.observe(elementRef.current);
return () => observer.disconnect();
}, []);
```

Expose a `unstable_update()` call to update the popover positioning

---

packages/reakit/src/Menu/Menu.tsx
packages/reakit/src/Menu/__tests__/Menu-test.tsx
packages/reakit/src/Rover/Rover.ts
packages/reakit/src/Rover/__tests__/Rover-test.tsx

Should a component break when not all required props are provided? 
Other components like `Dialog` do not break when you don't spread its state-props.

Make `Menu` run without menu state props

---

docs/TROUBLESHOOTING.md
packages/website/src/data/docs.yml

Closes #384
- Adds troubleshooting session
- Adds a topic about ramdonly generated IDs and tests

Add troubleshooting session on docs

---

packages/reakit/src/Menu/MenuBarState.ts
packages/reakit/src/Menu/MenuItemCheckbox.ts
packages/reakit/src/Menu/MenuItemRadio.ts
packages/reakit/src/Menu/__tests__/MenuItemCheckbox-test.tsx
packages/reakit/src/Menu/__tests__/MenuItemRadio-test.tsx
packages/reakit/src/Menu/__tests__/index-test.tsx

This fixes a regression introduced in #463 where both `PopoverState` and `MenuState` got conflicting property `unstable_update`. I'm updating the name of the function on `MenuState`, but I think both names should be revisited later.
Closes #472
No breaking changes, but `menuState.unstable_update` has been replaced by `menuState.unstable_setValues`.

fix: Fix `MenuItemCheckbox` and `MenuItemRadio` not working

---

packages/reakit/src/Button/Button.ts
packages/reakit/src/Button/__tests__/Button-test.tsx

Custom elements are receiving the `type` attribute, which is not valid.
About the role, see note on WAI-ARIA 1.1 [link(role)](https://w3.org/TR/wai-aria-1.1/#link):
> "If pressing the link triggers an action but does not change browser focus or page location, authors are advised to consider using the button role instead of the link role."

fix: Stop adding `type="button"` on `Button` by default

---

packages/reakit/src/Menu/README.md
packages/reakit/src/Radio/README.md
packages/reakit/src/Rover/README.md
packages/reakit/src/Rover/Rover.ts
packages/reakit/src/Rover/RoverState.ts
packages/reakit/src/Rover/__tests__/RoverState-test.ts
packages/reakit/src/Rover/__tests__/index-test.tsx
packages/reakit/src/Tab/README.md
packages/reakit/src/Toolbar/README.md

When `Rover` received focus it was incrementing the `unstable_moves` prop, triggering another effect that would try to focus it again.
No

fix: Fix `Rover` trying to focus itself again when it receives focus

---

packages/reakit-utils/src/__tests__/warning-test.ts
packages/reakit-utils/src/warning.ts
packages/reakit/src/Checkbox/__utils/useIndeterminateState.ts
packages/reakit/src/Dialog/Dialog.tsx
packages/reakit/src/Dialog/__utils/useEventListenerOutside.ts
packages/reakit/src/Dialog/__utils/useFocusOnHide.ts
packages/reakit/src/Dialog/__utils/useFocusOnShow.ts
packages/reakit/src/Dialog/__utils/useFocusTrap.ts
packages/reakit/src/Hidden/HiddenState.ts
packages/reakit/src/Hidden/__utils/useWarningIfMultiple.ts
packages/reakit/src/Menu/Menu.tsx
packages/reakit/src/Menu/MenuBar.tsx
packages/reakit/src/Popover/Popover.ts
packages/reakit/src/Radio/RadioGroup.tsx
packages/reakit/src/Rover/Rover.ts
packages/reakit/src/Rover/RoverState.ts
packages/reakit/src/Tab/TabList.tsx
packages/reakit/src/Toolbar/Toolbar.tsx
packages/reakit/src/utils/Provider.ts

Enable third-party callsites to use `warning()` for their specific warnings without tagging them as `"[reakit]"`.
Closes #475
Yes
- `warning()`'s label argument has been turned into a regular message. Existing callsites should update the first message after the condition to include a label, if required.
**Before:**
```js
warning(!!condition, 'Button', 'warning message');
```
**After:**
```js
warning(!!condition, '[reakit/Button]', 'warning message');
```

Remove hardcoded "[reakit]" string from warning()

---

packages/reakit/src/Tabbable/Tabbable.ts
packages/reakit/src/Tabbable/__tests__/Tabbable-test.tsx

Closes #480
By the way, something like `eslint-plugin-react-hooks` would catch this.

fix: Fix `Tabbable` preventing click after enabling it

---

packages/reakit-system/src/__tests__/createHook-test.tsx
packages/reakit-system/src/createHook.ts
packages/reakit/src/Form/FormCheckbox.ts
packages/reakit/src/Form/FormInput.ts
packages/reakit/src/Menu/Menu.tsx
packages/reakit/src/Menu/MenuDisclosure.ts

`useCompose` kind of breaks the encapsulated composition approach of `createHook`. This PR replaces it by `useComposeOptions`, which will be called after `useProps` and return options instead of calling the composed hooks directly.
Also, it changes the order that composed `useOptions` are called. Before, they were being called after the current hook `useProps`, which didn't compose so well as it wouldn't have access to options modified by the composed hooks. Now composed `useOptions` are called right after the current hook `useOptions`, but before `useProps`. The current hook `useProps` now will receive the `options` after they get proccessed by all composed hooks. It's necessary so the new `Id` module proposed on #492 will be able to pass a default `id` or `baseId` option to other hooks …

feat(reakit-system): Replace `useCompose` by `useComposeOptions` on `createHook`

---

packages/reakit/src/Id/IdState.ts
packages/reakit/src/Provider.tsx
packages/reakit/src/Radio/__tests__/RadioState-test.ts
packages/reakit/src/Rover/Rover.ts
packages/reakit/src/Rover/RoverState.ts
packages/reakit/src/Rover/__tests__/Rover-test.tsx
packages/reakit/src/Rover/__tests__/RoverState-test.ts
packages/reakit/src/Tab/Tab.ts
packages/reakit/src/Tab/TabList.tsx
packages/reakit/src/Tab/TabPanel.ts
packages/reakit/src/Tab/TabState.ts
packages/reakit/src/Tab/__tests__/Tab-test.tsx
packages/reakit/src/Tab/__tests__/TabPanel-test.tsx
packages/reakit/src/Tab/__tests__/TabState-test.ts
packages/reakit/src/Tab/__tests__/index-test.tsx
packages/reakit/src/Toolbar/Toolbar.tsx
packages/reakit/src/Toolbar/__tests__/ToolbarState-test.ts
packages/reakit/src/Toolbar/__tests__/index-test.tsx

This PR is a follow-up to #492.
- Compose `useIdState` into `useRoverState` and, therefore, its derivative hooks, such as `useTabState`, `useToolbarState` and `useRadioState`.
- Compose `Id` into `Rover` and its derivative components.
- Compose `IdGroup` into `TabList` and `Toolbar`
Now it's possible to pass a `baseId` option to `useRoverState`, `useTabState`, `useToolbarState` and `useRadioState` so their rover items will have a predictable `id` attribute.
Since they compose now from `IdGroup`, it's also possible to pass an `id` prop to `TabList` and `Toolbar` to achieve the same result:
```jsx
// we can now pass `baseId` to the state hook or `id` to the `IdGroup` (`Toolbar`) component
const toolbar = useToolbarState({ baseId: "toolbar" });
<Toolbar {...toolbar} id="toolbar"> …
```

feat: Add `baseId` option to `useRoverState` and derivative hooks

---

packages/reakit/src/Checkbox/Checkbox.ts
packages/reakit/src/Checkbox/__tests__/index-test.tsx

Closes #465
If `checked` or `value` is passed to the second argument of the `useCheckbox` hook, they will be used instead of `options.checked` and `options.value` (passed to the first argument).
No

fix: Stop ignoring `checked` and `value` props passed as html props to `useCheckbox`

---

packages/reakit/src/Checkbox/Checkbox.ts
packages/reakit/src/Form/FormCheckbox.ts
packages/reakit/src/Form/FormGroup.ts
packages/reakit/src/Form/FormInput.ts
packages/reakit/src/Form/FormPushButton.ts
packages/reakit/src/Form/FormRadio.ts
packages/reakit/src/Form/FormRadioGroup.tsx
packages/reakit/src/Form/FormRemoveButton.ts
packages/reakit/src/Form/FormSubmitButton.ts
packages/reakit/src/Form/__tests__/index-test.tsx
packages/reakit/src/Id/Id.tsx
packages/reakit/src/Id/IdGroup.tsx
packages/reakit/src/Radio/Radio.ts
packages/reakit/src/Radio/RadioGroup.tsx
packages/reakit/src/Radio/__tests__/index-test.tsx
packages/reakit/src/Tabbable/Tabbable.ts

This PR standardizes the precedence when `options` and `htmlProps` have conflicts. This is only an issue when using props hooks instead of components.
No

fix: Standardize precedence when `options` and `htmlProps` conflict

---

packages/reakit/src/Form/FormState.ts
packages/reakit/src/Form/__tests__/index-test.tsx

Closes #502
The problem was that the item was being `delete`d in the initial values as well. This PR copies the array using `Array.prototype.slice()`, which keeps empty items as empty.
No

fix: Fix `form.reset()` not reverting array fields to initial state

---

packages/reakit-system-palette/jest.config.js
packages/reakit/jest.config.js
packages/reakit/src/Dialog/__utils/usePreventBodyScroll.ts

This PR closes #505
- No
After applying the fix found by @diegohaz on the `body-scroll-lock` issues, it should fix the rollup build

importing directly body-scroll-lock from es modules to fix rollup build

---

packages/reakit/src/Portal/Portal.tsx

Should fix below issue, when PortalContext is undefined. See the commit message for good description.
Closes https://github.com/reakit/reakit/issues/513
Unfortunately, not sure.
I couldn't figure out when `document` would ever be undefined. But in that case, the outcome is different now.

Add default PortalContext if it's undefined

---

packages/reakit/src/Menu/README.md
packages/reakit/src/Popover/PopoverState.ts
packages/reakit/src/Popover/README.md
packages/reakit/src/Tooltip/README.md

Closes #516 
No
- - -
Aside - It didn't look like there were tests for other modifier flags like `unstable_shift`. If you have a way you prefer this to be tested, lmk and I'll update the PR.

Add support for the popper.js `inner` modifier to Popover

---

packages/reakit/src/Dialog/__tests__/DialogBackdrop-test.tsx
packages/reakit/src/Id/Id.tsx
packages/reakit/src/Id/IdGroup.tsx
packages/reakit/src/Rover/Rover.ts
packages/reakit/src/Tab/Tab.ts
packages/reakit/src/Tab/__tests__/Tab-test.tsx
packages/reakit/src/Tab/__tests__/TabPanel-test.tsx
packages/reakit/src/Tab/__utils.ts

Closes #518
This PR fixes regressions introduced by #492 and #494, which made some components ignore the `id` prop.
@namjul Do you know if there are other components with the same issue?
No

fix: Fix components not rendering `id` prop

---

packages/reakit/src/Menu/README.md
packages/reakit/src/Popover/PopoverState.ts
packages/reakit/src/Popover/README.md
packages/reakit/src/Tooltip/README.md

Adds support for two-axis offset positioning via an `unstable_offset` prop. Turns existing single-axis offset positioning (`gutter`) into a special case of `unstable_offset`.
Closes #511 
No

Support popper.js' `offset` modifier with `unstable_offset`

---

packages/reakit/src/Tabbable/Tabbable.ts
packages/reakit/src/Tabbable/__tests__/Tabbable-test.tsx

When clicking on a non-native `Tabbable` component (e.g. `<Tabbable as="div" />`) by pressing <kbd>Enter</kbd> or <kbd>Space</kbd> in conjunction with the meta key (e.g. <kbd>⌘</kbd>), the button should not be activated.
No

fix: Prevent clicks when pressing Enter/Space with meta key on non-native `Tabbable`

---

packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts

fix: Fix parent `Dialog` closing when clicking on nested `DialogBackdrop`

---

docs/BASIC_CONCEPTS.md
docs/COMPOSITION.md
packages/reakit-system/src/__tests__/createComponent-test.tsx
packages/reakit-system/src/createComponent.ts
packages/reakit/src/Box/Box.ts
packages/reakit/src/Dialog/Dialog.tsx
packages/reakit/src/Dialog/DialogBackdrop.tsx
packages/reakit/src/Dialog/__utils/useNestedDialogs.tsx
packages/reakit/src/Form/FormRadioGroup.tsx
packages/reakit/src/Form/__tests__/index-test.tsx
packages/reakit/src/Menu/MenuBar.tsx
packages/reakit/src/Menu/__utils/MenuContext.tsx
packages/reakit/src/Tooltip/Tooltip.tsx

This PR marks `unstable_wrap` as stable and renames it to `wrapElement`.
This:
```jsx
const { unstable_wrap, ...props } = useDialog();
const element = <div {...props} />;
return unstable_wrap ? unstable_wrap(element) : element;
```
Becomes this:
```jsx
const { wrapElement, ...props } = useDialog();
const element = <div {...props} />;
return wrapElement ? wrapElement(element) : element;
```
No (it was an unstable feature).

feat: Replace `unstable_wrap` by `wrapElement`

---

packages/reakit-playground/src/__deps/reakit.ts
packages/reakit-system-bootstrap/src/Menu.tsx
packages/reakit/src/Menu/MenuButton.ts
packages/reakit/src/Menu/MenuDisclosure.ts
packages/reakit/src/Menu/README.md
packages/reakit/src/Menu/__tests__/MenuButton-test.tsx
packages/reakit/src/Menu/__tests__/MenuDisclosure-test.tsx
packages/reakit/src/Menu/__tests__/index-test.tsx
packages/reakit/src/Menu/index.ts
packages/reakit/src/Popover/README.md
packages/reakit/src/Toolbar/README.md
packages/website/src/components/HomePlayground.tsx
stories/index.stories.tsx

This PR follows the same line of thought as #541. There's a dedicated section on the WAI-ARIA Authoring Practices website named `Menu Button`: https://www.w3.org/TR/wai-aria-practices/#menubutton
This is probably our last renaming before v1.0 gets out of beta.
No, only deprecation warnings.

feat: Add `MenuButton` and deprecate `MenuDisclosure`

---

packages/reakit-system-bootstrap/src/Menu.tsx
packages/reakit/package.json
packages/reakit/src/Menu/README.md
packages/reakit/src/Menu/__tests__/MenuArrow-test.tsx
packages/reakit/src/Popover/PopoverArrow.tsx
packages/reakit/src/Popover/PopoverState.ts
packages/reakit/src/Popover/README.md
packages/reakit/src/Popover/__tests__/PopoverArrow-test.tsx
packages/reakit/src/Tooltip/README.md
packages/reakit/src/Tooltip/TooltipState.ts
packages/reakit/src/Tooltip/__tests__/TooltipArrow-test.tsx
yarn.lock

Upgrade popper.js to v2
- The internal `popper.js` dependency has been upgraded to `v2`. The stable `Popover` API remains the same. But, while this change has been tested with the most common use cases, there may be some edge cases where `Popover` and `Menu` (which uses `Popover` underneath) may behave differently.

feat: Upgrade to popper.js v2

---

packages/reakit/src/Rover/Rover.ts
packages/reakit/src/Rover/RoverState.ts
packages/reakit/src/Rover/__tests__/RoverState-test.ts

Closes #488
`MenuItemRadio` composes from `MenuItem` and `Radio`. Both of them compose from `Rover`, which means that they will try to `register` and `unregister` an item twice. There's no problem with that. The result is "noop" for the second call. But this warning is indicating that a problem is happening and making users think that they need to fix something, which is not true.
No

fix: Remove confusing `rover.unregister()` warning

---

packages/reakit/src/Checkbox/__tests__/Checkbox-test.tsx
packages/reakit/src/Form/__tests__/FormSubmitButton-test.tsx
packages/reakit/src/Tabbable/Tabbable.ts
packages/reakit/src/Tabbable/__tests__/Tabbable-test.tsx
packages/reakit/src/Tooltip/__tests__/index-test.tsx

Closes #471
While this issue should be fixed in the React side for all elements (https://github.com/facebook/react/issues/17229), this PR guarantees that Reakit's `Tabbable` will behave consistently with a `Tooltip`, even when used with non-native interactive elements (e.g. `<Tabbable as="div">`).
No

fix: Fix inconsistent `Tooltip` behavior on disabled `Tabbable`

---

packages/reakit/src/Button/__tests__/Button-test.tsx
packages/reakit/src/Tabbable/Tabbable.ts
packages/reakit/src/Tabbable/__tests__/Tabbable-test.tsx

When there are two `useTabbable` being composed into one component and the resulting element is not a native interactive element (`button`, `input` etc.), pressing <kbd>Enter</kbd> or `<kbd>Space</kbd>` on it will result in a double click.
No

fix: Fix `Tabbable` dispatching `click` twice when composed by another `Tabbable`

---

docs/BASIC_CONCEPTS.md
docs/COMPOSITION.md
docs/MANAGING_STATE.md
packages/reakit-playground/src/__deps/reakit.ts
packages/reakit/src/Dialog/Dialog.tsx
packages/reakit/src/Dialog/DialogBackdrop.tsx
packages/reakit/src/Dialog/README.md
packages/reakit/src/Disclosure/DisclosureContent.ts
packages/reakit/src/Disclosure/DisclosureState.ts
packages/reakit/src/Disclosure/README.md
packages/reakit/src/Disclosure/__tests__/DisclosureContent-test.tsx
packages/reakit/src/Disclosure/__tests__/index-test.tsx
packages/reakit/src/Disclosure/__utils/useSetIsMounted.ts
packages/reakit/src/Disclosure/__utils/useWarningIfMultiple.ts
packages/reakit/src/Disclosure/index.ts
packages/reakit/src/Hidden/Hidden.ts
packages/reakit/src/Tab/README.md
packages/reakit/src/Tab/TabPanel.ts
packages/reakit/src/Tooltip/README.md
packages/reakit/src/Tooltip/Tooltip.tsx

This PR renames `DisclosureRegion` to `DisclosureContent` and removes the `role="region"` attribute from it. Since this is a generic component, we shouldn't make assumptions on which role it will have. This was also introducing an accessibility issue, since a `role="region"` element requires `aria-label` or `aria-labelledby`.
- `DisclosureRegion` has been renamed to `DisclosureContent`.

feat: Add `DisclosureContent` component

---

packages/reakit-playground/src/__deps/reakit-utils.ts
packages/reakit-utils/.gitignore
packages/reakit-utils/README.md
packages/reakit-utils/src/closest.ts
packages/reakit-utils/src/index.ts
packages/reakit-utils/src/matches.ts
packages/reakit-utils/src/tabbable.ts

This build is broken for IE11 because it's not using the IE11 polyfill.
Issue: https://github.com/reakit/reakit/issues/556
No, it only fix a bug by using the Element.matches polyfill everywhere.

fix: Add ie11 polyfill for Element.matches

---

packages/reakit/src/Button/README.md

Addresses part of #351  
@diegohaz - I'm running into an error when I try to put an example of styled-components in the Button readme. Also want to make sure that this is the direction you want to go. Let me know if there's anything you'd like done differently. I mostly just copied the examples from the Styles doc and made them more explicit as far as what styles were used. 
TypeError: Cannot read property 'length' of undefined
areHookInputsEqual
node_modules/react-dom/cjs/react-dom.development.js:16201
16198 | {
16199 |   // Don't bother comparing lengths in prod because these arrays should be
16200 |   // passed inline.
> 16201 |   if (nextDeps.length !== prevDeps.length) {
16202 |     warning$1(false, 'The final argument passed to %s changed size between renders. The ' + 'order and …

add style examples to Button readme

---

packages/reakit/src/Disclosure/README.md

Very tiny typo
Nope :) 
- `compoennt` has been replaced by `component`.

Update Disclosure README.md

---

docs/COMPOSITION.md
packages/reakit-system/src/createHook.ts
packages/reakit/src/Button/README.md
packages/reakit/src/Checkbox/README.md
packages/reakit/src/Clickable/README.md
packages/reakit/src/Composite/CompositeState.ts
packages/reakit/src/Composite/README.md
packages/reakit/src/Dialog/DialogBackdrop.tsx
packages/reakit/src/Dialog/__tests__/DialogBackdrop-test.tsx
packages/reakit/src/Popover/__tests__/PopoverBackdrop-test.tsx
packages/reakit/src/Rover/README.md
packages/reakit/src/Tab/README.md
packages/reakit/src/Tab/Tab.ts
packages/reakit/src/Tab/TabList.tsx
packages/reakit/src/Tab/TabPanel.ts
packages/reakit/src/Tab/TabState.ts
packages/reakit/src/Tab/__tests__/Tab-test.tsx
packages/reakit/src/Tab/__tests__/TabList-test.tsx
packages/reakit/src/Tab/__tests__/TabPanel-test.tsx
packages/reakit/src/Tab/__tests__/TabState-test.ts
packages/reakit/src/Tab/__tests__/index-test.tsx
packages/reakit/src/Tab/__utils.ts
packages/website/src/components/HomePlayground.tsx

This PR is kind of a redesign on the `Tab` API. It's been refactored so it composes from the `Composite` module instead of `Rover`.
The API became a lot simpler:
```jsx
const tab = useTabState();
<TabList {...tab} aria-label="My tabs">
<Tab {...tab}>Tab 1</Tab>
<Tab {...tab}>Tab 2</Tab>
<Tab {...tab}>Tab 3</Tab>
</TabList>
<TabPanel {...tab}>Tab 1</TabPanel>
<TabPanel {...tab}>Tab 2</TabPanel>
<TabPanel {...tab}>Tab 3</TabPanel>
```
Changes on this PR:
- No need to pass `selectedId` to `useTabState` to select the first tab. The first tab is now selected by default as this is the most common use case. That's a breaking change (more info below).
- When unmounting the current selected tab, instead of selecting the next or the previous tab, it selects now the last selected tab. It mimics the …

feat: Select the first `Tab` by default and don't require `stopId` prop

---

packages/reakit/src/Dialog/Dialog.tsx
packages/reakit/src/Dialog/__utils/useFocusOnHide.ts
packages/reakit/src/Dialog/__utils/useFocusOnShow.ts
packages/reakit/src/Dialog/__utils/useFocusTrap.ts
packages/reakit/src/Dialog/__utils/useNestedDialogs.tsx

Historical context:
1. Last year we found a bug where nested modals weren't working when using VoiceOver/Safari because it didn't support multiple elements with the `aria-modal="true"` attribute. So I created #457 to fix the issue by putting nested modals inside their parent ones in the DOM.
2. Months later we found that rendering modals in that way was creating a lot of styling issues where the parent styles would interfere in the child modal styles. Since the same problem was happening on the WAI-ARIA site, I concluded that it was a bug on VoiceOver/Safari and reverted that change on #533.
Now, this PR fixes the same problem by removing the `aria-modal` attribute from the parent modal when the nested modal is visible.
No

fix: Fix nested modals when using VoiceOver/Safari

---

packages/reakit/src/Menu/README.md
packages/reakit/src/Radio/README.md
packages/reakit/src/Radio/Radio.ts
packages/reakit/src/Radio/RadioState.ts
packages/reakit/src/Radio/__tests__/index-test.tsx

Closes #607 . Fixes issue with non string values being allowed as radio values, additionally fixes issue with falsey values (such as an empty string) not being able to be checked.
Added a test (based on the test by @tom-sherman) that tests that empty strings can be checked.
Technically there is no breaking change as radio values should have always been only strings, however it is possible that end users were providing non string values so this change could break that behaviour.

Fix for #607 - Falsey values as radio values and type updates.

---

packages/reakit/src/Dialog/__utils/useFocusOnHide.ts
packages/reakit/src/Dialog/__utils/useFocusOnShow.ts
packages/reakit/src/Menu/__tests__/index-test.tsx

When using VoiceOver, opening or closing an animated `Dialog` (and its derivative components) doesn't move focus correctly. This PR changes the code so that it waits for the animation to complete before moving focus.
**Before:**
**After:**
No

fix: Fix animated `Dialog` not being correctly focused with VoiceOver

---

packages/reakit/src/Dialog/__utils/useEventListenerOutside.ts
packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts

Bail out of dispatching a listener in `useEventListenerOutside` when the document doesn't have focus

---

packages/reakit/src/Dialog/Dialog.tsx
packages/reakit/src/Menu/Menu.tsx
packages/reakit/src/Menu/MenuButton.ts
packages/reakit/src/Menu/MenuItem.tsx
packages/reakit/src/Menu/__utils/MenuContext.tsx
packages/reakit/src/__tests__/index-test.tsx

fix: Fix `Menu` -> `Dialog` -> `Menu` behaving as a sub menu

---

packages/reakit/src/Tooltip/TooltipState.ts
packages/reakit/src/Tooltip/__tests__/index-test.tsx

This adds an experimental `unstable_timeout` number option to `useTooltipState` so it'll wait some time before showing the tooltip.
```jsx
import { useTooltipState, Tooltip, TooltipReference } from "reakit";
function Example() {
const tooltip = useTooltipState({ unstable_timeout: 250 });
return (
<>
<TooltipReference {...tooltip}>Reference</TooltipReference>
<Tooltip {...tooltip}>Tooltip</Tooltip>
</>
);
}
```
This also makes sure that there will be always only one tooltip open.
No

feat: Add experimental `unstable_timeout` option to `useTooltipState`

---

packages/reakit/src/Clickable/Clickable.ts

Closes #368
The `Clickable` component wasn't considering inputs, so the space key up was triggering another click on the checkbox.
I can't write a test for this because it checks for `event.isTrusted`, and, on tests, this is always `false`.
No

fix: Fix `Checkbox` activating twice on space key on Firefox

---

packages/reakit/src/Tooltip/README.md
packages/reakit/src/Tooltip/Tooltip.tsx
packages/reakit/src/Tooltip/TooltipState.ts
packages/reakit/src/Tooltip/__examples__/TooltipWithToolbar/__tests__/index-test.tsx
packages/reakit/src/Tooltip/__globalState.ts

This implements a global event handler that hides all tooltips if <kbd>Escape</kbd> is pressed.
No. This is part of the WAI-ARIA recommendations for tooltips.

feat: Hide `Tooltip` when pressing `Escape`

---

packages/reakit/src/Button/__examples__/ButtonWithTootltip/__tests__/index-test.tsx
packages/reakit/src/Button/__examples__/ButtonWithTootltip/index.tsx

Add an example using a Button with Tooltip and VisuallyHidden.
It will increase the list of examples related to #626

examples: button with tooltip

---

packages/reakit/src/Dialog/Dialog.tsx
packages/reakit/src/Dialog/__tests__/index-test.tsx

Fixes #636
No, unless you were relying on passing undefined to remove the tabIndex DOM attribute.

Ensure undefined doesn't override default tabIndex in Dialog

---

packages/reakit-utils/src/useLiveRef.ts

This fixes the timing of live ref updates. Writing to refs during the render phase is considered a side-effect and the React team is thinking how to surface this "problem" to the users. 
It's somewhat hard to 
No

Update live ref in commit phase

---

.eslintrc.js
package.json
yarn.lock

Following [this suggestion](https://github.com/reakit/reakit/pull/646#discussion_r426742680).
This PR makes sure, for consistency, that `test()` is used in our tests files rather than `it()`. 
I understand all tests in this project use the `*-test.tsx` file name convention, hence the regex.

Ensure `test()` within tests rather than `it()`

---

packages/reakit/src/Toolbar/__examples__/ToolbarWithMenu/__tests__/index-test.tsx
packages/reakit/src/Toolbar/__examples__/ToolbarWithMenu/index.tsx

As part of the documentation effort ono #626 this PR adds examples for a [Toolbar with Menu](https://reakit.io/docs/toolbar/#toolbar-with-menu).
I tried to stay consistent with existing examples 💅🏻
I can remove the **emojis from the example** if needed, I think they add a bit of fun to it, however, I tend to over-use them 😄

Examples: Toolbar with Menu

---

packages/reakit/src/Toolbar/__examples__/ToolbarWithPopover/__tests__/index-test.tsx
packages/reakit/src/Toolbar/__examples__/ToolbarWithPopover/index.tsx

Add an example for a **toolbar with a popover** and test it, following the effort of #626 
I noticed the **popover arrow** is not centred within the disclosure and it's `border-bottom` being visible. I guess this is something we should fix? 💅🏻
When focusing on an element _two outlines appear_, the browser one and a smaller one wrapping the text, is this intended?

Examples: Toolbar with Popover

---

packages/reakit/src/Tabbable/Tabbable.ts

When changing focus between tabbable elements on Safari and Firefox on MacOS, the blur event on the previous active element was being fired after the focus event on the next active element.
This PR waits for the blur event to happen on the active element before focusing the next element.
No

fix: Fix blur/focus events order on `Tabbable` on Safari and Firefox on MacOS

---

packages/reakit/src/Checkbox/README.md

Following the effort on #351 this PR introduces a **"Styling"** section on [`<Checkbox />` ](https://reakit.io/docs/checkbox/) documentation.  ( in line with [what we have already for `<Button />`](https://reakit.io/docs/button/#styling) )
`<Checkbox />` is not part of [`reakit-system-bootstrap`](https://github.com/reakit/reakit/tree/master/packages/reakit-system-bootstrap/src), hence the custom styles instead.

Document <Checkbox /> styling

---

packages/website/src/components/CoreLayout.tsx
packages/website/src/components/Header.tsx

Following the effort of other successful _open source_ projects within the front-end community
( [React](https://reactjs.org/), [Redux](https://redux.js.org/), [Webpack](https://webpack.js.org/), [Styled Components](https://styled-components.com/), etc... ) this pull-request adds a **BLM banner** on top of the website.

feat(website): add BLM banner

---

packages/reakit/src/Tab/README.md

As @diegohaz suggested on [this Spectrum post](https://spectrum.chat/reakit/general/why-is-tabpanel-focusable-can-i-make-it-not-be~50f78c3e-530d-4884-8a41-dbb668ce84a1), I've added a couple of new `Tab` examples to the docs:
- **Detecting the selected tab** shows how to determine which `Tab` is selected and alter the rendering of the corresponding `TabPanel`.
- **Non-tabbable tab panels** shows how to make `TabPanel`s non-tabbable/non-focuasble.
I also added a few of sentences under the  **Default selected tab** example pointing out how `id`s need to be set explicitly in order to use `selectedId` in `useTabState`. That's also relevant to the first example I added and it was not obvious to me when I was trying to figure out how to use this component.

Add Tab examples: Detecting the selected tab, Non-tabbable tab panels

---

packages/reakit/src/Tabbable/Tabbable.ts

Here we go again! 😅
We can't move focus right away when Safari/Firefox on MacOS focus on the closest focusable parent element when you click on a button. Otherwise it's going to prevent drag events from happening.
Related: https://github.com/WordPress/gutenberg/issues/22730
No

fix: Fix `Tabbable` preventing drag events on mouse down on Safari

---

packages/reakit-playground/src/__deps/reakit-system-bootstrap.ts
packages/reakit-playground/src/__deps/reakit.ts
packages/reakit-system-bootstrap/.gitignore
packages/reakit-system-bootstrap/src/Form.ts
packages/reakit-system-bootstrap/src/Input.ts
packages/reakit-system-bootstrap/src/index.ts
packages/reakit/.gitignore
packages/reakit/src/Form/FormInput.ts
packages/reakit/src/Form/README.md
packages/reakit/src/Input/Input.ts
packages/reakit/src/Input/README.md
packages/reakit/src/Input/__tests__/Input-test.tsx
packages/reakit/src/Input/index.ts
packages/reakit/src/index.ts
packages/website/src/data/docs.yml

Closes #665
It doesn't introduce breaking changes in base package. One who used `useFormInputProps` hook still can continue to use it or migrate to use `useInputProps` instead.
It does introduce a small breaking change for `reakit-system-bootstrap` though. It doesn't export `useFormInputProps` hook anymore.

feat: introduce Input primitive as base for FormInput (#665)

---

packages/reakit/src/Composite/CompositeState.ts
packages/reakit/src/Composite/__examples__/DrillUpComposite/__tests__/index-test.tsx
packages/reakit/src/Composite/__examples__/DrillUpComposite/index.tsx

Closes #650
This is a very specific case where the state lives in a component, and you try to update it from another component that is not a descendant right after the former has been unmounted. This is only possible if you pass the state up to a component higher in the tree.
No

fix: Fix `Composite` state update on unmounted components

---

packages/reakit/src/Composite/__keys.ts
packages/reakit/src/Dialog/__keys.ts
packages/reakit/src/Disclosure/__keys.ts
packages/reakit/src/Form/__keys.ts
packages/reakit/src/Grid/__keys.ts
packages/reakit/src/Id/IdState.ts
packages/reakit/src/Id/__keys.ts
packages/reakit/src/Menu/__keys.ts
packages/reakit/src/Popover/__keys.ts
packages/reakit/src/Radio/__keys.ts
packages/reakit/src/Rover/__keys.ts
packages/reakit/src/Tab/__keys.ts
packages/reakit/src/Toolbar/__keys.ts
packages/reakit/src/Tooltip/__keys.ts

This PR marks the `id.unstable_setBaseId` method as stable.
No. But people relying on the unstable feature will have to update their code.

feat: Add stable `id.setBaseId` method

---

packages/reakit/src/Composite/CompositeState.ts
packages/reakit/src/Composite/__examples__/DynamicComposite/index.tsx
packages/reakit/src/Composite/__keys.ts
packages/reakit/src/Grid/__keys.ts
packages/reakit/src/Menu/__keys.ts
packages/reakit/src/Radio/__keys.ts
packages/reakit/src/Tab/__keys.ts
packages/reakit/src/Toolbar/__keys.ts

This PR marks the `composite.unstable_sort` method as stable.
No. But people relying on the unstable feature will have to update their code.

feat: Add stable `composite.sort` method

---

packages/reakit/src/Menu/README.md

Add the "dropdown" word to the description so this component can be found on the search tool.
No.

docs: Add "dropdown" keyword to the menu docs

---

packages/reakit/src/Composite/CompositeState.ts
packages/reakit/src/Composite/__examples__/DynamicComposite/__tests__/index-test.tsx
packages/reakit/src/Composite/__examples__/DynamicComposite/index.tsx
packages/reakit/src/Composite/__utils/useSortBasedOnDOMPosition.ts

This PR makes use of [`IntersectionObserver`](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver) (when it's available) to detect changes in the order of composite items in the DOM so it can automatically sort the array of items in the composite state.
See https://deploy-preview-696--reakit.netlify.app/storybook/?path=/story/composite--dynamic-composite
No.

feat: Automatically sort composite items based on DOM position

---

packages/reakit/src/Disclosure/DisclosureContent.ts

This PR introduces a delay to mount the children prop of the `DisclosureContent` component and its derivative components, such as `Dialog` and `Menu`, when they're initially rendered with the `visible` state set to `false`.
This means that the visible UI will be displayed on the screen in less time. And children will be mounted into the DOM in the next layout paint.
No.

perf: Improve mount performance of invisible `DisclosureContent` and derivative components

---

packages/reakit/src/Disclosure/DisclosureState.ts

Explain the motivation for making this change and try to link to an open issue for more information.
Example: Closes #698
No breaking changes, just an additional warning in dev environment
Super late night PR written in the GitHub editor. I'm sure that method for detecting env and copy for warning will need to be tweaked. I haven't tested it yet because it's late. Depending on the build process I'll see if I can make time tomorrow.

Dev warning if disclosure stopAnimation uncalled

---

packages/reakit/src/Radio/Radio.ts
packages/reakit/src/Radio/__tests__/index-test.tsx

Adds auto generated `id` to `name` prop when `isNativeRadio`
closes #702

fix(Radio) : Return `name` prop when Radio has `isNativeRadio` prop

---

.npmrc

I just got caught out by this on my work machine as it's setup with our private registry configured in the global config.

chore: Add registry to npmrc

---

packages/reakit/src/Dialog/__utils/useDisclosureRef.ts

Fixes issue where Firefox users were encountering a `element.focus is not a function` error.
Ref: https://github.com/bumbag/bumbag-ui/issues/33

Assert `focus` attribute exists on the target element

---

packages/reakit/src/Composite/Composite.ts
packages/reakit/src/Composite/__examples__/VirtualCompositeWithFocusBlur/__tests__/index-test.tsx
packages/reakit/src/Composite/__examples__/VirtualCompositeWithFocusBlur/index.tsx

While working on #711, I noticed that the order that `focus`/`blur` events were triggered on `Composite` elements (with `unstable_virtual` set to `true`) were incorrect when using a pointer to click.
This PR fixes it.
Failing test: https://github.com/reakit/reakit/runs/989811378#step:11:504
No

fix: Fix intermediate `focus`/`blur` event order in `Composite`

---

.github/workflows/react-next.yml

This _should_ show a button to allow you to manually trigger the workflow.
See https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

chore: Allow manual triggering of react-next pipeline

---

packages/reakit-playground/src/PlaygroundEditor.tsx
packages/reakit-playground/src/__deps/reakit-utils.ts
packages/reakit-utils/.gitignore
packages/reakit-utils/README.md
packages/reakit-utils/src/canUseDOM.ts
packages/reakit-utils/src/getNextActiveElementOnBlur.ts
packages/reakit-utils/src/index.ts
packages/reakit-utils/src/useIsomorphicEffect.ts
packages/reakit/src/Composite/Composite.ts
packages/reakit/src/Portal/Portal.tsx
packages/reakit/src/Tabbable/Tabbable.ts

Add a new utils called `canUseDOM` that uses the same SSR check that React does:
https://github.com/facebook/react/blob/1eb2b892dfffedfdb57039ef715fc7049f4d538a/packages/shared/ExecutionEnvironment.js
I had some issues with SSR with the current check (`typeof window === 'undefined'`), changing to this made it work. 
n/a
I didn't manage to create a standalone repo to reproduce the issue. I've tried to use Next but it didn't happen in its SSR, might be due to some Webpack config I have. 
Nope.

fix: Change SSR-check to test the same way React does

---

.github/workflows/ci.yml
scripts/build/check.js

From https://github.com/reakit/reakit/pull/717#pullrequestreview-470768441
I've added a quick script for checking if there are any modified files. Modified files indicate that `yarn build` was not run before pushing changes to exported modules.
I added a new module to reakit-utils and pushed the changes without running the build step, looks like it's working as intended: https://github.com/reakit/reakit/pull/718/checks?check_run_id=1005209400#step:12:6

chore: Check build files are checked in as part of CI

---

packages/reakit/src/Composite/CompositeState.ts
packages/reakit/src/Composite/__examples__/CompositeShift/__tests__/index-test.tsx

This PR fixes the `shift` option on `useCompositeState`. On `master`/`next`, using `PageDown` and `PageUp` wouldn't work correctly.

fix: Fix `Composite` with `shift` when using `PageUp`/`PageDown`

---

packages/reakit/src/Tooltip/README.md
packages/reakit/src/Tooltip/Tooltip.tsx

As per our conversation on Twitter ✨ 
https://twitter.com/mattrothenberg/status/1311086235922857985

docs: remove erroneous reference to modal Tooltip prop

---

packages/reakit/src/Rover/RoverState.ts

Refactored the useCallback(fn, []) to useAction same as how reakit has done in Composite.
BTW, We already have `useAction` function in composite https://github.com/reakit/reakit/blob/master/packages/reakit/src/Composite/CompositeState.ts#L601 maybe we can externalize it to reduce the duplicate code, do let me know if you want me to move that function into `reakit-utils` or somewhere else.

refactor(rover): useCallback to useAction

---

docs/STYLING.md

Hi @diegohaz here's the PR for doc update that includes the markdown for styling to include CSS modules.
I ran `yarn website` to test manually:

Adds a section on using css modules for styling

---

packages/reakit/src/Composite/README.md

I was looking for a `Grid` component for half an hour until I realised it was removed. Then reintroduced as an experimental feature. Still, I think we shouldn't advice people to use an experimental feature since it can't even be found in the docs.
`yarn website`
No

docs: Replace Grid with TabList to avoid confusion

---

packages/website/src/data/docs.yml

Expose `Grid` in the documentation. It's experimental but the documentation looks good to go. It was accessible through direct link anyway.
- `yarn website`
- Open website
- Make sure `Grid` is available in the documentation
No

Expose Grid in the documentation

---

packages/reakit-playground/src/__deps/reakit-utils.ts
packages/reakit-system/src/__tests__/state-createComponent-test.tsx
packages/reakit-system/src/createComponent.ts
packages/reakit-utils/.gitignore
packages/reakit-utils/README.md
packages/reakit-utils/src/__tests__/normalizePropsAreEqual-test.ts
packages/reakit-utils/src/__tests__/splitProps-test.ts
packages/reakit-utils/src/index.ts
packages/reakit-utils/src/normalizePropsAreEqual.ts
packages/reakit-utils/src/splitProps.ts
packages/reakit-utils/src/types.ts

This PR tries to implement this issue: https://github.com/reakit/reakit/issues/744
Allow the use of `state` prop instead of object spreading. 
Since all components are created with `createComponent`, this implementation modifies this function to allow either `state` object or `state` object spreading.
`createComponent` uses two functions that are related to the props: `splitProps` and `propsAreEqual`.
If `splitProps` finds a `state` **plain object** in the `props` then it returns the `state` object instead of using the `keys` to split the props. If the `props` doesn't have a `state` that is **plain object** then it split the props using the `keys`.
Since we are trying to move the `state` into the `state` object, `propsAreEqual` need to make sure it takes the `state` object into account. …

Add state prop with backward compatibility

---

packages/reakit/src/Checkbox/__examples__/Checkbox/__tests__/index-test.tsx
packages/reakit/src/Checkbox/__examples__/Checkbox/index.tsx
packages/reakit/src/Checkbox/__examples__/Checkbox/style.css

Adds a Storybook example for a checkbox component.
Unrelated to this PR, but would it make sense to add some base styles (a color palette, CSS reset) for the examples to use? Tailwind CSS could be nice as well (as mentioned before in https://github.com/reakit/reakit/pull/753). A downside of Tailwind is that you can't easily style attributes like `[aria-checked]`. You'll have to create a plugin for all those attributes or use `@apply` or `theme()` in CSS.

Examples: Checkbox

---

packages/reakit/src/Dialog/__examples__/DialogSidebar/__tests__/index-test.tsx
packages/reakit/src/Dialog/__examples__/DialogSidebar/index.tsx

An example of a sidebar menu using `<Dialog />`
From #626 discussion.

Examples: Dialog Sidebar

---

packages/reakit-test-utils/src/click.ts
packages/reakit-test-utils/src/fireEvent.ts
packages/reakit/src/Composite/Composite.ts
packages/reakit/src/Composite/CompositeItem.ts
packages/reakit/src/Composite/__examples__/CompositeVirtualAsProp/__tests__/index-test.tsx
packages/reakit/src/Composite/__utils/userFocus.ts
packages/reakit/src/Dialog/__examples__/DialogWithVirtualCompositeWithTooltip/__tests__/index-test.tsx
packages/reakit/src/Dialog/__utils/useFocusOnHide.ts
packages/reakit/src/Menu/MenuItem.tsx

Closes #755
This PR is an alternative to #755. Instead of turning `unstable_virtual` off on mobile, it disables focus forwarding when `element.focus()` is called, which is the function VoiceOver uses to focus on items.

fix: Fix Composite `unstable_virtual` option on mobile devices

---

packages/reakit/src/Composite/Composite.ts
packages/reakit/src/Composite/__tests__/index-test.tsx

This PR removes the warning that `Composite` shows when the developer doesn't pass any role prop or pass an invalid composite role prop to the `Composite` component.
```jsx
// Will not warn anymore
<Composite />
```
The reason is that there are valid use cases for omitting the role prop. For example, we could create multiple connected listbox elements to implement the ARIA 1.2 listbox group pattern for screen readers that still don't support it, like VoiceOver. This use case is better explained on https://github.com/WordPress/gutenberg/issues/24975#issuecomment-722481740.
With the Reakit Composite module, the implementation would be something like this, where the `listbox` role is not passed to the `Composite` component.
```jsx
const composite = useCompositeState();
<Composite …
```

fix: Stop warning when using invalid composite roles on `Composite`

---

packages/reakit/src/Radio/Radio.ts
packages/reakit/src/Radio/__tests__/index-test.tsx

Fixes https://github.com/reakit/reakit/issues/790
`change` event is fired for native radio inputs by the browser. Therefore we don't need to fire it when we click on a native radio.
Regression test included
No

fix: Native radio input firing onChange callback twice on click

---

packages/reakit/src/Dialog/__utils/useFocusOnHide.ts

To be error proof it could be better that the document.querySelector in useFocusOnHide have quote around the value in the selector.
For example with the current code, some id may go in error (number, special characters)
[MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector)
Some query selector example
https://codesandbox.io/s/morning-tree-xbo5g?file=/src/App.js
Nop

Fix missing quote querySelector in useFocusOnHide

---

packages/reakit-utils/README.md
packages/reakit-utils/src/__tests__/splitProps-test.ts
packages/reakit-utils/src/splitProps.ts
packages/reakit/src/Dialog/__examples__/ChatDialog/__tests__/index-test.tsx
packages/reakit/src/Dialog/__examples__/ChatDialog/index.tsx
packages/reakit/src/Dialog/__examples__/index.story.ts

Closes #798
See tests, [storybook](https://deploy-preview-799--reakit.netlify.app/storybook/?path=/story/dialog--chat-dialog) (try to close the chat dialog by clicking outside) and the generated [CodeSandbox](https://codesandbox.io/s/naughty-resonance-yb9l8).
No
---
cc @david-szabo97 Could you please have a look here when you have time? 😊

fix: Accept other option props together with the `state` prop

---

packages/reakit-system/src/__tests__/state-createComponent-test.tsx
packages/reakit-system/src/createComponent.ts

Closes #797
Check console on CodeSandbox: https://codesandbox.io/s/empty-resonance-43go3
Technically, yes. The following code would stop working:
```jsx
<Grid as={Composite} state={state} />
```
But I've never really seen that being used like that. `Grid` uses `Composite` internally already, so that doesn't make much sense.
And, since `state={state}` isn't documented yet, I think it's safe to change it. The only problem is that it would behave differently from `{...state}`. But I've temporarily removed support for this on `{...state}` as well and, still, all the tests were passing. So I would argue that this behavior is not really useful, but let's keep it as is for `{...state}` so as to prevent breaking edge cases.
However we …

fix: Stop passing the `state` prop to custom `as` components

---

packages/reakit-playground/src/__deps/reakit-utils.ts
packages/reakit-utils/.gitignore
packages/reakit-utils/README.md
packages/reakit-utils/src/dom.ts
packages/reakit-utils/src/index.ts
packages/reakit/src/Popover/PopoverState.ts
packages/reakit/src/Tabbable/Tabbable.ts

Closes #751
Updated the popover state to update the popper styles in the main phase so they're defined before the menu popover receives focus. I'm still not sure if this is the right solution nor the side effects it could have. I need to read Popper.js docs more carefully.
Follow the reproduction steps on #751 on https://deploy-preview-801--reakit.netlify.app/
No

fix: Fix `Menu` scroll jump

---

packages/reakit/src/Combobox/Combobox.ts
packages/reakit/src/Combobox/README.md

Before this commit we were trying to show the Popover as soon as the user click
on the Combobox. This resulted in badly positioned Popover in some cases like
non-static Combobox containers.
Now we check if the Combobox value length is bigger than the minValueLength
before trying to show the Popover.
fixes #808

fix(Combobox): Fix badly positioned popover on click + minValueLength

---

packages/reakit/src/Composite/CompositeItem.ts
packages/reakit/src/Grid/__tests__/GridCell-test.tsx
packages/reakit/src/Menu/__tests__/MenuItem-test.tsx
packages/reakit/src/Menu/__tests__/MenuItemCheckbox-test.tsx
packages/reakit/src/Menu/__tests__/MenuItemRadio-test.tsx
packages/reakit/src/Radio/__tests__/Radio-test.tsx
packages/reakit/src/Tab/__tests__/Tab-test.tsx
packages/reakit/src/Toolbar/__tests__/ToolbarItem-test.tsx

`CompositeItem` was checking for `props.items.length`, which is always `0` on the first render. This PR changes it so it checks for the existence of the items array instead in order to determine whether it should have tabindex -1 or not.
No

fix: Fix `CompositeItem` with `tabindex=0` on the first render

---

packages/reakit/src/Composite/CompositeItem.ts
packages/reakit/src/Grid/__tests__/GridCell-test.tsx
packages/reakit/src/Menu/__tests__/MenuItem-test.tsx
packages/reakit/src/Menu/__tests__/MenuItemCheckbox-test.tsx
packages/reakit/src/Menu/__tests__/MenuItemRadio-test.tsx
packages/reakit/src/Radio/__tests__/Radio-test.tsx
packages/reakit/src/Tab/__tests__/Tab-test.tsx
packages/reakit/src/Toolbar/__tests__/ToolbarItem-test.tsx

#817 ended up introducing some breaking changes. This PR reverts it.

fix: Revert `CompositeItem` tabIndex fix

---

packages/reakit/src/Menu/README.md

In the docs, change use of `items` to `menuItems` as `items` can be conflicting with the menu state props
Closes #839
I can also set up this PR to extend the abstracting example towards what I have in #839 which allows for the `Menu` component to be used as a menuItem for sub menus or that could be set up as a separate PR if desired.
No, just an update to the markdown for the Menu component

Update Menu Abstracting example

---

packages/reakit/src/Button/__examples__/ButtonWithTooltip/__tests__/index-test.tsx
packages/reakit/src/Menu/__examples__/SimpleMenu/index.tsx
packages/reakit/src/Popover/PopoverState.ts

Closes #819
Closes #820
Related to #820 but i only cherry-pick the layout-shift fix.
Wrap Menu inside Portal then first render will make the scroll jump to bottom.
```jsx
import { useMenuState, Menu, MenuItem, MenuButton } from "reakit/Menu";
import { Portal } from 'reakit/Portal'
function Example() {
const menu = useMenuState();
return (
<>
<MenuButton {...menu}>Preferences</MenuButton>
<Portal>
<Menu {...menu} tabIndex={0} aria-label="Preferences">
<MenuItem {...menu}>Settings</MenuItem>
<MenuItem {...menu}>Extensions</MenuItem>
<MenuItem {...menu}>Keyboard shortcuts</MenuItem>
</Menu>
</Portal>
</>
);
}
```
No

Fix: layout shift when first render popper

---

packages/reakit/src/Tabbable/Tabbable.ts

In React 17, React effects triggered by native focus/blur events run before the `onFocus`/`onBlur` events on React.
Here's the difference (click on "Test" and see the logs):
- [React 16](https://codesandbox.io/s/difference-between-dom-focus-and-react-focus-16-3blvl?file=/src/App.js)
- [React 17](https://codesandbox.io/s/difference-between-dom-focus-and-react-focus-17-r4z3l?file=/src/App.js)
Currently on master we are scheduling a React effect in response to a native `focusin` event:
https://github.com/reakit/reakit/blob/caa81b385c0e95689a13a729635374c60956b154/packages/reakit/src/Tabbable/Tabbable.ts#L84-L91
With the change on React 17, this may break some code that's relying on the `onFocus` React event on the `focusableAncestor` element, since the effect will now run before the React …

fix: Fix button focus on mouse down on Safari and React 17

---

packages/reakit/src/Composite/Composite.ts
packages/reakit/src/Composite/__examples__/VirtualCompositeWithFocusBlur/__tests__/index-test.tsx

If the user clicks on a `CompositeItem` element and then uses arrow keys to move to another item, the `blur` event is not fired on the first item.
This PR moves the logic of getting the `previousElementRef` to the `onFocus` event on the `Composite` component.
See added test.
No.

fix: Fix `CompositeItem` not emitting blur events when `unstable_virtual` is `true`

---

docs/STYLING.md

876 - updated styled-components doc to include forwardedAs prop

---

packages/reakit/src/Tab/README.md

Just fixes a minor docs type.
N/A
Nope

Fix a minor Tab docs typo

---

packages/reakit/src/Form/__utils/types.ts

Closes #900 
`reakit` when included in a project with `typescript` 4.4.2 would fail `tsc`. This PR updates the troubled typings.
#903

make tsc work in typescript 4.4.2

---

packages/reakit/src/Radio/RadioGroup.tsx

Just a small refactor allowing Reakit to export `useRadioGroup` hook, so that it can be consumed for composing.

fix: Add missing `useRadioGroup` export

---

packages/reakit/src/Menu/__utils/useShortcuts.ts

Had an issue when I use the Menu from `reakit/Menu` to open a modal (code base from my company).
When just after the click of an `MenuItem` (without any focus of elements on the opened modal) I press any key, the app crashes every time with this exception:
Breakpoints:
The property `items` is always `undefined`. So, the `.find` will crash. I've just added a default value for it to avoid this issue. I don't really know how this issue occurs because I can't reproduce it on my own.. but my company has this issue and we're struggling to deal with.
Don't hesitate to tell me if I forgot something.
Thanks! ;-)

fix: add default empty value for items prop

---

.github/workflows/ci.yml
packages/ariakit/src/button/__examples__/button-as-link/index.tsx
packages/ariakit/src/button/__examples__/button-as-link/style.css
packages/ariakit/src/button/__examples__/button-as-link/test.tsx

Hello @diegohaz 
I want to contribute to Ariakit, so i made this simple example. 
Example button as a link #939 

feat: add example 'button as link'

---

packages/ariakit/src/radio/__examples__/radio/index.tsx
packages/ariakit/src/radio/__examples__/radio/style.css
packages/ariakit/src/radio/__examples__/radio/test.tsx
packages/ariakit/src/radio/readme.md

Ariakit: Add radio example

---

packages/ariakit/src/heading/__examples__/heading/index.tsx
packages/ariakit/src/heading/__examples__/heading/style.css
packages/ariakit/src/heading/__examples__/heading/test.tsx
packages/ariakit/src/heading/readme.md

Hai @diegohaz , I want to contribute to this project.
This PR adds `heading` example for #939

chore: Add `Heading` example

---

packages/ariakit/src/tooltip/__examples__/tooltip-with-timeout/index.tsx
packages/ariakit/src/tooltip/__examples__/tooltip-with-timeout/style.css
packages/ariakit/src/tooltip/__examples__/tooltip-with-timeout/test.tsx

Adds tooltip with timeout example for #939

chore: Add `tooltip-with-timeout` example

---

package-lock.json
package.json
packages/ariakit/src/menu/__examples__/menu-item-checkbox/index.tsx
packages/ariakit/src/menu/__examples__/menu-item-checkbox/style.css
packages/ariakit/src/menu/__examples__/menu-item-checkbox/test.tsx
packages/ariakit/src/menu/readme.md
packages/website/pages/index.tsx

Adds a "Menu item checkbox" example https://github.com/reakit/reakit/issues/939.

chore: Add `menu-item-checkbox` example 

---

packages/ariakit/src/checkbox/__examples__/checkbox-controlled/index.tsx
packages/ariakit/src/checkbox/__examples__/checkbox-controlled/style.css
packages/ariakit/src/checkbox/__examples__/checkbox-controlled/test.tsx

Add `controlled checkbox` example #939
The default example is when the checkbox is uncontrolled. #949

chore: Add `checkbox-controlled` example

---

packages/ariakit-playground/src/playground-code.tsx
packages/ariakit-playground/src/playground-editor.tsx

Right now, we can't scroll the playground editor when it's expanded, but not focused (which in the code is translated into the `editable` local state).
This has been an annoying experience. So this PR fixes the behavior so the editor doesn't need to be focused anymore to be scrollable.
1. Open https://ariakit.org/examples/combobox
2. Expand the editor
3. Focus on something else
4. Try to scroll on the editor
And then repeat the same with this PR preview site (https://ariakit-git-fix-playground-editor-scrolling-ariakit.vercel.app/examples/combobox)

fix: Fix `PlaygroundEditor` preventing scroll when not focused

---

packages/ariakit/src/collection/__examples__/collection/index.tsx
packages/ariakit/src/collection/__examples__/collection/style.css
packages/ariakit/src/collection/__examples__/collection/test.tsx

Part of #939
Adds the default example for the `Collection` component and a simple test

chore: Add `collection` example

---

package-lock.json
package.json
packages/ariakit-playground/src/__examples__/playground-tabs/style.css
packages/ariakit-playground/src/__examples__/playground/style.css
packages/ariakit/src/button/__examples__/button-as-link/style.css
packages/ariakit/src/button/__examples__/button/style.css
packages/ariakit/src/combobox/__examples__/combobox/style.css
packages/ariakit/src/disclosure/__examples__/disclosure/style.css
packages/ariakit/src/form/__examples__/form/style.css
packages/ariakit/src/heading/__examples__/heading/style.css
packages/ariakit/src/hovercard/__examples__/hovercard/style.css
packages/ariakit/src/menu/__examples__/menu-item-checkbox/style.css
packages/ariakit/src/popover/__examples__/popover-responsive/style.css
packages/ariakit/src/popover/__examples__/popover/style.css
packages/ariakit/src/tab/__examples__/tab/style.css
packages/ariakit/src/tooltip/__examples__/tooltip/style.css
packages/website/components/markdown-page/index.tsx
packages/website/components/markdown-page/style.module.css
packages/website/components/playground/index.tsx
packages/website/components/playground/open-in-code-sandbox.tsx
packages/website/components/playground/playground-disclosure.tsx
packages/website/components/playground/playground-error.tsx
packages/website/components/popup/index.tsx
packages/website/components/tooltip-button/index.tsx
packages/website/pages/index.tsx
prettier.config.js

ref: https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

chore: Add prettier-plugin-tailwindcss

---

packages/ariakit/src/focus-trap/__examples__/focus-trap/index.tsx
packages/ariakit/src/focus-trap/__examples__/focus-trap/style.css
packages/ariakit/src/focus-trap/__examples__/focus-trap/test.tsx
packages/website/pages/index.tsx

This update adds a basic example for the `FocusTrap` component as part of this effort: https://github.com/reakit/reakit/issues/939
- Run `yarn dev`
- Visit http://localhost:3000/examples/focus-trap.
- Press `Tab`.
- Toggle Focus Trap will trap `Tab` focus.
Nope! Only adding an example.

chore: Add `focus-trap` example

---

packages/ariakit/src/checkbox/__examples__/checkbox-custom/index.tsx
packages/ariakit/src/checkbox/__examples__/checkbox-custom/style.css
packages/ariakit/src/checkbox/__examples__/checkbox-custom/test.tsx
packages/website/pages/index.tsx

This update adds a custom styled checkbox example for the Checkbox component:
Screenshots
How to test?
- `npm run dev`
- Visit http://localhost:3000/examples/checkbox-custom
Does this PR introduce breaking changes?
Nope, just an example

chore: Add `checkbox-custom` example 

---

packages/ariakit/src/popover/popover-arrow.tsx

This PR closes #1040. 
The way to test:
- Boot in Safari, Chrome & Firefox 
- Open the Popover
- Reduce the height of the window to force the pop over to appear above the button
Screenshots of that testing:
Safari:
Chrome: 
Firefox:

fix: Fix `PopoverArrow` placement on Safari

---

packages/ariakit/src/hovercard/__examples__/hovercard-disclosure/index.tsx
packages/ariakit/src/hovercard/__examples__/hovercard-disclosure/style.css
packages/ariakit/src/hovercard/__examples__/hovercard-disclosure/test.tsx
packages/ariakit/src/hovercard/__examples__/hovercard/test.tsx
packages/ariakit/src/hovercard/__utils/debug-polygon.ts
packages/ariakit/src/hovercard/__utils/polygon.ts
packages/ariakit/src/hovercard/hovercard-anchor.ts
packages/ariakit/src/hovercard/hovercard-disclosure.tsx
packages/ariakit/src/hovercard/hovercard-state.ts
packages/ariakit/src/hovercard/hovercard.tsx
packages/ariakit/src/menu/menu-button.ts
packages/ariakit/src/menu/menu.ts

This PR introduces a series of improvements on the `Hovercard` components:
- `showOnMouseMove` has been replaced by `showOnHover`.
- `HovercardDisclosure` now controls its own visibility by adding DOM event handlers to the other hovercard elements.
- `hideOnMouseLeave` has been replaced by `hideOnHoverOutside`.
- There's a new `disablePointerEventsOnApproach` prop on `Hovercard` that controls whether pointer/mouse events should be disabled when the mouse is moving towards the hovercard.
- Support for nested hovercards (required for nested submenus).

feat: Improve `Hovercard` API and behavior

---

jest.setup.js
package-lock.json
package.json

This change adds [`jest-fail-on-console`](https://github.com/ValentinH/jest-fail-on-console), a lib to prevent unexpected error logs.
`jest-fail-on-console` is particularly useful since jest doesn't automatically fail when an error log happens, and especially for large codebases, this can end up being a problem as it gets easier to introduce overloaded tests outputs.

chore: Add jest-fail-on-console lib

---

jest.config.js
packages/ariakit-utils/src/__tests__/array-test.ts
packages/ariakit-utils/src/__tests__/dom-test.ts

This week I started to dig into some more components and decided that learning most of the utils would help me more quickly understand the rest of the lib. While reading through them, I noticed the lack of unit tests around them. I figured this was a good way to learn how they work and practice writing tests.
With that I started on `array` and `dom` and covered most of them. I honestly don't know if this is super valuable to the lib. If not, no worries, it was a great way for me to practice and learn a ton more low level web APIs. If this work does seem valuable but this is too much to go through in one PR, I would be happy to break this down either by file or even by function. Just let me know how you would like to proceed.
Also if this does seem valuable, my plan is to continue through …

chore: Add test coverage to utils (array and dom)

---

packages/ariakit/src/composite/composite-hover.ts

fix: Fix modal `Dialog` not opening when triggered by `MenuItem`

---

packages/ariakit/src/hovercard/hovercard-anchor.ts

This PR fixes a bug on `MenuBar` where two menus may be visible at the same time when touching the menu bar items.
It turns out that we need to ignore `mousemove` events without an actual mouse movement.
This also potentially fixes #1091

fix: Fix `MenuBar` on iOS

---

.changeset/fast-files-march.md
packages/ariakit/src/hovercard/hovercard.tsx

Refresh the enter point reference while the mouse is moving through the transit polygon towards the hovercard.

Fix the logic behind the Hovercard transit area

---

.changeset/popover-state-get-anchor-rect.md
packages/ariakit/src/menu/__examples__/menu-context-menu/index.tsx
packages/ariakit/src/popover/popover-disclosure.tsx
packages/ariakit/src/popover/popover-state.ts

This PR adds a `getAnchorRect` prop to the `usePopoverState` hook and replaces the existing `defaultAnchorRect`/`anchorRect`/`setAnchorRect` props that don't work in certain situations. For example, due to how React updates work, there's always a delay between `setAnchorRect` and the actual update on the UI.

Add getAnchorRect prop to usePopoverState

---

.changeset/menu-initial-focus.md
packages/ariakit/src/menu/__examples__/menu-bar/test.tsx
packages/ariakit/src/menu/menu.ts

This PR fixes an inconsistency in the initial focus of the Menu component (especially when we unmount and re-mount all the menu items). See `menu-combobox` example.

Fix Menu initial focus

---

.changeset/dialog-prevent-body-scroll-ios.md
jest.setup.js
packages/ariakit/src/dialog/__utils/use-prevent-body-scroll.ts

This PR improves the "prevent body scroll" logic on `Dialog`.
Closes #1085

Fix Dialog body scroll on iOS

---

.changeset/npmignore-src-folder.md
.codesandbox/ci.json
packages/ariakit-playground/.npmignore
packages/ariakit-test-utils/.gitignore
packages/ariakit-test-utils/.npmignore
packages/ariakit-utils/.npmignore
packages/ariakit/.npmignore

This is so we can reduce the downloadable size of the packages, which will get even more prominent as we add more examples and tests.

Stop shipping src folder with the npm packages

---

packages/ariakit/src/form/form-input.ts

Fixed a simple typo in the FormInput description. `unline` to `unlike`

Fix typo in FormInput description

---

.changeset/utils-use-store-provider-return-type.md
packages/ariakit-utils/src/store.tsx

While writing tests for the store utils, I got confused by the return type of `useStoreProvider`. TS was saying that `wrapElement` might be undefined. 
However, when inspecting the way `useWrapElement` works and its types, I was pretty sure there was no way it could be undefined and its types agreed.
So after adjusting things a bit I realized it was because the types were being inherited from the `useStoreProvider` argument types. Specifically `{ state, ...props }: P & { state?: S; wrapElement?: WrapElement },`. This was because props was being redefined. I updated the code to simply return `useWrapElement` however, if there was a reason to keep it closer to the previous code, defining a new variable (Ex. `newProps`) would have the same result. 
I didn't update any changeset files because …

Update useStoreProvider to return a more accurate type

---

.changeset/dialog-backdrop-hidden.md
packages/ariakit/src/dialog/__utils/dialog-backdrop.tsx
packages/ariakit/src/dialog/dialog.tsx

When explicitly rendering `<Dialog hidden={false} />`, we don't style the dialog with `display: none`. But the backdrop element currently doesn't inherit this behavior. We have to do this:
```jsx
<Dialog hidden={false} backdropProps={{ hidden: false }} />
```
This PR changes it so Dialog automatically passes its hidden prop to the backdrop element.

Pass hidden prop to DialogBackdrop

---

.changeset/composite-hover-focus-visible.md
.changeset/test-hover-microtask.md
jest.config.js
packages/ariakit-test/src/__tests__/blur-test.tsx
packages/ariakit-test/src/hover.ts
packages/ariakit/src/composite/__examples__/composite-hover-virtual-focus-events/index.tsx
packages/ariakit/src/composite/__examples__/composite-hover-virtual-focus-events/style.css
packages/ariakit/src/composite/__examples__/composite-hover-virtual-focus-events/test.tsx
packages/ariakit/src/composite/composite.ts

This PR fixes the `data-focus-visible` attribute that was being erroneously added to composite items with `CompositeHover` and `virtualFocus: true`.
See tests and example for more details.

Fix focus-visible behavior on composite items

---

contributing.md
packages/ariakit/readme.md

Open in Gitpod added in the README.md
Gitpod is a remote development environment. It allows the user to contribute/ browse the contents of the github repository in the browser.
[Link](https://gitpod.io/)
Adding this OS feature in the README.md would allow the contributors to open the codebase directly into their browser.
(P.S : Not sponsored by Gitpod. Just want to add this functionality in order to improve user experiences)

Added Open in Gitpod

---

packages/ariakit/src/separator/__examples__/separator/index.tsx
packages/ariakit/src/separator/__examples__/separator/styles.css
packages/ariakit/src/separator/__examples__/separator/test.tsx
packages/ariakit/src/separator/readme.md
packages/website/pages/index.tsx

Adds the `separator` example for #939
Hey, first time here really liked this project and I plan to be an active contributor. If there is anything I missed or could improve let me know.

chore: Add `separator` example

---

.changeset/utils-use-event-timing.md
packages/ariakit-utils/src/__tests__/hooks-test.tsx
packages/ariakit-utils/src/hooks.ts

There are situations where `useLayoutEffect` may not execute before the event callback is called. For example, when calling the event callback in a layout effect in a child component.

Fix useEvent hook timing

---

.changeset/select-empty-initial-focus.md
packages/ariakit/src/select/select-popover.ts

This pull request uses the select's base ref as a fallback when there is no focusable item to focus.
Fixes #1553

Use listbox as a fallback ref when there is no focusable item to focus

---

.changeset/menu-show-auto-focus.md
packages/ariakit/src/menu/menu.ts

When we open a `Menu` component using `menu.show()`, we also have to call `menu.setAutoFocusOnShow(true)`, which is not really obvious. This PR eliminates the need to call `setAutoFocusOnShow`.

Make it easier to programmatically open a menu

---

.changeset/select-focus-firefox.md
packages/ariakit/src/dialog/dialog.tsx
packages/ariakit/src/focusable/focusable.ts

This PR fixes a bug where the select popover wasn't receiving focus when the select button got clicked on Firefox on macOS.
Since Firefox 88, buttons receive focus on mouse down. The fact that we were forcing focus on the select button in a requestAnimationFrame callback was conflicting with the popover initial focus that happened right after the first time the select button received focus.

Fix Select focus on Firefox/macOS

---

.changeset/popover-arrow-flash.md
packages/ariakit/src/popover/popover-state.ts

Update the current placement state synchronously to avoid styling flashes. For example, without this, a popover that has initially placement set to "bottom", but gets flipped to "top" will have a frame where the popover arrow is not properly rotated (PopoverArrow uses the currentPlacement state).

Fix PopoverArrow styling flash

---

.changeset/dialog-auto-focus-on-show.md
.changeset/dialog-scroll-into-view.md
.changeset/utils-ensure-focus.md
.changeset/utils-focus-into-view.md
packages/ariakit-utils/src/__tests__/focus-test.ts
packages/ariakit-utils/src/focus.ts
packages/ariakit/src/composite/composite.ts
packages/ariakit/src/dialog/dialog.tsx
packages/ariakit/src/menu/menu.ts
packages/ariakit/src/popover/popover.tsx

This PR fixes an issue on Firefox where auto focusing on dialog show/hide wouldn't work with [`scroll-behavior: smooth`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior).
`autoFocusOnShow` and `autoFocusOnHide` can now be functions so that the new behavior can be overwritten.

Support autoFocusOnShow prop as a function on Dialog

---

.changeset/menu-list-role.md
packages/ariakit/src/menu/menu-list.ts

I'm reverting this fix because changing the semantics of the widget this way may be more harmful than dealing with this bug on Safari.
Nonetheless, there's an open ticket on the WebKit tracker: https://bugs.webkit.org/show_bug.cgi?id=241445

Revert Menu fix on Safari

---

.changeset/tooltip-position.md
packages/ariakit/src/tooltip/tooltip.tsx

On #1592, we removed the popover position style from the `usePopoverState` hook and added it to the `Popover` component, but forgot to add it to the Tooltip as well.

Fix tooltip position

---

.changeset/menu-button-autofocus.md
packages/ariakit/src/menu/menu-button.ts

When a menu is open and has a leave animation, clicking twice on the menu button before the animation completes wouldn't move the focus to the menu popup.

Fix auto focus when re-opening menu quickly

---

.changeset/form-field-name.md
packages/ariakit/src/form/form-field.ts

Custom components used with `FormField` won't include the `name` prop on the first render (and on the server) even when the underlying element accepts it. This PR removes the initial check, so the `name` prop is always passed down. The consumer is responsible for stripping this prop if necessary.

Always pass name prop down on FormField

---

.changeset/dialog-auto-focus.md
packages/ariakit/src/dialog/dialog.tsx
packages/ariakit/src/menu/__examples__/menu-slide/menu.tsx

This PR reverts a change we made on #1599. It turns out that preventing scroll when a dialog shows up has other side effects. For example, the selected option in a Select component will be at the end of the popover viewport when it needs to scroll when opening. This isn't a great UX as the following options won't be immediately visible.

Do not prevent scroll on Dialog auto focus

---

.changeset/composite-focus-item.md
packages/ariakit/src/composite/composite.ts

When two or more composite components are used together, but only one has `composite={true}` (default), we only need to focus on the items once.

Avoid duplicate work when combining two composite components

---

.changeset/disclosure-animated.md
packages/ariakit/src/dialog/dialog.tsx
packages/ariakit/src/disclosure/disclosure-content.ts
packages/ariakit/src/disclosure/disclosure-state.ts
packages/ariakit/src/select/__examples__/select-animated/test-browser.ts

This PR updates the logic behind disclosure animations in the library.
Instead of relying on the `transitionend`/`animationend` events, which may not fire under certain circumstances, we'll detect the animation/transition delay and duration values by parsing the computed styles and automatically schedule the `stopAnimation()` call.
Closes #1684

Improve animation logic

---

.changeset/dialog-backdrop-type-re.md
.changeset/dialog-backdrop-type.md
packages/ariakit/src/dialog/dialog.tsx

As mentioned in [this comment](https://github.com/ariakit/ariakit/issues/1698#issuecomment-1203456837), the previous type for DialogOptions.backdrop(`ElementType<ComponentPropsWithRef<"div">>`) is actually a subset of the type added in #1700. Replaced both with `ElementType<ComponentProps<"div">>`.

Optimize the type of DialogOptions.backdrop

---

.changeset/tab-default-id-react17.md
packages/ariakit/src/tab/__examples__/tab/index.tsx
packages/ariakit/src/tab/__examples__/tab/test.tsx
packages/ariakit/src/tab/tab-panel.ts
packages/ariakit/src/tab/tab.ts

We have a `useId` hook to generate IDs for our components automatically. In React 17, this function needs a second render.
When the user passes a static `id` prop to the `Tab` component, this tab is registered to the state in the first render — before the other tabs relying on the `useId` hook. This means that `TabPanel` components without an explicit `tabId` prop, when scanning the tab items to find its match, will only see that single tab that was registered first and assume that's the matching tab.
To fix this, we're waiting `useId` to be fulfilled on all Tabs before registering them, even those that get an `id` prop. This way, they're all registered at the same time.
Closes #1721

Fix Tab with default selected id on React 17

---

.changeset/menu-button-role.md
.changeset/utils-get-popup-item-role.md
packages/ariakit-utils/src/__tests__/dom-test.ts
packages/ariakit-utils/src/dom.ts
packages/ariakit/src/combobox/combobox-item.tsx
packages/ariakit/src/menu/menu-button.ts
packages/ariakit/src/menu/menu-item.ts
packages/ariakit/src/select/select-item.tsx

Currently, the `role` attribute on `MenuButton` is hard-coded as `menuitem` whenever rendered inside another menu.
This may be problematic when we combine nested `Menu` components with other composite containers, like `SelectPopover`, `SelectList`, `ComboboxPopover`, `ComboboxList`, etc.
This PR updates the `MenuButton` component to determine its role attribute based on the composite content element's role. This is similar to what other composite items do.

Support dynamic role attribute on MenuButton

---

.changeset/combobox-links.md
.changeset/utils-is-opening-in-new-tab.md
packages/ariakit-playground/src/__examples__/playground/test-chrome.ts
packages/ariakit-utils/src/events.ts
packages/ariakit/src/combobox/__examples__/combobox-links/index.tsx
packages/ariakit/src/combobox/__examples__/combobox-links/style.css
packages/ariakit/src/combobox/__examples__/combobox-links/test-browser.ts
packages/ariakit/src/combobox/__examples__/combobox-textarea/test-chrome.ts
packages/ariakit/src/combobox/combobox-item.tsx
packages/ariakit/src/command/command.ts
packages/ariakit/src/composite/composite.ts
packages/ariakit/src/menu/menu-item.ts
packages/ariakit/src/popover/__examples__/popover-flip/test-chrome.ts
packages/ariakit/src/select/select-item.tsx

This PR improves support for `CompositeItem` rendered as a link. This includes `ComboboxItem`, `MenuItem`, and `SelectItem` components. Now clicking on `<a>` items with a mouse or keyboard while pressing `metaKey` (macOS) or `ctrlKey` (PC) opens the link in a new tab as expected. Popovers won't close, and `Select`/`Combobox` values won't change when clicking with those modifiers.

Improve support for composite items as links

---

.changeset/menu-heading-aria-labelledby.md
packages/ariakit/src/menu/__examples__/menu-dialog-animated/test-chrome.ts
packages/ariakit/src/menu/menu.ts

This PR fixes the `aria-labelledby` prop on `Menu` when using `MenuHeading`. Instead of using the heading id, it still referenced the menu button element. Now `MenuHeading` correctly takes precedence.

Use MenuHeading's id on Menu's aria-labelledby prop

---

.changeset/combobox-on-key-down.md
packages/ariakit/src/combobox/combobox.ts
packages/ariakit/src/composite/composite.ts

We were stopping the propagation of the `onKeyDownCapture` event on the `Combobox` component when pressing printable keys and the Home/End keys. This was so the event wasn't propagated to the combobox items by the `Composite` component. But, as a side effect, we were also preventing the `onKeyDown` event from happening on the combobox itself.
This PR moves this logic to the composite component, so we don't need to stop the propagation on combobox.

Allow onKeyDown prop on Combobox when pressing printable keys

---

.changeset/hovercard-polygon.md
packages/ariakit/src/hovercard/__examples__/hovercard/test-browser.ts
packages/ariakit/src/hovercard/__utils/polygon.ts
packages/ariakit/src/hovercard/hovercard.tsx

When the Hovercard component was positioned diagonally to the anchor, it was prematurely hiding when moving the mouse onto it. This was because we only considered one position (`top`, `right`, `bottom`, `left`) when calculating the transit area polygon.
This PR considers both `x` and `y` coordinates when creating the polygon.

Fix Hovercard transit area

---

packages/ariakit/src/combobox/__examples__/combobox-inline-autocomplete/index.tsx
packages/ariakit/src/combobox/__examples__/combobox-inline-autocomplete/style.css
packages/ariakit/src/combobox/__examples__/combobox-inline-autocomplete/test.tsx
packages/website/pages/index.tsx

Trying to complete: #939 "Combobox with autoComplete set to inline"
I'm not sure if the test cases are enough and if the example is complete enough, let me know!

Add `combobox` inline autocomplete example

---

.changeset/composite-item-new-tab-background.md
.changeset/composite-link-download.md
.changeset/utils-is-downloading.md
packages/ariakit-utils/src/events.ts
packages/ariakit/src/combobox/__examples__/combobox-links/icons.tsx
packages/ariakit/src/combobox/__examples__/combobox-links/index.tsx
packages/ariakit/src/combobox/__examples__/combobox-links/style.css
packages/ariakit/src/combobox/__examples__/combobox-links/test-browser.ts
packages/ariakit/src/combobox/__examples__/combobox/style.css
packages/ariakit/src/combobox/combobox-item.tsx
packages/ariakit/src/command/command.ts
packages/ariakit/src/composite/composite-state.ts
packages/ariakit/src/menu/menu-item.ts
packages/ariakit/src/select/select-item.tsx

See changesets for more context.
When the composite item received the <kbd>Enter</kbd> key down event, we were dispatching the click event asynchronously. Because of that, when activating links with <kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>Enter</kbd>, some browsers wouldn't open the new tab in the background. Instead, the new tab would be brought to the front.
To fix that, this PR dispatches the click event in a microtask that will be executed at the end of the current event loop.

Improve support for links on composite components with virtual focus

---

.changeset/combobox-set-value-on-mouse-down.md
packages/ariakit/src/combobox/__examples__/combobox-inline-autocomplete/test.tsx
packages/ariakit/src/combobox/__examples__/combobox/test.tsx
packages/ariakit/src/combobox/combobox.ts

This PR fixes a bug that wouldn't allow text selection on a `Combobox` with `autoComplete="inline"` or `autoComplete="both"` if the mouse is released outside of the combobox input.
The problem was that the temporary inline value would only be set to the combobox state on click. If the mouse is released outside of the element, the click event is not dispatched so we don't get the value set. This PR changes this behavior, so the logic is performed on mouse down instead.

Fix combobox inline selection

---

.changeset/focusable-focus-visible-timing.md
packages/ariakit/src/focusable/focusable.ts

If the focus changed during the key down event on a Focusable element, the blur event would trigger before our `onFocusVisible` function. This means that the `data-focus-visible` attribute would be set *after* the blur event and, therefore, wouldn't be removed.
This is the case with some browser extensions like 1password.
This PR solves this by calling `onFocusVisible` in a microtask and always checking if the element has focus before setting the focusVisible state to true.

Fix onFocusVisible timing

---

.changeset/select-autofill-focus.md
packages/ariakit/src/select/__examples__/select-autofill/test.tsx
packages/ariakit/src/select/select.tsx

Some browser extensions, like 1password, move focus to the next form element when auto-filling fields. We render a visually hidden native select element on the' Select' component. This element is not tabbable, but it's still focusable. To fix the issue, we'll automatically focus on our custom select element when the native element receives focus.

Fix auto focus on the native select element

---

.changeset/form-field-validity-state.md
packages/ariakit/src/form/form-field.ts
packages/ariakit/src/form/form-state.ts

In some situations, the validity state is out of date when validation happens on `FormField`.
This PR changes the logic so we wait for microtasks to be executed before checking the element's validity state.

Fix stale validity state on FormField

---

.changeset/composite-typeahead-use-store.md
packages/ariakit/src/composite/composite-typeahead.ts

Instead of using `useContext` directly, this PR updates the `CompositeTypeahead` component to `useStore` so it doesn't try to use the dynamic composite context (that may trigger unnecessary and sometimes expensive re-renders) when the `state` prop has been provided.

Improve CompositeTypeahead runtime performance

---

.changeset/popover-size-available.md
packages/ariakit/src/popover/popover-state.ts

Some displays will show blurred pixels when the Popover tries to fit the viewport with float numbers. This PR fixes this using `Math.floor` on them.

Fix Popover blurred pixels when trying to fit viewport

---

.changeset/combobox-auto-select.md
.changeset/composite-item-move-on-key-press copy.md
.changeset/composite-move-on-key-press.md
packages/ariakit/src/combobox/__examples__/combobox-group/index.tsx
packages/ariakit/src/combobox/__examples__/combobox-group/test.tsx
packages/ariakit/src/combobox/__examples__/combobox-textarea/test.tsx
packages/ariakit/src/combobox/combobox-item.tsx
packages/ariakit/src/combobox/combobox.ts
packages/ariakit/src/composite/composite-item.tsx
packages/ariakit/src/composite/composite.ts
packages/ariakit/src/menu/__examples__/menu-combobox/test.tsx

Closes #1475
This PR improves the behavior of `Combobox` with the `autoSelect` prop set to `true`.
Before, when `autoSelect` was enabled, the first item would be selected only on text insertion. That is, deleting or pasting text was ignored. This was so the `inline` autocomplete (automatically updating and highlighting the input value while typing) would work properly. In other words, we didn't want to trigger the inline auto-completion when deleting text from the combobox input. After some feedback and research, this behavior seemed counter-intuitive.
This PR decouples `autoSelect` from the `autoComplete="inline"` (or `autoComplete="both"`) behavior. While the latter keeps working only on text insertion (or when the user deliberately moves the focus to an item using the keyboard), the …

Improve Combobox autoSelect and inline autocomplete behavior

---

.changeset/combobox-inline-caret-at-end.md
packages/ariakit/src/combobox/__examples__/combobox-group/test.tsx
packages/ariakit/src/combobox/combobox.ts

This PR updates the behavior of the `Combobox` component with `autoComplete="inline"` or `autoComplete="both"` so the completion string is only appended and highlighted when the caret is at the end of the input. This avoids a situation where inserting text at the beginning of an input unexpectedly moves the caret to the end.

Allow inline auto-complete only when caret is at the end

---

.changeset/composite-proxy-event-modifier-keys.md
packages/ariakit/src/composite/composite.ts

This PR fixes a bug where a scroll jump happens in this scenario:
1. `ComboboxItem` has `focusOnHover` prop set to `true`.
2. Hover over an item.
3. Move the scroll position without moving the mouse.
4. Press any modifier key.

Fix scroll jump on Combobox when pressing modifier keys

---

packages/ariakit/src/menu/__examples__/menu-slide/style.css

Add `scroll-snap-stop: always` to prevent swiping to go back multiple pages, because I was surprised at the current behavior while using it, but just a suggestion!
With this change, you can only go back one page at a time when swiping fast. You can still drag it all the way though (with no flick).
Before (first fast flick, then slow drag):
https://user-images.githubusercontent.com/15364860/194398697-d2f4c170-6f2c-4e23-8a5c-8a72e75fd91e.mov
After (first fast flick, then slow drag):
https://user-images.githubusercontent.com/15364860/194398770-008d841b-36f3-4c0e-824f-4d09d4a5af12.mov

Sliding Menu Example: Prevent being able to swipe multiple pages

---

.changeset/unique-type-names.md
packages/ariakit/src/checkbox/checkbox-state.ts
packages/ariakit/src/collection/__utils.ts
packages/ariakit/src/collection/collection-item.ts
packages/ariakit/src/collection/collection-state.ts
packages/ariakit/src/combobox/combobox-state.ts
packages/ariakit/src/composite/__utils.ts
packages/ariakit/src/composite/composite-item.tsx
packages/ariakit/src/composite/composite-state.ts
packages/ariakit/src/composite/composite-typeahead.ts
packages/ariakit/src/composite/composite.ts
packages/ariakit/src/form/form-state.ts
packages/ariakit/src/select/__utils.ts
packages/ariakit/src/select/select-popover.ts
packages/ariakit/src/select/select-state.ts
packages/ariakit/src/select/select.tsx
packages/ariakit/src/tab/tab-state.ts

Due to whitespace changes from reformatting, this diff is better viewed with [?w=1](https://github.com/ariakit/ariakit/pull/2153/files?w=1).
* Update types referenced in #2092 to have unique names, in order to support a .d.ts bundler that requires this uniqueness
* Update references to use the new names, done using IntelliJ's Refactor -> Rename
* Reformat files as required
Closes #2092.
Thank you again for being open to this PR!

Rename types to have unique names matching their pattern

---

.changeset/config.json
.changeset/radio-default-value.md
examples/radio-default-value/index.tsx
examples/radio-default-value/style.css
examples/radio-default-value/test.ts
packages/ariakit-core/src/radio/radio-store.ts
packages/ariakit-react-core/src/radio/radio.ts

Fix radio store not accepting `defaultValue` as a prop

---

.changeset/short-ties-switch.md
examples/menu-dialog-animated/dialog.tsx
examples/menu-dialog-animated/index.tsx
packages/ariakit-react-core/src/dialog/dialog.tsx

When rendering `Dialog` with `React.lazy`, returning focus when the dialog is closed isn't working. This PR fixes that.

Fix `Dialog` not returning focus when rendered with `React.lazy`

---

.changeset/wet-jobs-relate-2.md
.changeset/wet-jobs-relate-3.md
.changeset/wet-jobs-relate.md
examples/combobox-cancel/test.ts
examples/combobox-group/test-browser.ts
examples/combobox-group/test.ts
packages/ariakit-react-core/src/combobox/combobox.ts
packages/ariakit-test/src/type.ts

This PR fixes a bug where the completion string would be lost when the user keeps typing the same value. Please take a look at the test-browser file for more details.
This also closes #2203. Unfortunately, neither JSDOM nor Playwright supports IME. I had to simulate it with composition events, so the tests aren't 100% accurate.

Fix combobox completion string when using inline autoSelect

---

.changeset/large-goats-kneel.md
.changeset/lemon-comics-compare.md
examples/form-radio/icon.tsx
examples/form-radio/index.tsx
examples/form-radio/readme.md
examples/form-radio/style.css
examples/form-radio/test.ts
examples/form/index.tsx
examples/form/style.css
examples/radio/icon.tsx
packages/ariakit-core/src/utils/focus.ts
packages/ariakit-core/src/utils/store.ts
packages/ariakit-react-core/src/collection/collection-item.ts
packages/ariakit-react-core/src/composite/composite-item.tsx
vitest.setup.ts

Closes #2281 
This PR makes the `store` prop optional on `CompositeItem` and `CollectionItem` components, so we can use `Radio` and `FormRadio` without explicitly passing a store.

Fix FormRadio error when not providing composite store

---

.changeset/thick-yaks-count.md
packages/ariakit-core/src/utils/store.ts

Using `@deprecated` should prevent people from using these experimental methods. Also, they will be obfuscated on VSCode autocompletion hints, which helps to discover the actual public APIs.

Mark internal store functions as deprecated/experimental

---

.changeset/two-pans-nail.md
examples/select-combobox-focus-within/select-combobox.tsx
examples/select-combobox/index.tsx
packages/ariakit-react-core/src/combobox/combobox-item-value.tsx
packages/ariakit-react-core/src/dialog/dialog-backdrop.tsx
packages/ariakit-react-core/src/utils/system.tsx
packages/ariakit-react-core/src/utils/types.ts
website/components/editor.tsx
website/components/header-menu.tsx
website/components/header-nav.tsx
website/components/header-version-select.tsx
website/components/playground-browser.tsx
website/components/playground-toolbar.tsx
website/components/popup.tsx

This PR adds a `render` prop to all components as an alternative to the `children` prop as a function.
The difference is that the `render` prop will also receive the `children` passed to the original component, which makes the code much cleaner.
Using `children`:
```jsx
<Ariakit.ComboboxItem
ref={ref}
focusOnHover
className="select-item"
{...props}
>
{(props) => (
<Ariakit.SelectItem {...props} value={value}>
{props.children}
</Ariakit.SelectItem>
)}
</Ariakit.ComboboxItem>
```
Using `render`:
```jsx
<Ariakit.ComboboxItem
ref={ref}
focusOnHover
className="select-item"
{...props}
render={(props) => <Ariakit.SelectItem {...props} value={value} />}
/>
```

Add a `render` prop to the system

---

.changeset/tab-activeid.md
examples/dialog-nested/confirm-dialog.tsx
examples/dialog-react-router/index.tsx
examples/dialog-react-router/readme.md
examples/menu-dialog-animated/dialog.tsx
examples/popover-focus-within/popover.tsx
examples/popover-lazy/index.tsx
examples/popover-standalone/popover.tsx
examples/tab-react-router/index.tsx
examples/tab-react-router/tabs.tsx
guide/400-component-stores/readme.md
packages/ariakit-core/src/tab/tab-store.ts
packages/ariakit-core/src/utils/store.ts
packages/ariakit-react-core/src/utils/store.tsx
website/app/(examples)/previews/dialog-next-router/readme.md
website/app/(examples)/previews/tab-next-router/readme.md
website/app/(examples)/previews/tab-next-router/tabs.tsx
website/app/(examples)/previews/tab-next-router/test-browser.ts
website/components/header-menu.tsx

This PR fixed the [Tab with Next.js App Router](https://ariakit.org/examples/tab-next-router) example when the `selectOnMove` prop is set to `true` (default).
It turns out there was a problem with getting the `activeId` state in sync with `selectedId`.

Fix Tab activeId sync

---

.changeset/checkbox-examples-1.md
.changeset/checkbox-examples-2.md
components/checkbox.md
components/group.md
examples/checkbox-as-button/readme.md
examples/checkbox-as-button/site-icon.tsx
examples/checkbox-as-button/style.css
examples/checkbox-controlled/readme.md
examples/checkbox-custom/checkbox.tsx
examples/checkbox-custom/index.tsx
examples/checkbox-custom/readme.md
examples/checkbox-custom/site-icon.tsx
examples/checkbox-custom/style.css
examples/checkbox-custom/test.ts
examples/checkbox-group/index.tsx
examples/checkbox-group/readme.md
examples/checkbox-group/site-icon.tsx
examples/checkbox-store/readme.md
examples/checkbox/style.css
guide/200-styling/readme.md
packages/ariakit-react-core/src/checkbox/checkbox.tsx
packages/ariakit-react-core/src/command/command.ts
website/app/(main)/[category]/[page]/page.tsx
website/build-pages/config.js

This PR improves the current checkbox docs and fixes two related issues:
- The `Checkbox` component now accepts `string[]` as the `value` prop. This is to conform with the native input prop type. If a string array is passed, it will be stringified, just like in the native input element.
- Fixed the `clickOnEnter` prop on `Checkbox` not working when rendering the component as a native input element.

Improve checkbox examples

---

.changeset/composite-typeahead-trim.md
components/menu.md
examples/menu-item-checkbox/index.tsx
examples/menu-item-checkbox/menu.tsx
examples/menu-item-checkbox/readme.md
examples/menu-item-checkbox/site-icon.tsx
examples/menu-item-checkbox/test.ts
packages/ariakit-react-core/src/composite/composite-typeahead.ts
website/components/page-item.tsx

Trim the composite item element's text before comparing it with the pressed key.

Fix composite typeahead when the item text starts with a space

---

.changeset/hide-on-control.md
packages/ariakit-react-core/src/hovercard/hovercard.tsx

This PR removes the `hideOnControl` prop from the `Hovercard` and derived components (`Tooltip`, `Menu`, etc.).

Remove hideOnControl prop from Hovercard

---

.changeset/lazy-lizards-change.md
scripts/build/utils.js

Add extension to paths in proxy package.json files

---

.changeset/dialog-modal-animated-1.md
.changeset/dialog-modal-animated-2.md
examples/dialog-nested-multiple/dialog.tsx
examples/dialog-nested-multiple/index.tsx
examples/dialog-nested-multiple/style.css
examples/dialog-nested-multiple/test-browser.ts
examples/dialog-nested-multiple/test.ts
packages/ariakit-react-core/package.json
packages/ariakit-react-core/src/dialog/dialog-backdrop.tsx
packages/ariakit-react-core/src/dialog/dialog.tsx
packages/ariakit-react-core/src/dialog/utils/disable-accessibility-tree-outside.ts
packages/ariakit-react-core/src/dialog/utils/disable-tree-outside.ts
packages/ariakit-react-core/src/dialog/utils/is-backdrop.ts
packages/ariakit-react-core/src/dialog/utils/mark-tree-outside.ts
packages/ariakit-react-core/src/dialog/utils/orchestrate.ts
packages/ariakit-react-core/src/dialog/utils/use-prevent-body-scroll.ts
packages/ariakit-react-core/src/dialog/utils/use-root-dialog.ts
packages/ariakit-react-core/src/focusable/focusable.ts

Closes #2528
Instead of allowing any dialog to disable body scroll, this PR makes it so only the root dialog (determined by the internal `useRootDialog` hook) has control over this behavior.

Improve modal behavior on animated dialogs

---

.changeset/collection-store-default-items.md
packages/ariakit-core/src/collection/collection-store.ts

This PR fixes the `defaultItems` prop on the collection store and other stores that use it. The default items passed to the collection were being overridden when new items were added.

Persist defaultItems in the collection store

---

.changeset/menu-combobox-initial-focus.md
examples/menu-combobox/index.tsx
examples/menu-combobox/test.ts
guide/400-component-stores/readme.md
packages/ariakit-core/src/collection/collection-store.ts
packages/ariakit-react-core/src/combobox/combobox.ts
packages/ariakit-react-core/src/menu/menu.ts

When the rendered items changed, pressing <kbd>ArrowDown</kbd> on a menu button, after closing the menu, wouldn't focus on the first menu item.

Fix Menu/Combobox initial focus

---

.changeset/composite-hover-scroll-into-view.md
.github/workflows/main.yml
examples/combobox-group/test-browser.ts
packages/ariakit-react-core/src/composite/composite.tsx

This PR updates the `Composite` component so composite items aren't scrolled into view when they get focused on hover.

Do not scroll composite item into view on hover

---

.changeset/combobox-auto-select-maintain-value.md
examples/combobox-group/combobox.tsx
examples/combobox-group/index.tsx
examples/combobox-group/test-browser.ts
packages/ariakit-react-core/src/combobox/combobox.ts

This PR fixes the `Combobox` behavior when using the `autoSelect` and the `autoComplete="both|inline"` props. Pressing <kbd>Tab</kbd> or clicking outside while the inline auto-complete was active wouldn't work as expected.

Maintain Combobox value on blur

---

.changeset/role-elements.md
packages/ariakit-react-core/src/role/role.ts
website/app/(main)/[category]/[page]/page.tsx
website/components/header-updates.tsx
website/components/newsletter-form.tsx

This PR adds a new experimental feature to the `Role` component. It can be rendered like `Role.div`, `Role.a`, `Role.buton`, etc.

Add experimental element keys to Role

---

.changeset/cyan-forks-pretend.md
examples/menu/index.tsx
packages/ariakit-react-core/src/utils/store.tsx

With the #2671 change, React started showing a warning when `flushSync` was called from inside a lifecycle method. Since the `store.sync` callback can be called immediately, this PR changes it so the `flushSync` function is used only in subsequent calls.

Fix flushSync warning

---

.changeset/combobox-min-length.md
examples/combobox-min-length/index.tsx
examples/combobox-min-length/test.ts
packages/ariakit-react-core/src/combobox/combobox.ts

The `combobox-min-length` example using the derived state technique (setting a controlled state on render) did not work properly after introducing synchronous updates on the store in #2671. This pull request resolves the issue by moving the `showOnChange` behavior below the value update.

Fix combobox-min-length example

---

.changeset/2737-chilly-rivers-argue.md
examples/select-listbox/index.tsx
examples/select-listbox/style.css
examples/select-listbox/test.ts
packages/ariakit-react-core/src/utils/store.tsx

This PR addresses a bug that occasionally results in components rendering with an incorrect or outdated state when controlled values are passed as props to component stores. In other words, the rendered state differs from the one supplied by the user via the store hook props.

Fix controlled component store rendering with stale state

---

.changeset/2745-thin-pugs-thank.md
packages/ariakit-core/src/checkbox/checkbox-store.ts
packages/ariakit-core/src/collection/collection-store.ts
packages/ariakit-core/src/combobox/combobox-store.ts
packages/ariakit-core/src/disclosure/disclosure-store.ts
packages/ariakit-core/src/form/form-store.ts
packages/ariakit-core/src/menu/menu-store.ts
packages/ariakit-core/src/popover/popover-store.ts
packages/ariakit-core/src/select/select-store.ts
packages/ariakit-core/src/utils/store.ts
packages/ariakit-react-core/src/utils/system.tsx

This PR introduces an error that's triggered in the following scenario:
```js
const a = useDialogStore();
const b = useDialogStore({ store: a, defaultOpen: true });
```
Both `a` and `b` ought to be synchronized. By default, the last store in the call stack takes precedence. However, it's still unclear what the value of the `open` state should be in the example above.
`a` has the `open` state set to `false` by default, while `b` has a default open state set to `true`. The default state should only be used when the `open` state is undefined. Since we're passing `a` to `b` and `a` has the `open` state defined, the `defaultOpen` value is disregarded, resulting in both `a` and `b` having the `open` state set to `false`.
This could be confusing, and we might change this behavior in the future. …

Throw when passing conflicting props to store

---

.changeset/0-2776-has-combobox.md
.changeset/0-2783-has-combobox.md
.changeset/0-2783-menu-select-on-combobox-store.md
.changeset/2783-sync-stores.md
packages/ariakit-core/src/combobox/combobox-store.ts
packages/ariakit-core/src/menu/menu-store.ts
packages/ariakit-core/src/select/select-store.ts
packages/ariakit-react-core/src/combobox/combobox-store.ts
packages/ariakit-react-core/src/menu/menu-store.ts
packages/ariakit-react-core/src/select/select-list.tsx
packages/ariakit-react-core/src/select/select-store.ts

This PR modifies the component stores that sync with other stores, such as `useMenuStore` and `useSelectStore`, which accept a `combobox` prop. Now, they return the provided store as a property of the store object.
For instance:
```js
const combobox = useComboboxStore();
const select = useSelectStore({ combobox });
console.log(combobox === select.combobox); // true
```
This modification enables us to verify in a Select component if it's being combined with a combobox. We previously relied on a `combobox` state for this, but it proved to be an inadequate general solution.
Furthermore, I've discontinued support for the `menu` and `select` props on `useComboboxStore`. These weren't in use anywhere, and they're more effectively supported as the `combobox` prop on `useSelectStore` and …

Return composed store props on component stores

---

.changeset/2796-store-null.md
packages/ariakit-core/src/disclosure/disclosure-store.ts
packages/ariakit-core/src/menu/menu-store.ts
packages/ariakit-core/src/popover/popover-store.ts
packages/ariakit-core/src/select/select-store.ts
packages/ariakit-core/src/utils/store.ts

Allowing `null` as a value for composed store properties makes it easier for users to override a default value inferred from context. For instance, if the tree is rendered as `Menu` > `Dialog` > `Menu`, the last `Menu` could mistakenly recognize the first one as its parent. In such a situation, the user can pass `parent: null` to `useMenuStore` or `MenuProvider` to turn off the default value.

Accept null value on composed store props

---

.changeset/2802-disclosure-store-set-mounted.md
examples/menu-dialog-animated/dialog.tsx
examples/menu-dialog-animated/menu.tsx
packages/ariakit-core/src/utils/store.ts
packages/ariakit-react-core/src/disclosure/disclosure-store.ts
packages/ariakit-react-core/src/utils/store.tsx

This PR adds a `setMounted` prop to `useDisclosureStore` and derived component stores. This callback prop can be used to react to changes in the `mounted` state. For example:
```js
useDialogStore({
setMounted(mounted) {
if (!mounted) {
props.onUnmount?.();
}
},
});
```

Add setMounted setter function to disclosure store

---

.changeset/2801-form-checkbox-integer-like.md
.changeset/odd-ears-camp.md
examples/form-checkbox-integer-like-name/index.tsx
examples/form-checkbox-integer-like-name/test.ts
packages/ariakit-core/src/form/form-store.ts

This fixes https://github.com/ariakit/ariakit/issues/2799.

Fix FormCheckbox erroring when an "integer-like" key is used

---

.changeset/2803-toolbar-standalone.md
examples/toolbar-provider-select/index.tsx
examples/toolbar-provider/index.tsx
packages/ariakit-react-core/src/toolbar/toolbar.tsx

With this PR, the `Toolbar` component can now render without needing an explicit `store` prop or a `ToolbarProvider` component wrap. This also adds some store props to `Toolbar`: `focusLoop`, `orientation`, `rtl`, `virtualFocus`.
Related to #2658

Add implicit store to Toolbar

---

.changeset/2812-disclosure-infinite-loop.md
packages/ariakit-react-core/src/disclosure/disclosure-store.ts
packages/ariakit-react-core/src/menu/menu-button.tsx

This PR fixes an infinite loop when using `MenuButton` with two synchronized stores like so:
```jsx
const store = useMenuStore();
const menu = useMenuStore({ store });
<MenuButton store={menu} />
```
There will be a follow-up PR with a test case.

Fix infinite loop on MenuButton

---

.changeset/2892-tasty-poets-poke-1.md
.changeset/2892-tasty-poets-poke-2.md
.changeset/z-jsdocs.md
components/dialog.md
examples/dialog-backdrop-scrollable/readme.md
examples/dialog-framer-motion/readme.md
examples/dialog-hide-warning/index.tsx
examples/dialog-hide-warning/readme.md
examples/dialog-hide-warning/site-icon.tsx
examples/dialog-hide-warning/style.css
examples/dialog-hide-warning/test.ts
examples/dialog-radix/readme.md
examples/dialog-react-router/readme.md
examples/dialog-react-toastify/readme.md
examples/menu-slide/readme.md
packages/ariakit-core/src/disclosure/disclosure-store.ts
packages/ariakit-react-core/src/dialog/dialog.tsx
packages/ariakit-react-core/src/focusable/focusable.ts
packages/ariakit-test/.gitignore
packages/ariakit-test/package.json
packages/ariakit-test/src/click.ts
packages/ariakit-test/src/focus.ts
packages/ariakit-test/src/hover.ts
packages/ariakit-test/src/index.ts
packages/ariakit-test/src/mouse-down.ts
packages/ariakit-test/src/mouse-up.ts
packages/ariakit-test/src/query.ts
packages/ariakit-test/src/select.ts
packages/ariakit-test/src/tap.ts
website/app/(examples)/previews/dialog-next-router/readme.md

Closes #2867
This PR adds an example inspired by the use case reproduced in #2867 with a more idiomatic implementation.
I've also added new query functions to the test package that were used to test this example.

Add dialog-hide-warning example

---

.changeset/2945-menu-item-controlled-1.md
.changeset/2945-menu-item-controlled-2.md
.changeset/2945-menu-item-controlled-3.md
.changeset/2945-menu-item-controlled-4.md
examples/menu-values-test/index.tsx
examples/menu-values-test/style.css
examples/menu-values-test/test.ts
packages/ariakit-core/src/utils/misc.ts
packages/ariakit-react-core/src/checkbox/checkbox.tsx
packages/ariakit-react-core/src/command/command.ts
packages/ariakit-react-core/src/composite/composite-item.tsx
packages/ariakit-react-core/src/focusable/focusable.ts
packages/ariakit-react-core/src/form/form-checkbox.ts
packages/ariakit-react-core/src/form/form-radio.ts
packages/ariakit-react-core/src/hovercard/hovercard-anchor.ts
packages/ariakit-react-core/src/menu/menu-button.tsx
packages/ariakit-react-core/src/menu/menu-item-checkbox.ts
packages/ariakit-react-core/src/menu/menu-item-radio.tsx
packages/ariakit-react-core/src/radio/radio.ts
packages/ariakit-react-core/src/select/select-item.tsx
packages/ariakit-react-core/src/tab/tab.ts

Closes #2913
Closes #2914
Closes #2915
Closes #2916
This PR introduces a new example, `menu-values-test`, illustrating various applications of the `MenuItemCheckbox` and `MenuItemRadio` components:
- Controlled with `checked` and `onChange` props.
- Uncontrolled with the `defaultChecked` prop.
- Controlled with a parent `onClick` handler.
- Disabled.
This PR addresses some bugs and missing features found in those scenarios. For more details, please refer to the linked issues and changeset files.

Support controlled props on MenuItemCheckbox and MenuItemRadio

---

.changeset/3037-hovercard-anchor.md
packages/ariakit-react-core/src/hovercard/hovercard-anchor.ts

When multiple `HovercardAnchor` elements are used for the same `Hovercard`, a bug occurred in the popover's position because the `anchorElement` was reset each time the popover was mounted. This PR resolves the problem by not depending on the `mounted` state, but instead setting the `disclosureElement` state in a microtask following the display of the popover.

Fix Hovercard when using multiple anchors

---

.changeset/3059-preserve-tab-order-anchor-1.md
.changeset/3059-preserve-tab-order-anchor-2.md
packages/ariakit-react-core/src/combobox/combobox-popover.tsx
packages/ariakit-react-core/src/popover/popover.tsx
packages/ariakit-react-core/src/portal/portal.tsx

This PR adds a new `preserveTabOrderAnchor` prop to `Portal` and related components. The `Popover` component also automatically sets it as its disclosure element.
This ensures that, when the `portal` prop is enabled, the tab order will be preserved from the disclosure to the content element even when the `Popover` component is rendered in a different location in the React tree when the' portal' prop is enabled.

Add `preserveTabOrderAnchor` prop to `Portal`

---

.changeset/3098-menubar-expand-focus.md
examples/menubar/test.ts
packages/ariakit-core/src/menubar/menubar-store.ts
packages/ariakit-react-core/src/menu/menu-button.tsx

This PR reverts a change introduced in v0.3.6. In that version, the `Menubar` component was updated so that hovering or focusing on one of its menu buttons would invariably open the menu popover if another menu button was already in focus.
This behavior proved to be inconsistent. So, I'm now reverting to the previous state where menus only expand if another menu is already expanded.

Revert Menubar always expanding with focus

---

.changeset/3151-select-default-open-controlled.md
examples/select-default-open-controlled/index.tsx
examples/select-default-open-controlled/style.css
examples/select-default-open-controlled/test.ts
packages/ariakit-core/src/utils/store.ts
packages/ariakit-test/src/react.tsx

Closes #3147
When the select popover was mounted by default, the external/context store was only initialized as part of the internal store, not the host/provider component. As a result, if the popover were unmounted, it would be destroyed, leaving the external/context store uninitiated.
This PR modifies the store logic to enable a store to be initialized again before it's destroyed.

Fix Select not opening when unmountOnHide is true

---

.changeset/3234-tab-store-update.md
packages/ariakit-react-core/src/tab/tab-store.ts

This PR fixes the tab store so it now updates the `store` object reference properly. For example, when a new `store` prop is passed to the tab store.

Fix Tab store reference updates

---

.changeset/3264-select-combobox-jump-scroll.md
examples/select-combobox/test-browser.ts
packages/ariakit-react-core/src/combobox/combobox.ts
packages/ariakit-react-core/src/select/select.tsx

I believe that this solution may not address the underlying issue. However, I am still submitting this PR so that we can have a temporary fix for now.
Another option we have is to call `store.move(activeId);` using a `flushSync` method, but this approach [may negatively impact performance as noted by React team](https://react.dev/reference/react-dom/flushSync).
Closes https://github.com/ariakit/ariakit/issues/1811

Prevent SelectCombobox to scroll jump on opening when using the keyboard

---

.changeset/3273-combobox-scroll-interupt-link-event.md
examples/combobox-links/test-browser.ts
packages/ariakit-react-core/src/composite/utils.ts

Fix CompositeItem not triggering onClick action when partially visible

---

examples/combobox-multiple/test-browser.ts
examples/menu-maximum-update-depth/index.tsx
examples/menu-maximum-update-depth/style.css
packages/ariakit-core/src/collection/collection-store.ts
packages/ariakit-core/src/utils/store.ts

Fix a regression introduced by #3241 where the `renderedItems` state was being reset on every scroll event.
Closes #3285
Re-opens #3214

Fix regression when scrolling composite items

---

.changeset/3288-safari-focus-fix.md
packages/ariakit-react-core/src/focusable/focusable.ts

`pointerup` is dispatched before `mouseup`, so using the former is safer.

Make sure buttons are focused before pointerup on Safari

---

.changeset/3559-tab-panel-unmount-on-hide.md
packages/ariakit-react-core/src/tab/tab-panel.tsx

When `TabPanel` has no `tabId`, it uses the element position in the DOM to determine the related tab. If we completely unmount the tab panel element, the active tab panel will be always rendered as the first one, and thus connected to the first tab.
This PR updates the logic so only the panel children will be unmounted, not the panel element itself.

Fix unmountOnHide on TabPanel

---

.changeset/3640-combobox-item-reset-value-on-select-1.md
.changeset/3640-combobox-item-reset-value-on-select-2.md
packages/ariakit-core/src/combobox/combobox-store.ts
packages/ariakit-react-core/src/combobox/combobox-item.tsx

Don't reset the value every time the `selectedValue` state changes. Only do so when the user interacts with the `ComboboxItem` component.

Move resetValueOnSelect option to ComboboxItem

---

.changeset/3716-select-toggle-on-click.md
packages/ariakit-react-core/src/form/form-label.tsx
packages/ariakit-react-core/src/select/select-label.tsx
packages/ariakit-react-core/src/select/select.tsx
website/components/header-version-select.tsx
website/components/playground-edit.tsx
website/components/playground-toolbar.tsx

To ensure uniformity across all dropdown buttons in the library, the [`SelectPopover`](https://ariakit.org/reference/select-popover) now opens when you click on the [`Select`](https://ariakit.org/reference/select) component, instead of on mouse/touch/pointer down.
This change also resolves a problem where the `:active` state wouldn't be triggered on the select button due to a focus change on mousedown.

Open SelectPopover on click instead of mousedown

---

.changeset/3721-focusable-sync-focus-visible.md
packages/ariakit-core/src/tab/tab-store.ts
packages/ariakit-react-core/src/focusable/focusable.tsx
packages/ariakit-react-core/src/tab/tab-panel.tsx
vitest.config.ts

Here we were setting the `data-focus-visible` attribute asynchronously in a microtask on the focus capture event:
https://github.com/ariakit/ariakit/blob/b273686cb6c644b5075e84e1202c15f7c4e67b28/packages/ariakit-react-core/src/focusable/focusable.tsx#L350-L352
However, when a blur event was immediately dispatched right after focus, the `data-focus-visible` attribute would be set after the blur event, leaving the element in an incorrect focus visible state.

Make sure focus visible is set before sync blur event

---

.changeset/3812-combobox-auto-select-touch-move.md
packages/ariakit-react-core/src/combobox/combobox.tsx

Closes #3808
I tried to write a test for it, but Playwright doesn't seem to support scroll on touch move yet (related: https://github.com/microsoft/playwright/issues/2903).

Fix Combobox autoSelect with virtualized list on mobile

---

.changeset/ninety-comics-worry.md
packages/ariakit-test/src/react.tsx
vitest.setup.ts

This PR changes the output of the `render` function of `@ariakit/test` to return `rerender`. Previously, it returned the `unmount` function directly, and now it returns an object with the shape `{ unmount, rerender }`.
Context: https://github.com/ariakit/ariakit/issues/3939#issuecomment-2258293118

Output `rerender` from `@ariakit/test`'s `render`.

---

.changeset/ninety-comics-worry.md
packages/ariakit-test/src/react.tsx
vitest.setup.ts

Revert "Output `rerender` from `@ariakit/test`'s `render`."

---

.changeset/ninety-comics-worry.md
packages/ariakit-test/src/react.tsx
vitest.setup.ts

(rework of #3978 after accidental git mess)
---
This PR changes the output of the `render` function of `@ariakit/test` to return `rerender`. Previously, it returned the `unmount` function directly, and now it returns an object with the shape `{ unmount, rerender }`.
Context: https://github.com/ariakit/ariakit/issues/3939#issuecomment-2258293118

Output `rerender` from `@ariakit/test`'s render.

---

.changeset/3983-fix-ios-smooth-scroll-restoration.md
packages/ariakit-react-core/src/dialog/utils/use-prevent-body-scroll.ts

Tested locally, not sure if i missed an edge case.
fixes: #3980

Make the iOS scroll restoration instant on Dialog close

---

.changeset/4011-fix-hovercard-hide-on-scroll-safari.md
packages/ariakit-react-core/src/hovercard/hovercard.tsx

Apparently, recent versions of Safari are triggering a `mousemove` event on scroll without any actual mouse movement, causing our hovercard tests to be flaky. This PR updates the hovercard logic to check for mouse movement before executing the code inside the `mousemove` event handler to hide the hovercard.

Fix hovercard hiding on scroll on Safari

---

.changeset/4018-tab-selected-accessible-when-disabled.md
examples/combobox-tabs/style.css
examples/combobox-tabs/test-browser.ts
packages/ariakit-react-core/src/focusable/focusable.tsx
packages/ariakit-react-core/src/tab/tab.tsx

Closes #3941
Updated the tab code to make sure the selected tab remains accessible to keyboard focus even when the `accessibleWhenDisabled` prop is set to `false`.

Keep selected tab accessible when disabled

---

.changeset/4039-combobox-value.md
components/combobox.md
examples/combobox-tabs-old/combobox.tsx
packages/ariakit-react/src/combobox.ts

A [`ComboboxValue`](https://ariakit.org/reference/combobox-value) component is now available. This _value_ component displays the current value of the combobox input without rendering any DOM elements or taking any HTML props. You can optionally pass a function as a child returning any React node based on the current value:
```jsx
<ComboboxProvider>
<Combobox />
<ComboboxValue>
{(value) => `Current value: ${value}`}
</ComboboxValue>
</ComboboxProvider>
```

Add ComboboxValue component to @ariakit/react

---

.changeset/4040-composite-item-remove-aria-selected.md
examples/menu-nested-combobox/test.ts
packages/ariakit-react-core/src/composite/composite-item.tsx

Composite items like [`ComboboxItem`](https://ariakit.org/reference/combobox-item) no longer have the `aria-selected` attribute automatically set when focused. This attribute was previously used to address an old bug in Google Chrome, but it's no longer needed. Now, it's only set when the item is actually selected, such as in a select widget or a multi-selectable combobox.
This change shouldn't affect most users since the `aria-selected` attribute is not part of the public API and is not recommended as a [CSS selector](https://ariakit.org/guide/styling#css-selectors) (use [`[data-active-item]`](https://ariakit.org/guide/styling#data-active-item) instead). However, if you have snapshot tests, you may need to update them.

Remove aria-selected from focused composite items

---

.changeset/0-4048-use-store-state.md
packages/ariakit-react-core/src/utils/store.tsx
packages/ariakit-react/package.json
packages/ariakit-react/src/index.ts
packages/ariakit-react/src/store.ts
website/build-pages/reference-utils.js

The [`useStoreState`](https://ariakit.org/reference/use-store-state) hook is now part of the public API. Previously used internally by dynamic `useState` hooks from Ariakit store objects, it is now available in the `@ariakit/react` package to ensure compatibility with the new React Compiler.
The following snippets are equivalent:
```js
const combobox = useComboboxStore();
const value = combobox.useState("value");
```
```js
const combobox = useComboboxStore();
const value = useStoreState(combobox, "value");
```
Besides working better with the new React Compiler, [`useStoreState`](https://ariakit.org/reference/use-store-state) is more flexible than `store.useState` as it accepts a store that is `null` or `undefined`, in which case the returned value will be `undefined`. This is useful when …

Expose useStoreState as a public API

---

website/build-pages/reference-utils.js

This was affecting `SelectValue`.
See https://ariakit.org/reference/select-value#fallback

Fix optional props being listed as required props in docs

---

.changeset/4056-tab-accessible-when-disabled.md
examples/tab-disabled/index.tsx
examples/tab-disabled/style.css
examples/tab-disabled/test.ts
packages/ariakit-react-core/src/tab/tab.tsx

This suggests reverting the unintended changes caused by https://github.com/ariakit/ariakit/pull/4018
See https://github.com/WordPress/gutenberg/pull/64637#issuecomment-2298634076

Make `accessibleWhenDisabled` `true` by default again

---

.changeset/4093-safari-menu-button-hide-mousedown.md
examples/dialog-menu/test-browser.ts
packages/ariakit-react-core/src/dialog/utils/use-hide-on-interact-outside.ts
packages/ariakit-react-core/src/focusable/focusable.tsx

This PR addresses a long-standing issue where `mousedown` on `MenuButton` hides the menu when it's inside a focusable ancestor (like a dialog) on Safari.
This occurs because Safari focuses on the nearest focusable ancestor when a button is clicked, instead of focusing on the button itself like other browsers. Ariakit normalizes this behavior in a non-intrusive way by restoring focus to the button, but it doesn't prevent the focusable ancestor from receiving focus (as it would also prevent other side effects like drag events, selection, etc.).
The problem is that allowing the focusable ancestor to receive focus also triggers the `hideOnInteractOutside` feature on dialogs. This PR adds a flag to the focused ancestor that's checked in the hiding logic.

Fix mousedown on MenuButton hiding Menu

---

.changeset/4093-composite-item-active-item-focus-visible.md
examples/composite/test.ts
packages/ariakit-react-core/src/focusable/focusable.tsx

Closes #4083
This PR sets the `data-focus-visible` attribute without relying on React to update the `focusVisible` state internally. This ensures `data-focus-visible` and other attributes like `data-active-item` are updated simultaneously (visually).
I tried `ReactDOM.flushSync`, but aside from potentially hurting performance, there were a few React warnings about calling this in lifecycle methods. We could ignore these warnings, but setting the data attribute imperatively seems to be a safer option.

Set data-focus-visible synchronously

---

.changeset/4101-dialog-nested-focus-trap-inert.md
examples/dialog-menu/test.ts
packages/ariakit-react-core/package.json
packages/ariakit-react-core/src/dialog/utils/disable-tree.ts
packages/ariakit-react-core/src/dialog/utils/is-focus-trap.ts
packages/ariakit-react-core/src/menu/menu-button.tsx
packages/ariakit-react-core/src/portal/portal.tsx

When a non-[`modal`](https://ariakit.org/reference/popover#modal) [`portal`](https://ariakit.org/reference/popover#portal) [`preserveTabOrder`](https://ariakit.org/reference/popover#preservetaborder) popover (e.g., `<Menu portal>`) is rendered within a modal dialog, the user cannot <kbd>Tab</kbd> out of the popover once it receives focus. This happens because the modal dialog disables the tree outside it, including the focus trap elements that allow users to <kbd>Tab</kbd> in and out of the nested popover.
This PR addresses the issue by ignoring focus trap elements in the `disableTreeOutside` function.
See test for more details.

Fix modal dialog disabling focus traps of nested dialogs

---

.changeset/4144-dialog-backdrop-performance-improvment.md
packages/ariakit-react-core/src/dialog/dialog-backdrop.tsx

Related to #4075
Although this doesn't fully address the performance issues mentioned in that post, it's probably better to use `useEffect` here anyway. There may be a frame where the backdrop is not visible or is behind some elements if `z-index` values differ, but in that case, users can set a static `z-index` for both the dialog and the backdrop element.
We should continue measuring to see what else we can do.

Improve performance on DialogBackdrop

---

.changeset/4164-composite-next-options.md
packages/ariakit-core/src/composite/composite-store.ts
packages/ariakit-react-core/src/tab/tab-panel.tsx

The [`next`](https://ariakit.org/reference/use-composite-store#next), [`previous`](https://ariakit.org/reference/use-composite-store#previous), [`up`](https://ariakit.org/reference/use-composite-store#up), and [`down`](https://ariakit.org/reference/use-composite-store#down) methods of the [composite store](https://ariakit.org/reference/use-composite-store) now accept an object as the first argument to override the composite state for that specific method. For example, you can pass a different [`activeId`](https://ariakit.org/reference/use-composite-store#activeId) value to the [`next`](https://ariakit.org/reference/use-composite-store#next) method so it returns the next item based on that value rather than the current active item in the composite store:
```js
const store = …
```

Add state override options to the composite store's next methods

---

.changeset/0-4169-tab-panel-scroll-restoration.md
examples/tab-panel-scroll-restoration-various/index.tsx
examples/tab-panel-scroll-restoration-various/style.css
examples/tab-panel-scroll-restoration-various/test-chrome-firefox.ts
examples/theme.css
packages/ariakit-react-core/src/disclosure/disclosure-content.tsx
packages/ariakit-react-core/src/tab/tab-panel.tsx
website/components/playground-client.tsx

Ariakit now supports scroll restoration for the [`TabPanel`](https://ariakit.org/reference/tab-panel) component. This allows you to control whether and how the scroll position is restored when switching tabs.
To enable scroll restoration, use the new [`scrollRestoration`](https://ariakit.org/reference/tab-panel#scrollrestoration) prop:
```jsx
// Restores the scroll position of the tab panel element when switching tabs
<TabPanel scrollRestoration />
```
By default, the scroll position is restored when switching tabs. You can set it to `"reset"` to return the scroll position to the top of the tab panel when changing tabs. Use the [`scrollElement`](https://ariakit.org/reference/tab-panel#scrollelement) prop to specify a different scrollable element:
```jsx
// Resets the scroll position of a …
```

Add scroll restoration functionality to TabPanel

---

.changeset/4202-collection-store-item-out-of-sync.md
packages/ariakit-core/src/collection/collection-store.ts
packages/ariakit-react-core/src/composite/composite-item.tsx

Currently, calling `store.item(id)` may return an item that has been previously removed from the collection/composite store. This occurs because we were searching for the item in the public store, which may lag behind the private store where items are registered synchronously one by one (this prevents multiple unnecessary updates when rendering several items).
This PR modifies the `item` method logic to use the private store instead of the batched public store.
I also updated the tabbable logic introduced in #4191 to consider only `item?.element` instead of `item?.element?.isConnected`. This is because when `isConnected` changes, it doesn't always trigger the `useStoreState` callback, as the component may not re-render or the state may not update in response to this DOM change.

Fix `collectionStore.item()` getting out of sync with current items

---

.changeset/4211-menu-store-sync-private-store.md
examples/menubar-navigation/menubar.tsx
examples/menubar-navigation/test-browser.ts
packages/ariakit-core/src/utils/store.ts

The `menuStore.item(id)` method isn't working on menu stores synced with other menu stores using the `store` prop.
This issue arises because the `__unstablePrivateStore` property (or any other custom property) wasn't being copied to the new store object when using `mergeStore`. This PR updates `mergeStore` to use `Object.assign`, ensuring the resulting store includes properties from the merged store objects.

Fix menu store not syncing internal items

---

packages/ariakit-react/.gitignore

This has been missing from the gitignore for a while. Generated with the "clean" script.

Add missing gitignore entry (store)

---

packages/ariakit-solid-core/src/group/group-label.tsx
packages/ariakit-solid-core/src/group/group.tsx
packages/ariakit-solid-core/src/heading/heading.tsx
packages/ariakit-solid-core/src/separator/separator.tsx
packages/ariakit-solid-core/src/utils/misc.ts

Parent: #4378
- `setRef`
- support `null` in `createRef`
- support special dollar syntax for expanding getters in `mergeProps`
- misc fixes, cleanups, and comments

[Solid] Util improvements

---

packages/ariakit-test/src/__tests__/blur-test.react.tsx
vitest.config.ts
vitest.setup.ts

Following #4400 up, this PR cleans up the test loader logic in a few ways:
- Instead of relying on a global variable, test files can be explicitly made exclusive to a loader by adding a suffix, e.g. `something-test.react.tsx` or `something-test.solid.tsx`. The "blur test" file was updated to reflect this pattern.
- Centralized loader logic and types in config file rather than setup.
- Cleaned up config a bit, leaning into the idea that it will always be run with a "loader" as parameter in a "matrix" type setup. E.g. `PLUGINS_BY_LOADER`.

Clean up test loader logic.

---

examples/select-group/index.react.tsx
examples/select-group/style.css

Fixes: #4395
The `SelectSeparator` component is deprecated. Users are now advised to use `SelectGroup` with custom CSS border styling to visually separate groups of items.

[docs] replace SelectSeparator with SelectGroup and border styling

---

package-lock.json
package.json
site/src/examples/separator/test.ts
vitest.config.ts
vitest.setup.ts

I updated the vitest configuration to include the React plugin, which is necessary when the tsconfig doesn't explicitly use React as the JSX import source.
I also updated the test import paths to allow the use of folders other than just `/examples`.

Update vitest config to include React plugin

---

.changeset/4531-react-popover-arrow-1.md
.changeset/4531-react-popover-arrow-2.md
packages/ariakit-react-core/src/popover/popover-arrow-path.ts
packages/ariakit-react-core/src/popover/popover-arrow.tsx

This pull request includes several enhancements and improvements to the `PopoverArrow` component in the `@ariakit/react-core` and `@ariakit/react` packages. The main changes include adding a new prop, improving the component's functionality, and refactoring the code for better maintainability.
Enhancements to `PopoverArrow` component:
* Added a new `borderWidth` prop to the `PopoverArrow` component to allow users to define the border width explicitly.
* Improved the `PopoverArrow` component to infer its border width from the popover’s `box-shadow` style when applicable, ensuring a consistent size regardless of the arrow's size.
* Modified the arrow’s SVG path to be more angled in the pointing direction for better visual accuracy.
Code refactoring and improvements:
* Refactored the …

Improve `PopoverArrow` SVG and add `borderWidth` features

---

.changeset/4535-react-dialog-focus-on-hide-prevent-scroll.md
examples/menu-combobox/test-browser.ts
packages/ariakit-react-core/src/dialog/dialog.tsx

Fixes #4324
When hiding a dialog or popover, the [`finalFocus`](https://ariakit.org/reference/dialog#finalfocus) element will no longer scroll into view. This change prevents scrolling issues when the element lies outside the viewport and mirrors the behavior of native HTML dialog and popover elements.

Fix scrolling issue when closing dialogs by clicking outside

---

.changeset/4539-react-composite-move-on-key-press-composing-text.md
packages/ariakit-react-core/src/composite/composite.tsx

Fixes #4388
Unfortunately, Playwright doesn't currently support IME or composition text, which prevents us from testing it properly. See https://github.com/microsoft/playwright/issues/5777

Fix composition text commands clashing with Composite's `moveOnKeyPress`

---

.changeset/4506-native-select-disabled-field-fix.md
examples/select-form-disabled/index.react.tsx
examples/select-form-disabled/style.css
examples/select-form-disabled/test.ts
packages/ariakit-react-core/src/select/select.tsx

Fixes: #4310
**Problem:**
When the `Select` component was rendered with the `disabled` prop, the hidden native `<select>` element used for form submission was still enabled. As a result, the form would submit a value for the disabled field, which is inconsistent with native HTML form behavior.
**Fix:**
This PR ensures that the native <select> element receives the disabled attribute, preventing its value from being included in the form submission when it is disabled.
A working example and tests have also been added to demonstrate and verify the fix.
Tests cover disabled behavior, keyboard interaction, and correct form submission logic.

[Select] Fix: prevent native select value from submitting when Select is disabled

---

.changeset/beige-fireants-agree.md
packages/ariakit-react-core/src/popover/popover-arrow.tsx

Use useId from util for backward compatibility

---

packages/ariakit-solid/readme.md

As I started looking into porting new components to Solid, I noticed that the contribution guide link points to the main guide instead of the Solid-specific one 🙂

[Doc]: fix contribution guide link on solid

---

packages/ariakit-solid-core/src/checkbox/checkbox.tsx
packages/ariakit-solid-core/src/utils/store.tsx

- Problem
When a component receives a dynamic store prop, Solid reactivity doesn't automatically respond to changes in the accessor. This causes stale state in components like Checkbox, where checked remains stuck even after the store changes. The underlying issue is that useStoreState subscribes to the initial store, but doesn't track the updates to the store
- Expected behaviour
When the store prop changes, the component should react to the new store, updating internal values like checked and aria-checked as needed.
- Fix
Introduced a utility to wrap useStoreState in a createMemo, which ensures that any change to the dynamic store accessor causes the value to be re-evaluated. This guarantees the component stays in sync with the current store.
Also added an effect inside useStore to …

Fix Solid checkbox dynamic store behaviour

---

.changeset/sad-pants-shout.md
packages/ariakit-core/src/utils/events.ts
packages/ariakit-react-core/src/focusable/focusable.tsx
packages/ariakit-react-core/src/utils/hooks.ts

When profiling why opening a `Combobox` with 100+ items feels laggy (it’s 100 list items, how slow could it be?), I noticed that `Focusable` (which is used by `Combobox` and a bunch of other things) installs global event listeners every time it mounts. With 100 items in a list, it’s 100 focusables – and, therefore, 200 `addGlobalEventListener` calls. This ends up taking ~30% of the total opening time:
This PR fixes this by introducing a global flag in `focusable.tsx` that prevents calling `addGlobalEventListener` more than once.

Improve open performance for long comboboxes by ~30%
